### ISSUE TITLE
No proper encoding for ids

### ISSUE THREAD

**Issue by douglaz** [sksamuel/elastic4s#1001]
If the id contains forward slashes (like a url) it will fail:

```scala
object EncodingTest extends App {
  import com.sksamuel.elastic4s.ElasticsearchClientUri
  import com.sksamuel.elastic4s.http.HttpClient
  import com.sksamuel.elastic4s.http.ElasticDsl._
  import scala.concurrent.Await
  import scala.concurrent.duration.Duration
  val client: HttpClient = HttpClient(ElasticsearchClientUri("localhost", 9200))

  assert(Await.result(client.execute(indexInto("urls", "blacklisted").withId("http://www.github.com/")), Duration.Inf).created)
}
```

```15:28:08.214 [main] DEBUG com.sksamuel.elastic4s.http.index.IndexImplicits$IndexHttpExecutable$ - Endpoint=/urls/blacklisted/http://www.github.com/
15:28:08.215 [main] DEBUG com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient - Executing elastic request PUT:/urls/blacklisted/http://www.github.com/?
15:28:08.348 [ForkJoinPool-1-worker-5] DEBUG com.sksamuel.elastic4s.http.ResponseHandler$ - Attempting to unmarshall response to com.sksamuel.elastic4s.http.index.IndexResponse
15:28:08.349 [ForkJoinPool-1-worker-5] DEBUG com.sksamuel.elastic4s.http.ResponseHandler$ - No handler found for uri [/urls/blacklisted/http://www.github.com/] and method [PUT]
Exception in thread "main" com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'No': was expecting 'null', 'true', 'false' or NaN
 at [Source: No handler found for uri [/urls/blacklisted/http://www.github.com/] and method [PUT]; line: 1, column: 3]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2839)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2812)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchToken(ReaderBasedJsonParser.java:2619)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1880)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3834)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2880)
	at com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper$class.readValue(ScalaObjectMapper.scala:190)
	at com.sksamuel.elastic4s.json.JacksonSupport$$anon$1.readValue(JacksonSupport.scala:11)
	at com.sksamuel.elastic4s.http.ResponseHandler$.fromEntity(ResponseHandler.scala:29)
	at com.sksamuel.elastic4s.http.DefaultResponseHandler$$anonfun$handle$1.apply(ResponseHandler.scala:37)
	at scala.util.Try$.apply(Try.scala:192)
	at com.sksamuel.elastic4s.http.DefaultResponseHandler.handle(ResponseHandler.scala:37)
	at com.sksamuel.elastic4s.http.NotFound404ResponseHandler.handle(ResponseHandler.scala:43)
	at com.sksamuel.elastic4s.http.HttpClient$$anonfun$execute$1.apply(HttpClient.scala:33)
	at com.sksamuel.elastic4s.http.HttpClient$$anonfun$execute$1.apply(HttpClient.scala:32)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by sksamuel** [comment]
Fixed in master, will be included in rc-1
