### ISSUE TITLE
GeoBounding box crashing because of com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to com.fasterxml.jackson.databind.node.ArrayNode on GeoBoundingBoxQueryBodyFn

### ISSUE THREAD

**Issue by SodaDev** [sksamuel/elastic4s#1003]
Start object is called too many times during query object creation which causes throwing an exception. Fix for that issue is very simple one. Since I have no access to the repo, I've attached simple patch for that fix. You can check that behaviour in the REPL by calling `XContentFactory.jsonBuilder().startObject().startObject()` which causes 
```
com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to com.fasterxml.jackson.databind.node.ArrayNode
java.lang.ClassCastException: com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to com.fasterxml.jackson.databind.node.ArrayNode
	at com.sksamuel.elastic4s.json.XContentBuilder.array(XContentBuilder.scala:22)
	at com.sksamuel.elastic4s.json.XContentBuilder.startObject(XContentBuilder.scala:209)
	at com.sksamuel.elastic4s.search.SearchDslTest$$anonfun$79.apply(SearchDslTest.scala:462)
	at com.sksamuel.elastic4s.search.SearchDslTest$$anonfun$79.apply(SearchDslTest.scala:462)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1679)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1692)
	at com.sksamuel.elastic4s.search.SearchDslTest.org$scalatest$OneInstancePerTest$$super$runTest(SearchDslTest.scala:18)
	at org.scalatest.OneInstancePerTest$class.runTest(OneInstancePerTest.scala:131)
	at com.sksamuel.elastic4s.search.SearchDslTest.runTest(SearchDslTest.scala:18)
	at org.scalatest.OneInstancePerTest$class.runTests(OneInstancePerTest.scala:181)
	at com.sksamuel.elastic4s.search.SearchDslTest.runTests(SearchDslTest.scala:18)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpec.run(FlatSpec.scala:1685)
	at org.scalatest.OneInstancePerTest$class.runTest(OneInstancePerTest.scala:128)
	at com.sksamuel.elastic4s.search.SearchDslTest.runTest(SearchDslTest.scala:18)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1750)
	at com.sksamuel.elastic4s.search.SearchDslTest.org$scalatest$OneInstancePerTest$$super$runTests(SearchDslTest.scala:18)
	at org.scalatest.OneInstancePerTest$class.runTests(OneInstancePerTest.scala:188)
	at com.sksamuel.elastic4s.search.SearchDslTest.runTests(SearchDslTest.scala:18)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpec.run(FlatSpec.scala:1685)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1340)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1334)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1334)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1500)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

Can be solved easily with patch:
[Fix_for_GeoBoundingBoxQueryBodyFn_builder__com_fasterxml_jackson_databind_node_ObjectNode_.patch.txt](https://github.com/sksamuel/elastic4s/files/1183487/Fix_for_GeoBoundingBoxQueryBodyFn_builder__com_fasterxml_jackson_databind_node_ObjectNode_.patch.txt)

```
Index: elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/queries/geo/GeoBoundingBoxQueryBodyFn.scala
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/queries/geo/GeoBoundingBoxQueryBodyFn.scala	(date 1500677355000)
+++ elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/queries/geo/GeoBoundingBoxQueryBodyFn.scala	(date 1501254217000)
@@ -7,7 +7,7 @@
 object GeoBoundingBoxQueryBodyFn {
 
   def apply(q: GeoBoundingBoxQueryDefinition): XContentBuilder = {
-    val builder = XContentFactory.jsonBuilder().startObject().startObject("geo_bounding_box")
+    val builder = XContentFactory.jsonBuilder().startObject("geo_bounding_box")
     builder.startObject(q.field)
 
     q.corners.foreach { corners =>
```

**Comment by SodaDev** [comment]
Start object is called too many times during query object creation which causes throwing an exception. Fix for that issue is very simple one. Since I have no access to the repo, I've attached simple patch for that fix. You can in the REPL that calling `XContentFactory.jsonBuilder().startObject().startObject()` causes 
```
com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to com.fasterxml.jackson.databind.node.ArrayNode
java.lang.ClassCastException: com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to com.fasterxml.jackson.databind.node.ArrayNode
	at com.sksamuel.elastic4s.json.XContentBuilder.array(XContentBuilder.scala:22)
	at com.sksamuel.elastic4s.json.XContentBuilder.startObject(XContentBuilder.scala:209)
	at com.sksamuel.elastic4s.search.SearchDslTest$$anonfun$79.apply(SearchDslTest.scala:462)
	at com.sksamuel.elastic4s.search.SearchDslTest$$anonfun$79.apply(SearchDslTest.scala:462)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1679)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1692)
	at com.sksamuel.elastic4s.search.SearchDslTest.org$scalatest$OneInstancePerTest$$super$runTest(SearchDslTest.scala:18)
	at org.scalatest.OneInstancePerTest$class.runTest(OneInstancePerTest.scala:131)
	at com.sksamuel.elastic4s.search.SearchDslTest.runTest(SearchDslTest.scala:18)
	at org.scalatest.OneInstancePerTest$class.runTests(OneInstancePerTest.scala:181)
	at com.sksamuel.elastic4s.search.SearchDslTest.runTests(SearchDslTest.scala:18)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpec.run(FlatSpec.scala:1685)
	at org.scalatest.OneInstancePerTest$class.runTest(OneInstancePerTest.scala:128)
	at com.sksamuel.elastic4s.search.SearchDslTest.runTest(SearchDslTest.scala:18)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1750)
	at com.sksamuel.elastic4s.search.SearchDslTest.org$scalatest$OneInstancePerTest$$super$runTests(SearchDslTest.scala:18)
	at org.scalatest.OneInstancePerTest$class.runTests(OneInstancePerTest.scala:188)
	at com.sksamuel.elastic4s.search.SearchDslTest.runTests(SearchDslTest.scala:18)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpec.run(FlatSpec.scala:1685)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1340)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1334)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1334)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1500)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

[Uploading Fix_for_GeoBoundingBoxQueryBodyFn_builder__com_fasterxml_jackson_databind_node_ObjectNode_.patch…]()
