### ISSUE TITLE
Failed to initialize connection: None of the configured nodes were available 

### ISSUE THREAD

**Issue by sravankumar24** [sksamuel/elastic4s#1021]
I am trying to connect to my local elastic search instance by 
val esSettings = Settings.builder().put("cluster.name", "cluster name").build()
 val esClient = TcpClient.transport(esSettings,ElasticsearchClientUri(host:port))

and trying to bulk insert using 

esClient.execute {
      bulk(
     //bulk insert code here 
      )
    }

esClient.close()

this piece of code is existing in an application (whose process is always up).
The connection is getting established for the first time that we run this, but if we try to run the second time (without killing the application) it fails with 
Failed to initialize connection: None of the configured nodes were available [{uhAnU8f}{uhAnU8fuSU23apQDfGCPXA}{BXaLbIxSSeWiL6tqAbHpMg}{127.0.0.1}{127.0.0.1:9330}]

But when I restart the entire process, the connection is successful for first time and fails the second time.
i.e the connection is only lasting for one bulk insert, if i try to re-establish the connection after closing, it fails with no configured nodes available.
Is there any other way other than  esClient.close() to close the client or any other ways to open..

-Sravan

**Comment by sksamuel** [comment]
You can open as many clients as you want, so closing one won't affect opening another.

**Comment by sravankumar24** [comment]
Hey Samuel, 
When I try not to close, i still get the none of the nodes were available exception after couple of runs. 

-Sravan

**Comment by sravankumar24** [comment]
Samuel, 
I tried with out closing and still same issue after couple of successful runs.
here is the full stack trace.

Failed to initialize connection: None of the configure nodes were available: [{uhAnU8f}{uhAnU8fuSU23apQDfGCPXA}{BXaLbIxSSeWiL6tqAbHpMg}{127.0.0.1}{127.0.0.1:9351}]
akka.actor.ActorInitializationException: akka://AvroSubscriberSystem/user/JobCoordinator/Listener_EDT_c08de9dd_ba4f_4be2_b7e8_5230c4015dfe_JobId2107: exception durin creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:174)
        at akka.actor.ActorCell.create(ActorCell.scala:607)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: avrosubscriber.exceptions.DatabaseConnectionException: Failed to initialize connection: None of the configured nodes were available: [{uhAnU8f}{uhAnU8fuSU3apQDfGCPXA}{BXaLbIxSSeWiL6tqAbHpMg}{127.0.0.1}{127.0.0.1:9351}]
        at avrosubscriber.actors.TopicListenerActor.<init>(TopicListenerActor.scala:120)
        at avrosubscriber.actors.TopicListenerActor$$anonfun$props$1.apply(TopicListenerActor.scala:35)
        at avrosubscriber.actors.TopicListenerActor$$anonfun$props$1.apply(TopicListenerActor.scala:35)
        at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
        at akka.actor.Props.newActor(Props.scala:213)
        at akka.actor.ActorCell.newActor(ActorCell.scala:562)
        at akka.actor.ActorCell.create(ActorCell.scala:588)
        ... 9 more
Caused by: NoNodeAvailableException[None of the configured nodes were available: [{uhAnU8f}{uhAnU8fuSU23apQDfGCPXA}{BXaLbIxSSeWiL6tqAbHpMg}{127.0.0.1}{127.0.0.1:9351]]; nested: NodeDisconnectedException[[uhAnU8f][127.0.0.1:9351][indices:admin/exists] disconnected];
        at org.elasticsearch.client.transport.TransportClientNodesService$RetryListener.onFailure(TransportClientNodesService.java:288)
        at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51)
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1024)
        at org.elasticsearch.transport.TransportService$Adapter.lambda$onNodeDisconnected$6(TransportService.java:851)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:527)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: NodeDisconnectedException[[uhAnU8f][127.0.0.1:9351][indices:admin/exists] disconnected]
