### ISSUE TITLE
GeoDistanceSortContentBuilder   XContentFactory.jsonBuilder(). startObject() .startObject("_geo_distance")

### ISSUE THREAD

**Issue by hzwuhao8** [sksamuel/elastic4s#1022]
def run() {
    import com.sksamuel.elastic4s.http.ElasticDsl._
    import com.sksamuel.elastic4s.http.ElasticDsl
    //XContentFactory.jsonBuilder().startObject("xs")
    val sort = geoSort("location").points(p).order(SortOrder.ASC)
    println(sort)

    val s = com.sksamuel.elastic4s.http.search.queries.SortContentBuilder(sort)
    println(s)
  }

GeoDistanceSortDefinition(location,List(),ArrayBuffer(50.4247460886713, 124.113464934083),None,None,None,Some(asc),None,None,None)
Exception in thread "main" com.fasterxml.jackson.core.JsonGenerationException: Can not write a field name, expecting a value
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1897)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeFieldName(UTF8JsonGenerator.java:185)
	at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.writeFieldName(JsonXContentGenerator.java:183)
	at org.elasticsearch.common.xcontent.XContentBuilder.field(XContentBuilder.java:246)
	at org.elasticsearch.common.xcontent.XContentBuilder.startObject(XContentBuilder.java:222)
	at com.sksamuel.elastic4s.http.search.queries.GeoDistanceSortContentBuilder$.apply(SortContentBuilder.scala:48)

 I read  org.elasticsearch.search.sort.GeoDistanceSortBuilder   
find 
 at line 325
    builder.startObject();
    builder.startObject(NAME);

I  think  
 
val builder = XContentFactory.jsonBuilder().startObject("_geo_distance")
 need change to 
val builder = XContentFactory.jsonBuilder(). startObject() .startObject("_geo_distance")

**Comment by tanvir-amit** [comment]
I am having the same issue.

**Comment by sksamuel** [comment]
This is fixed now in the latest 5.5.x build and master (6.0.0-rc1).
