### ISSUE TITLE
sortBy throws a JsonGenerationException

### ISSUE THREAD

**Issue by tanvir-amit** [sksamuel/elastic4s#1040]
The `sortBy` method throws this error: 

```
com.fasterxml.jackson.core.JsonGenerationException: Can not write a field name, expecting a value
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1897)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeFieldName(UTF8JsonGenerator.java:185)
	at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.writeFieldName(JsonXContentGenerator.java:183)
	at org.elasticsearch.common.xcontent.XContentBuilder.field(XContentBuilder.java:246)
	at org.elasticsearch.common.xcontent.XContentBuilder.startObject(XContentBuilder.java:222)
	at com.sksamuel.elastic4s.http.search.queries.GeoDistanceSortContentBuilder$.apply(SortContentBuilder.scala:48)
	at com.sksamuel.elastic4s.http.search.queries.SortContentBuilder$.apply(SortContentBuilder.scala:10)
	at com.sksamuel.elastic4s.http.search.SearchBodyBuilderFn$.$anonfun$apply$10(SearchBodyBuilderFn.scala:39)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.sksamuel.elastic4s.http.search.SearchBodyBuilderFn$.apply(SearchBodyBuilderFn.scala:39)
	at com.sksamuel.elastic4s.http.search.SearchImplicits$SearchShow$.show(SearchImplicits.scala:19)
	at com.sksamuel.elastic4s.http.search.SearchImplicits$SearchShow$.show(SearchImplicits.scala:18)
	at com.sksamuel.elastic4s.http.HttpClient.show(HttpClient.scala:20)
	at com.sksamuel.elastic4s.http.HttpClient.show$(HttpClient.scala:20)
	at com.sksamuel.elastic4s.http.HttpClient$$anon$1.show(HttpClient.scala:37)
	at com.loyalty.partnerLocation.api.services.ElasticSearchClient.getPartnerLocationsByParams(ElasticSearchClient.scala:22)
	at com.loyalty.partnerLocation.api.actor.Locator$$anonfun$receive$1.applyOrElse(Locator.scala:26)
	at akka.actor.Actor.aroundReceive(Actor.scala:502)
	at akka.actor.Actor.aroundReceive$(Actor.scala:500)
	at com.loyalty.partnerLocation.api.actor.Locator.aroundReceive(Locator.scala:13)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

This happens with this `SearchDefinition`:

```scala
val geoDistanceQueryDefinition = GeoDistanceQueryDefinition(
  field = "location",
  point = Some(43.65435, -79.38871),
  distanceStr = "100km"
)
search("partner-location") limit 100 query(geoDistanceQueryDefinition) sortBy GeoDistanceSortDefinition(
  field = "location",
  points = Seq(new GeoPoint(43.65435, -79.38871)),
  order = Some(SortOrder.ASC),
  unit = Some(DistanceUnit.KILOMETERS)
)
```

Also, including `geoDistance = Some(GeoDistance.PLANE)` in the `GeoDistanceSortDefinition` seems to crash the server.

The raw query that I am trying to achieve is: 

```json
{
  "query": {
        "geo_distance": {
          "distance": "100km", 
          "location": { 
            "lat":  43.65435,
            "lon": -79.38871
          }
        }
      },
   "sort": [
    {
      "_geo_distance": {
        "location": { 
          "lat":  43.65435,
          "lon": -79.38871
        },
        "order":         "asc",
        "unit":          "km", 
        "distance_type": "plane" 
      }
    }
  ]
}
```

Elastic4s versions tried: 5.4.4, 5.4.6, 5.4.11

**Comment by tanvir-amit** [comment]
@sksamuel I believe the error occurs in the `GeoDistanceSortContentBuilder` object on this line:

```scala
val builder = XContentFactory.jsonBuilder().startObject("_geo_distance")
```

**Comment by sksamuel** [comment]
I've added a test for this and it passes so I must have fixed it already in master.
