### ISSUE TITLE
Log4J dependency for http client

### ISSUE THREAD

**Issue by avdv** [sksamuel/elastic4s#1042]
Hi.

Using these dependencies:

```
val elasticsearchVersion = "5.4.3"
val elastic4sVersion = "5.4.11"

libraryDependencies ++= Seq(
  "com.sksamuel.elastic4s" %% "elastic4s-core" % elastic4sVersion,
  "com.sksamuel.elastic4s" %% "elastic4s-http" % elastic4sVersion,
  "org.elasticsearch" % "elasticsearch" % elasticsearchVersion
)
```

I receive the following exception at runtime:

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: java.lang.NoClassDefFoundError: org/apache/logging/log4j/Logger]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:251)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:250)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:412)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:284)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/apache/logging/log4j/Logger
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:424)
	at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:174)
	at scala.util.Try$.apply(Try.scala:209)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:174)
	at akka.stream.impl.Transform.apply(TraversalBuilder.scala:155)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:482)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:424)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:415)
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:496)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/Logger
	at org.elasticsearch.common.logging.Loggers.getLogger(Loggers.java:101)
	at org.elasticsearch.common.ParseField.<clinit>(ParseField.java:35)
	at org.elasticsearch.script.ScriptType.<clinit>(ScriptType.java:43)
	at com.sksamuel.elastic4s.script.ScriptDefinition$.apply$default$3(ScriptDefinition.scala:9)
	at com.sksamuel.elastic4s.script.ScriptApi.script(ScriptApi.scala:6)
	at com.sksamuel.elastic4s.script.ScriptApi.script$(ScriptApi.scala:6)
	at eve.search.controllers.AssetAggregator.script(AssetAggregator.scala:32)
	at eve.search.controllers.AssetAggregator.$anonfun$findAssets$1(AssetAggregator.scala:245)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:482)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:480)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.elasticsearch.common.logging.Loggers.getLogger(Loggers.java:101)
	at org.elasticsearch.common.ParseField.<clinit>(ParseField.java:35)
	at org.elasticsearch.script.ScriptType.<clinit>(ScriptType.java:43)
	at com.sksamuel.elastic4s.script.ScriptDefinition$.apply$default$3(ScriptDefinition.scala:9)
	at com.sksamuel.elastic4s.script.ScriptApi.script(ScriptApi.scala:6)
```

Apparently, the dependency on log4j only exists on the tcp client, but at least `log4j-api` seems to be required at runtime.

**Comment by sksamuel** [comment]
This is fixed in version 6, which has no es dependencies outside of the core rest jar.

**Comment by avdv** [comment]
OK, thanks. I'm closing this ticket in anticipation of a 6.x release... :smile:
