### ISSUE TITLE
ConnectionClosedException exception when connecting a new ES node

### ISSUE THREAD

**Issue by yanns** [sksamuel/elastic4s#1082]
First of all, thx for this amazing lib!
We are using the http client 6.0.0-beta2.

When elastic search is restarted, then the http client does not handle the re-connection and throws an exception:

```
root[ERROR] org.elasticsearch.client.http.ConnectionClosedException: Connection closed
root[ERROR] 	at org.elasticsearch.client.http.nio.protocol.HttpAsyncRequestExecutor.endOfInput(HttpAsyncRequestExecutor.java:344)
root[ERROR] 	at org.elasticsearch.client.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:261)
root[ERROR] 	at org.elasticsearch.client.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
root[ERROR] 	at org.elasticsearch.client.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
root[ERROR] 	at org.elasticsearch.client.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
root[ERROR] 	at org.elasticsearch.client.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
root[ERROR] 	at org.elasticsearch.client.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
root[ERROR] 	at org.elasticsearch.client.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
root[ERROR] 	at org.elasticsearch.client.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
root[ERROR] 	at org.elasticsearch.client.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
```

A better way would be to handle this case, closing the living connections, and starting a new pool.

**Comment by sksamuel** [comment]
It should be handled in the same way the Java Rest API does it. Which I don't know how.

**Comment by sksamuel** [comment]
Any suggestions on what to do here @yanns

**Comment by yanns** [comment]
I'll have a look at the java client when I find some time.
I guess this issue should be fixed there.

**Comment by sksamuel** [comment]
Yeah, closing this then.
