### ISSUE TITLE
Jackson `JsonParseException: Numeric value out of range of int` if total hits too big

### ISSUE THREAD

**Issue by john-niara** [sksamuel/elastic4s#1096]
I tried a `termsAggregation` with no query or filter on a large index. The total # of hits is therefore the number of documents in the index, which happens to be a little bigger than the maximum Java int. The result is a Jackson `JsonParseException`:

```
scala> client.execute {
     |   search("foo") size 0 aggs {
     |     termsAggregation("agg1").field("ip")
     |   }
     | }.await
com.fasterxml.jackson.databind.JsonMappingException: Numeric value (2285008210) out of range of int
 at [Source: {"took":4,"timed_out":false,"_shards":{"total":16,"successful":16,"skipped":0,"failed":0},"hits":{"total":2285008210,"max_score":0.0,"hits":[]},"aggregations":{"agg1":{"doc_count_error_upper_bound":5968991,"sum_other_doc_count":2118799242,"buckets":[{"key":"X.X.X.X","doc_count":77272200},{"key":"X.X.X.X","doc_count":13480849},{"key":"X.X.X.X","doc_count":10919314},{"key":"X.X.X.X","doc_count":9901298},{"key":"X.X.X.X","doc_count":9760396},{"key":"X.X.X.X","doc_count":9661884},{"key":"X.X.X.X","doc_count":9060126},{"key":"X.X.X.X","doc_count":8897304},{"key":"X.X.X.X","doc_count":8788192},{"key":"X.X.X.X","doc_count":8467405}]}}}; line: 1, column: 117]
 at [Source: {"took":4,"timed_out":false,"_shards":{"total":16,"successful":16,"skipped":0,"failed":0},"hits":{"total":2285008210,"max_score":0.0,"hits":[]},"aggregations":{"agg1":{"doc_count_error_upper_bound":5968991,"sum_other_doc_count":2118799242,"buckets":[{"key":"X.X.X.X","doc_count":77272200},{"key":"X.X.X.X","doc_count":13480849},{"key":"X.X.X.X","doc_count":10919314},{"key":"X.X.X.X","doc_count":9901298},{"key":"X.X.X.X","doc_count":9760396},{"key":"X.X.X.X","doc_count":9661884},{"key":"X.X.X.X","doc_count":9060126},{"key":"X.X.X.X","doc_count":8897304},{"key":"X.X.X.X","doc_count":8788192},{"key":"X.X.X.X","doc_count":8467405}]}}}; line: 1, column: 107] (through reference chain: com.sksamuel.elastic4s.http.search.SearchResponse["hits"]->com.sksamuel.elastic4s.http.search.SearchHits["total"])
  at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388)
  at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:348)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1600)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:513)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:400)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
  at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:400)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2896)
  at com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper$class.readValue(ScalaObjectMapper.scala:190)
  at com.sksamuel.elastic4s.json.JacksonSupport$$anon$1.readValue(JacksonSupport.scala:11)
  at com.sksamuel.elastic4s.http.ResponseHandler$.fromEntity(ResponseHandler.scala:36)
  at com.sksamuel.elastic4s.http.search.SearchImplicits$SearchHttpExecutable$$anon$3.doit(SearchImplicits.scala:64)
  at com.sksamuel.elastic4s.http.search.SearchImplicits$SearchHttpExecutable$$anon$3.doit(SearchImplicits.scala:62)
  at com.sksamuel.elastic4s.http.ResponseHandler$$anonfun$handle$1.apply(ResponseHandler.scala:13)
  at scala.util.Try$.apply(Try.scala:192)
  at com.sksamuel.elastic4s.http.ResponseHandler$class.handle(ResponseHandler.scala:13)
  at com.sksamuel.elastic4s.http.search.SearchImplicits$SearchHttpExecutable$$anon$3.handle(SearchImplicits.scala:62)
  at com.sksamuel.elastic4s.http.HttpClient$$anonfun$execute$1.apply(HttpClient.scala:33)
  at com.sksamuel.elastic4s.http.HttpClient$$anonfun$execute$1.apply(HttpClient.scala:32)
  at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
  at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (2285008210) out of range of int
 at [Source: {"took":4,"timed_out":false,"_shards":{"total":16,"successful":16,"skipped":0,"failed":0},"hits":{"total":2285008210,"max_score":0.0,"hits":[]},"aggregations":{"agg1":{"doc_count_error_upper_bound":5968991,"sum_other_doc_count":2118799242,"buckets":[{"key":"X.X.X.X","doc_count":77272200},{"key":"X.X.X.X","doc_count":13480849},{"key":"X.X.X.X","doc_count":10919314},{"key":"X.X.X.X","doc_count":9901298},{"key":"X.X.X.X","doc_count":9760396},{"key":"X.X.X.X","doc_count":9661884},{"key":"X.X.X.X","doc_count":9060126},{"key":"X.X.X.X","doc_count":8897304},{"key":"X.X.X.X","doc_count":8788192},{"key":"X.X.X.X","doc_count":8467405}]}}}; line: 1, column: 117]
  at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
  at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
  at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:928)
  at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:866)
  at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:694)
  at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:299)
  at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:279)
  at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
  ... 29 more
```

I tried two changes in elastic4s to fix this:

1. Change `Int` to `Long` in the relevant places in `elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/aggresponses.scala` and `responses.scala`, in particular the type for the `total` field in the `InnerHits` and `SearchHits` case classes and the code that computes them.
2. Add `mapper.configure(DeserializationFeature.USE_LONG_FOR_INTS, true)` in `/elastic4s-jackson/src/main/scala/com/sksamuel/elastic4s/jackson/JacksonSupport.scala`.

Even with both these changes, I still get the above error. So there's something I'm missing about how the JSON response is being deserialized.

If there is a workaround available I'd appreciate being pointed in the right direction. Or maybe it would be a reasonable change to use `Long` for the total hits, or make the type easily configurable. I'm happy to work on a PR if someone helps me understand why the changes I tried didn't do the trick.

**Comment by sksamuel** [comment]
Changing it to a Long would work I'm sure, I don't know why it would fail when you tried it. Feel free to PR it.

**Comment by sksamuel** [comment]
I've bumped all the ints to longs, it won't hurt anything. That's in master, and will be in rc1 today.
