### ISSUE TITLE
MalformedInputException in edtition 5.4.3

### ISSUE THREAD

**Issue by AlgerLin** [sksamuel/elastic4s#1097]
I got the exception below when query with non-ASCII terms in the edition 5.4.3, which seems to be caused by the unnecessary logging code. 

java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:72)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.addString(TraversableOnce.scala:357)
	at scala.collection.AbstractIterator.addString(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:323)
	at scala.collection.AbstractIterator.mkString(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:325)
	at scala.collection.AbstractIterator.mkString(Iterator.scala:1336)
	at com.sksamuel.elastic4s.http.HttpExecutable$RichRestClient.async(***HttpExecutable.scala:48***)
	at com.sksamuel.elastic4s.http.search.SearchImplicits$SearchHttpExecutable$.execute(SearchImplicits.scala:70)
	at com.sksamuel.elastic4s.http.search.SearchImplicits$SearchHttpExecutable$.execute(SearchImplicits.scala:41)
	at com.sksamuel.elastic4s.http.HttpClient$class.execute(HttpClient.scala:23)
	at com.sksamuel.elastic4s.http.HttpClient$$anon$1.execute(HttpClient.scala:37)

**Comment by AlgerLin** [comment]
Sorry for this misreport, I guess that just because the scala option "-encoding" not be applied on "sbt test", which work correctly in "sbt run".
