### ISSUE TITLE
CreateIndexTemplateBuilder, problem with MappingBuilderFn.buildWithName

### ISSUE THREAD

**Issue by mrForest13** [sksamuel/elastic4s#1115]
Hello, 

I have problem with 

`    req.mappings.foreach { mapping =>
      builder.addMapping(mapping.`type`, MappingBuilderFn.buildWithName(mapping, mapping.`type`))
    }`

The method buildWithName returns 

> com.sksamuel.elastic4s.json.XContentBuilder

, before update to 6.x this method returned 

> org.elasticsearch.common.xcontent.XContentBuilder

In my opinion this is the reason for calling the wrong method from:

> org.elasticsearch.action.admin.indices.template.put.PutIndexTemplateRequestBuilder

Instead of (it was called in the version 5.X)

> addMapping (String type, org.elasticsearch.common.xcontent.XContentBuilder source)

 is call (it is in version 6.X)

> addMapping(String type, Object... source)

This causes a validation error: source length must be > 1. The buildWithName method returns only one object, so it always ends with this error.

`        if (source.length % 2 != 0) {
            throw new IllegalArgumentException("mapping source must be pairs of fieldnames and properties definition.");
        }`

**Comment by sksamuel** [comment]
Do you have a full stack trace ?

**Comment by mrForest13** [comment]
yes i do.

`Exception in thread "main" java.lang.IllegalArgumentException: mapping source must be pairs of fieldnames and properties definition.
	at org.elasticsearch.action.admin.indices.mapping.put.PutMappingRequest.buildFromSimplifiedDef(PutMappingRequest.java:194)
	at org.elasticsearch.action.admin.indices.template.put.PutIndexTemplateRequest.mapping(PutIndexTemplateRequest.java:284)
	at org.elasticsearch.action.admin.indices.template.put.PutIndexTemplateRequestBuilder.addMapping(PutIndexTemplateRequestBuilder.java:136)
	at com.sksamuel.elastic4s.admin.CreateIndexTemplateBuilder$.$anonfun$apply$7(CreateIndexTemplateBuilder.scala:27)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.sksamuel.elastic4s.admin.CreateIndexTemplateBuilder$.apply(CreateIndexTemplateBuilder.scala:26)
	at com.sksamuel.elastic4s.index.IndexTemplateExecutables$CreateIndexTemplateExecutable$.apply(IndexTemplateExecutables.scala:19)
	at com.sksamuel.elastic4s.index.IndexTemplateExecutables$CreateIndexTemplateExecutable$.apply(IndexTemplateExecutables.scala:15)
	at com.sksamuel.elastic4s.TcpClient.execute(TcpClient.scala:34)
	at com.sksamuel.elastic4s.TcpClient.execute$(TcpClient.scala:32)
	at com.sksamuel.elastic4s.TcpClientConstructors$$anon$1.execute(TcpClient.scala:54)
	at core.setup.EsSchema.createIndexTemplate(EsSchema.scala:47)
	at core.setup.EsSchema.$anonfun$createAllIndices$2(EsSchema.scala:73)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.List.map(List.scala:295)
	at core.setup.EsSchema.$anonfun$createAllIndices$1(EsSchema.scala:73)
	at scala.collection.immutable.List.flatMap(List.scala:335)
	at core.setup.EsSchema.createAllIndices(EsSchema.scala:69)
	at core.setup.SystemSetup.$anonfun$install$1(SystemSetup.scala:27)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157`

**Comment by sksamuel** [comment]
Thanks, one more question - which version of elastic4s?

**Comment by mrForest13** [comment]
6.0.0-M4

**Comment by sksamuel** [comment]
can you try 6.0.0 rc1

**Comment by mrForest13** [comment]
same error

**Comment by sksamuel** [comment]
Fixed in master, and will be in next release.
