### ISSUE TITLE
Script sort with http client on v 5.4.0

### ISSUE THREAD

**Issue by amerpersonal** [sksamuel/elastic4s#1149]
Hi,

I'm using elastic4s version 5.4.0. I'm trying to use script sort. It works with TcpClient but won't work with HttpClient. It shows ScalaMatchError:

```
scala.MatchError: ScriptSortDefinition
at com.sksamuel.elastic4s.http.search.queries.SortContentBuilder$.apply(SortContentBuilder.scala:9)
	at com.sksamuel.elastic4s.http.search.SearchBodyBuilderFn$.$anonfun$apply$10(SearchBodyBuilderFn.scala:39)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.List.map(List.scala:295)
	at com.sksamuel.elastic4s.http.search.SearchBodyBuilderFn$.apply(SearchBodyBuilderFn.scala:39)
```

If I look at a code in SortContentBuilder.scala, it looks like:

```
def apply(sort: SortDefinition): XContentBuilder = sort match {
    case fs: FieldSortDefinition => FieldSortContentBuilder(fs)
  }
```

No match for `ScriptSortDefinition`. Currently solution is to use decprecated tcp client. I didn't try newer versions because it will break some other things. Is this solved in newer versions and, if not, when it will be?

**Comment by sksamuel** [comment]
Yes its fixed in newer versions.
