### ISSUE TITLE
java.lang.NullPointerException in ElasticError.parse

### ISSUE THREAD

**Issue by obruchez** [sksamuel/elastic4s#1159]
I'm regularly getting this exception in my application while bulk indexing documents (Elastic4s 6.0.2):

java.lang.NullPointerException: null
	at com.sksamuel.elastic4s.http.ElasticError$.parse(ElasticError.scala:21)
	at com.sksamuel.elastic4s.http.DefaultResponseHandler.handle(ResponseHandler.scala:48)
	at com.sksamuel.elastic4s.http.HttpClient$$anonfun$execute$1.apply(HttpClient.scala:67)
	at com.sksamuel.elastic4s.http.HttpClient$$anonfun$execute$1.apply(HttpClient.scala:65)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

I'm currently investigating and trying to understand what's happening.

**Comment by obruchez** [comment]
It seems that bulk indexing my documents using batches (~100) instead of indexing them all at the same time (thousands of documents) eliminates this exception.

**Comment by sksamuel** [comment]
Fixed in master thanks.
