### ISSUE TITLE
Timeout exceptions don't point to elastic4s

### ISSUE THREAD

**Issue by francisdb** [sksamuel/elastic4s#1165]
We are getting exceptions from `org.apache.http.nio.pool.AbstractNIOConnPool` but nothing in the stack points to elastic4s. This is quite annoying as we have multiple libs using apache http client.

It would be better if elastic4s could wrap these exceptions and also provide some more info on what url/method and timeout was in use at that time?

see also
https://issues.apache.org/jira/browse/HTTPCLIENT-1880
https://stackoverflow.com/questions/42089736/timeoutexception-for-closeablehttpasyncclient

```
java.util.concurrent.TimeoutException: null
    at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:364)
    at org.apache.http.nio.pool.AbstractNIOConnPool.processNextPendingRequest(AbstractNIOConnPool.java:344)
    at org.apache.http.nio.pool.AbstractNIOConnPool.release(AbstractNIOConnPool.java:318)
    at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.releaseConnection(PoolingNHttpClientConnectionManager.java:303)
    at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.releaseConnection(AbstractClientExchangeHandler.java:239)
    at org.apache.http.impl.nio.client.MainClientExec.responseCompleted(MainClientExec.java:387)
    at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:168)
    at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
    at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
    at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
    at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
    at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
    at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by sksamuel** [comment]
The exception must get propagated out into the e4s Future ?

**Comment by francisdb** [comment]
Yes they come out of the future, but the stack trace does not contain anything elastic4s / elasticsearch. In our app this ends up in the generic error handler that logs the error as above from which it is hard to find out which of the libraries caused this.

We can wrap client.execute to fix this in our code. (recover and re-throw with proper context)

Feel free to close this issue if you don't see the value.

**Comment by sksamuel** [comment]
I can see the value. I'll introduce com.sksamuel.elastic4s.Exception or something and wrap in that.

**Comment by sksamuel** [comment]
I've added something to 6.1, let me know if it's good.

**Comment by francisdb** [comment]
Will do, but we also set some higher timeouts so might take some time for this one to pop up again.
