### ISSUE TITLE
JavaClientExceptionWrapper Exception

### ISSUE THREAD

**Issue by krullgit** [sksamuel/elastic4s#1211]
Hi, I'm getting this exception while performing SearchIterator and fuzzy Queries. I didn't try match or term queries but I expect it wouldn't help. The error occurs when trying a size bigger than 1000. I don't know the exact value but 1100 is already to high. (1001 works as well)
e.g.: search("index").size(1100) 

`Exception in thread "main" com.sksamuel.elastic4s.http.JavaClientExceptionWrapper
	at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient$$anon$1.onFailure(ElasticsearchJavaRestClient.scala:40)
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:608)
	at org.elasticsearch.client.RestClient$1.retryIfPossible(RestClient.java:399)
	at org.elasticsearch.client.RestClient$1.failed(RestClient.java:378)
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:419)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:375)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:263)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:492)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:213)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by sksamuel** [comment]
Try printing out the query (turn logging on com.sksamuel to debug to get the json) and send it directly to elasticsearch to see what happens.

**Comment by krullgit** [comment]
Ok, I did it with the client.show  command described in the README and here is my result:
`{"query":{"fuzzy":{"categories":{"value":"Clothing","fuzziness":"1"}}},"size":10000}`

I'm getting the following error in elastic:
```
{
  "statusCode": 504,
  "error": "Gateway Timeout",
  "message": "Client request timeout"
}
```

So I set according to google the elasticsearch.requestTimeout: 300000 in the kibana.yml and voila.
The query above works (I can go up to 10000 now) . But what is it that the kibana.yml has any effects on my scala program?


Unfortunately for my second that doesn't work for the second query. Here it is:
`{"query":{"terms":{"asin.keyword":["B000OZFZ38","B006BCN1KW","B00EVYOCIM","B003AJIX48","B00J9G31K2","B000VS9ZHU","B000VSFWMM","B003CGRVRY","B008E71ECE","B004W5H7TG","B00015UY6E","B002Q4VBBK","B002XKQ2YI","B00113KUZK","B005SH9L6Y","B007KAHQN2","B0061IWV9S","B0096U7292","B00AK9JRPU","B00H5GWE9C","B000HDLWIE","B004URVU9Y","B005NC9R40","B007KAHRIG","B007KAHTDY","B008R6S6GO","B00AK9JWW8","B008YNHZ7Q","B008UL9728","B00DTHQJA6","B00DTHQIX4","B00DB8CFAG","B00B7YFGY8","B00BHXUEFA","B00009PM1W","B001CSIFKQ","B002L7AH6C","B006T85XC2","B009SO1SFK","B008DYIARK","B00AK9JNMM","B00BHXUHKW","B00DTHQIWU","B00HFKMGZK","B00H5GWA8C","B00IX4DTG2","B006V7X7GU","B007VI5ZQS","B007T930U2","B00BHXUFQI","B00DTHQIS4","B00EJQSH74","B00B7YFHP6","B00J3RI8I2","B002PKAQCU","B005SH9L6O","B00FRSGZ9A","B00DTHQISY","B00DTHQJ8I","B00KPXNA6I","B00KC1YA12","B004QEYTF8","B0047N181Q","B0045OW30C","B0045EPK0C","B00472MP0U","B0046HAIAK","B00466IEBG","B003EEM052","B004HEX1ME","B004HEX1HY","B004HEX1OW","B004IK85E6","B004FPYP0C","B004JHY7CM","B003JKKKL2","B005EPG8QQ","B005EPGCM6","B0058MMMCE","B005C2XP6C","B0058GG0UA","B0058SOBUY","B0029NZZXI","B002CVTWGI","B006M9XDL6","B006JXHH8U","B005ZVIIY4","B005DZLHUO","B007WR2UDY","B007WR2UF2","B00889PL7M","B00889PQAY","B00889YX62","B00889YYX4","B0088AYWAS","B0086VOWXQ","B0078JAJLG","B007CVB7O8","B007IRVZ8O","B006YVWHJ6"]}},"size":10000}`

I have this one in a loop with each 100 terms. After 80 loops its slows down significantly, but make it till 100 (finish). When I send bigger packages like 500 terms it slows down as well but don't get to the finish line and crashes with JavaClientExceptionWrapper at 16 loops or so. That's very strange I think. Is my harddrive broken? I don't get it.

**Comment by sksamuel** [comment]
You're probably just overloading the machine you're running it on. Either way, it's not an issue with this library and so you're likely to get more help if you ask in the elasticsearch forums and paste in the raw json.

**Comment by obruchez** [comment]
For reference, I just updated from 6.0.4 to 6.1.2 and I'm also getting a JavaClientExceptionWrapper exception. I will investigate.

com.sksamuel.elastic4s.http.JavaClientExceptionWrapper
[info] com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient$$anon$1.onFailure(ElasticsearchJavaRestClient.scala:40)
[info] org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:608)
[info] org.elasticsearch.client.RestClient$1.retryIfPossible(RestClient.java:399)
[info] org.elasticsearch.client.RestClient$1.failed(RestClient.java:378)
[info] org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
[info] org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:419)
[info] org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestFailed(AbstractClientExchangeHandler.java:335)
[info] org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$100(AbstractClientExchangeHandler.java:62)
[info] org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.failed(AbstractClientExchangeHandler.java:378)
[info] org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
[info] org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalPoolEntryCallback.failed(PoolingNHttpClientConnectionManager.java:504)
[info] org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
[info] org.apache.http.nio.pool.RouteSpecificPool.failed(RouteSpecificPool.java:163)
[info] org.apache.http.nio.pool.AbstractNIOConnPool.requestFailed(AbstractNIOConnPool.java:542)
[info] org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.failed(AbstractNIOConnPool.java:817)
[info] org.apache.http.impl.nio.reactor.SessionRequestImpl.failed(SessionRequestImpl.java:160)
[info] org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:173)
[info] org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145)
[info] org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
[info] org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192)
[info] org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
[info] java.lang.Thread.run(Thread.java:745)

**Comment by Dacxidoodle** [comment]
I'm getting connection exception trying to connect to an aws ES service. My local is able to hit the http service using browser but not on the play framework code.

val client = ElasticClient(ElasticProperties("https://host?ssl=true")


I've been trying the example from the git sample code: https://github.com/sksamuel/elastic4s/blob/master/samples/elastic4s-http-client-sbt/src/main/scala/com/sksamuel/elastic4s/samples/HttpClientExampleApp.scala


play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[JavaClientExceptionWrapper: java.net.ConnectException]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:274)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:194)
        at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:347)
        at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:345)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:414)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
Caused by: com.sksamuel.elastic4s.http.JavaClientExceptionWrapper: java.net.ConnectException
        at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient$$anon$1.onFailure(ElasticsearchJavaRestClient.scala:53)
        at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:629)
        at org.elasticsearch.client.RestClient$1.retryIfPossible(RestClient.java:419)
        at org.elasticsearch.client.RestClient$1.failed(RestClient.java:398)
        at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:419)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestFailed(AbstractClientExchangeHandler.java:335)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$100(AbstractClientExchangeHandler.java:62)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.failed(AbstractClientExchangeHandler.java:378)
        at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
Caused by: java.net.ConnectException: null
        at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:168)
        at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:561)
        at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:822)
        at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:183)
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:210)
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:155)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
        at java.lang.Thread.run(Thread.java:748)
