### ISSUE TITLE
java.util.concurrent.TimeoutException sometimes arise

### ISSUE THREAD

**Issue by dacr** [sksamuel/elastic4s#1261]
using elastic4s 6.1.3 with elasticsearch 6.1.2, I got sometimes concurrent.TimeoutException while doing a huge bulk inserts operation : 

```
[info] ElasticExperimentsFetchTest:
[info] - insert and fetch *** FAILED ***
[info]   com.sksamuel.elastic4s.http.JavaClientExceptionWrapper: java.util.concurrent.TimeoutException
[info]   at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient$$anon$1.onFailure(ElasticsearchJavaRestClient.scala:40)
[info]   at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:608)
[info]   at org.elasticsearch.client.RestClient$1.retryIfPossible(RestClient.java:399)
[info]   at org.elasticsearch.client.RestClient$1.failed(RestClient.java:378)
[info]   at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
[info]   at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:419)
[info]   at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestFailed(AbstractClientExchangeHandler.java:335)
[info]   at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$100(AbstractClientExchangeHandler.java:62)
[info]   at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.failed(AbstractClientExchangeHandler.java:378)
[info]   at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
[info]   ...
[info]   Cause: java.util.concurrent.TimeoutException:
[info]   at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:364)
[info]   at org.apache.http.nio.pool.AbstractNIOConnPool.processNextPendingRequest(AbstractNIOConnPool.java:344)
[info]   at org.apache.http.nio.pool.AbstractNIOConnPool.release(AbstractNIOConnPool.java:318)
[info]   at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.releaseConnection(PoolingNHttpClientConnectionManager.java:303)
[info]   at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.releaseConnection(AbstractClientExchangeHandler.java:239)
[info]   at org.apache.http.impl.nio.client.MainClientExec.responseCompleted(MainClientExec.java:387)
[info]   at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:168)
[info]   at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
[info]   at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
[info]   at org.apache.http.impl.nio.client.InternalRequestExecutor.inputReady(InternalRequestExecutor.java:83)
[info]   ...
```

The big insertions is done this way (`for` comprehension on futures) : 
```
    val insertResults = for {
      cleaned <- doClean // delete any existing index
      created <- doCreateTestIndex // create the index
      refreshDisabled <- doUpdateIndexRefreshInterval("-1") // To accelerate insertion
      responses <- insertEvents // bulk operation insert all events
      refreshEnabled <- doUpdateIndexRefreshInterval("10s") // revert back to a normal behavior
      refreshed <- doRefreshIndex // to wait for every to be available for search...
    } yield {
      responses
    }
```
each bulk is composed of ~1000 events, and I'm trying to insert 500000 events and unfortunately I got some time that concurrent TimeoutException, and almost systematically after a fresh elasticsearch restart.

**Comment by dacr** [comment]
Here a way to reproduce the issue using ammonite scala console and the following gist : 
https://gist.github.com/dacr/7060a2d55bc88135944502becb4eb0df

Here the result I systematically get using this code sample (I let the refreshInterval to the default value) :
```
...
dcr-dcr@ Future.sequence(rcs).await 
com.sksamuel.elastic4s.http.JavaClientExceptionWrapper: java.util.concurrent.TimeoutException
  com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient$$anon$1.onFailure(ElasticsearchJavaRestClient.scala:40)
  org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:608)
  org.elasticsearch.client.RestClient$1.retryIfPossible(RestClient.java:399)
  org.elasticsearch.client.RestClient$1.failed(RestClient.java:378)
  org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
  org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:419)
  org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestFailed(AbstractClientExchangeHandler.java:335)
  org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$100(AbstractClientExchangeHandler.java:62)
  org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.failed(AbstractClientExchangeHandler.java:378)
  org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
  org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalPoolEntryCallback.failed(PoolingNHttpClientConnectionManager.java:504)
  org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
  org.apache.http.nio.pool.AbstractNIOConnPool.fireCallbacks(AbstractNIOConnPool.java:454)
  org.apache.http.nio.pool.AbstractNIOConnPool.release(AbstractNIOConnPool.java:323)
  org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.releaseConnection(PoolingNHttpClientConnectionManager.java:303)
  org.apache.http.impl.nio.client.AbstractClientExchangeHandler.releaseConnection(AbstractClientExchangeHandler.java:239)
  org.apache.http.impl.nio.client.MainClientExec.responseCompleted(MainClientExec.java:387)
  org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:168)
  org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
  org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
  org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
  org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
  org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
  org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
  org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
  org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
  org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
  org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
  org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
  org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
  java.lang.Thread.run(Thread.java:748)
java.util.concurrent.TimeoutException
  org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:364)
  org.apache.http.nio.pool.AbstractNIOConnPool.processNextPendingRequest(AbstractNIOConnPool.java:344)
  org.apache.http.nio.pool.AbstractNIOConnPool.release(AbstractNIOConnPool.java:318)
  org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.releaseConnection(PoolingNHttpClientConnectionManager.java:303)
  org.apache.http.impl.nio.client.AbstractClientExchangeHandler.releaseConnection(AbstractClientExchangeHandler.java:239)
  org.apache.http.impl.nio.client.MainClientExec.responseCompleted(MainClientExec.java:387)
  org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:168)
  org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
  org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
  org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
  org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
  org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
  org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
  org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
  org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
  org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
  org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
  org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
  org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
  java.lang.Thread.run(Thread.java:748)

```

**Comment by bursalihilal** [comment]
I have the same issue

`

java.util.concurrent.TimeoutException: null
--
at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:364) ~[org.apache.httpcomponents.httpcore-nio-4.4.5.jar:4.4.5]
at org.apache.http.nio.pool.AbstractNIOConnPool.processNextPendingRequest(AbstractNIOConnPool.java:344) ~[org.apache.httpcomponents.httpcore-nio-4.4.5.jar:4.4.5]
at org.apache.http.nio.pool.AbstractNIOConnPool.release(AbstractNIOConnPool.java:318) ~[org.apache.httpcomponents.httpcore-nio-4.4.5.jar:4.4.5]
at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.releaseConnection(PoolingNHttpClientConnectionManager.java:303) ~[org.apache.httpcomponents.httpasyncclient-4.1.2.jar:4.1.2]
at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.releaseConnection(AbstractClientExchangeHandler.java:239) ~[org.apache.httpcomponents.httpasyncclient-4.1.2.jar:4.1.2]
at org.apache.http.impl.nio.client.MainClientExec.responseCompleted(MainClientExec.java:387) ~[org.apache.httpcomponents.httpasyncclient-4.1.2.jar:4.1.2]
at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:168) ~[org.apache.httpcomponents.httpasyncclient-4.1.2.jar:4.1.2]
at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436) ~[org.apache.httpcomponents.httpcore-nio-4.4.5.jar:4.4.5]
at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326) ~[org.apache.httpcomponents.httpcore-nio-4.4.5.jar:4.4.5]
at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) ~[org.apache.httpcomponents.httpcore-nio-4.4.5.jar:4.4.5]
at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) ~[org.apache.httpcomponents.httpasyncclient-4.1.2.jar:4.1.2]
at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) ~[org.apache.httpcomponents.httpasyncclient-4.1.2.jar:4.1.2]
at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[org.apache.httpcomponents.httpcore-nio-4.4.5.jar:4.4.5]
at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[org.apache.httpcomponents.httpcore-nio-4.4.5.jar:4.4.5]
at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[org.apache.httpcomponents.httpcore-nio-4.4.5.jar:4.4.5]
at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[org.apache.httpcomponents.httpcore-nio-4.4.5.jar:4.4.5]
at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[org.apache.httpcomponents.httpcore-nio-4.4.5.jar:4.4.5]
at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[org.apache.httpcomponents.httpcore-nio-4.4.5.jar:4.4.5]
at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588) ~[org.apache.httpcomponents.httpcore-nio-4.4.5.jar:4.4.5]
 

`

**Comment by codepfleger** [comment]
You can set the setConnectionRequestTimeout to a higher value (default is 500) to solve this problem.

`clientBuilder.setRequestConfigCallback(requestConfigBuilder -> requestConfigBuilder.setConnectionRequestTimeout(10000))`

**Comment by sksamuel** [comment]
Right, I mean it's not an elastic4s issue. You're just sending too much data to ES at once.
You could look at a reactive streams implementation.

**Comment by razem-io** [comment]
@codepfleger this information is so important! I switched from the Tcp to the Http client because we updated our elasticsearch cluster.
Even if it is an elasticsearch issue the same code works with the TcpClient without a problem. Switching to http and out of a sudden we got over 900 timeout exceptions in a few minutes. Before we never even had a timeout exception.

Perhaps it would be a good idea to override the default timeout to mirror the behaviour of the TcpClient.

For the lazy people:
```val client = HttpClient(
    ElasticsearchClientUri(host, port),
    (requestConfigBuilder: RequestConfig.Builder) => { requestConfigBuilder.setConnectionRequestTimeout(60000)},
    (httpClientBuilder: HttpAsyncClientBuilder) => { httpClientBuilder })```

**Comment by sksamuel** [comment]
These are the default values in the apache http client. Perhaps we should override them to a more sensible value as you say.

**Comment by dacr** [comment]
@razem-io for even more lazy people, all the lines and the imports :
```
import org.apache.http.client.config.RequestConfig
import org.apache.http.impl.nio.client.HttpAsyncClientBuilder
val client = ElasticClient(
  ElasticsearchClientUri("127.0.0.1", 9200),
  (requestConfigBuilder: RequestConfig.Builder) => { requestConfigBuilder.setConnectionRequestTimeout(60000)},
  (httpClientBuilder: HttpAsyncClientBuilder) => { httpClientBuilder }
)
```

**Comment by abdvel** [comment]
hi,
I have the same issue.
How to add setConnectionRequestTimeout in Aws4ElasticClient?

This is my configuration
```
val esConfig = Aws4ElasticConfig(elasticEndpoint, awsAccessKey, awsSecretKey, awsRegion)
val esClient = Aws4ElasticClient(esConfig)
```
I got always concurrent.TimeoutException when multiple request

Thank you for help.

**Comment by ikr0m** [comment]
We can also use elasticsearch timeouts
https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_timeouts.html
```
RestClientBuilder builder = RestClient.builder(
    new HttpHost("localhost", 9200))
    .setRequestConfigCallback(
        new RestClientBuilder.RequestConfigCallback() {
            @Override
            public RequestConfig.Builder customizeRequestConfig(
                    RequestConfig.Builder requestConfigBuilder) {
                return requestConfigBuilder
                    .setConnectTimeout(5000)
                    .setSocketTimeout(60000);
            }
        });
```
