### ISSUE TITLE
Cannot create index in embedded node - Logger Dependency Issue?

### ISSUE THREAD

**Issue by jakehschwartz** [sksamuel/elastic4s#1268]
Hello,

Sorry if you answered this somewhere else, I did a quick search a didn't see anything.

I'm using version 5.5.7

I've created a local node and an http client and attempted to create an index:
```
val localNode = LocalNode("mycluster", "/tmp/datapath")
val client = HttpClient(ElasticsearchClientUri(s"elasticsearch://${localNode.ipAndPort}"))

Await.result(client.execute(createIndex("index-name")), Duration.Inf)
```

When I get the following error and stack trace:
```
PUT http://127.0.0.1:9200/index-name: HTTP/1.1 500 Internal Server Error
{"error":{"root_cause":[{"type":"class_cast_exception","reason":"org.apache.logging.log4j.simple.SimpleLoggerContext cannot be cast to org.apache.logging.log4j.core.LoggerContext"}],"type":"class_cast_exception","reason":"org.apache.logging.log4j.simple.SimpleLoggerContext cannot be cast to org.apache.logging.log4j.core.LoggerContext"},"status":500}
org.elasticsearch.client.ResponseException: PUT http://127.0.0.1:9200/index-name: HTTP/1.1 500 Internal Server Error
{"error":{"root_cause":[{"type":"class_cast_exception","reason":"org.apache.logging.log4j.simple.SimpleLoggerContext cannot be cast to org.apache.logging.log4j.core.LoggerContext"}],"type":"class_cast_exception","reason":"org.apache.logging.log4j.simple.SimpleLoggerContext cannot be cast to org.apache.logging.log4j.core.LoggerContext"},"status":500}
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:354)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:343)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:745)
```

I also see the following log message when starting up:
```
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
```

I assume there is some dependency issue, I currently have the following log dependencies in the project:
```
    "org.slf4j" % "slf4j-simple" % "1.7.25",
    "com.typesafe.scala-logging" %% "scala-logging" % "3.7.2"
```

Thanks again.

**Comment by sksamuel** [comment]
The embedded node has now been removed.
