### ISSUE TITLE
Elastic embedded not working (might be wrong netty version)

### ISSUE THREAD

**Issue by polarke** [sksamuel/elastic4s#1281]
I am trying to initialize an embedded server with the following code:
`
object ElasticServer {
  val node = LocalNode("elasticsearch", "/tmp/elastic")
  val Server = node.http(false)
}
`

I got the following exception:
>java.lang.ExceptionInInitializerError:
...
>Cause: io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioServerSocketChannel
[info]   at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:41)
...
> Cause: java.lang.NoSuchMethodError: io.netty.channel.DefaultChannelId.newInstance()Lio/netty/channel/DefaultChannelId;
[info]   at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:107)

It seems a wrong version of netty is used to create network channel. In build.sbt, you have lines of library dependencies commented out.
[https://github.com/sksamuel/elastic4s/blob/master/build.sbt#L71-L93](url)
Could these lines of dependencies are actually necessary for elastic-embedding?

**Comment by polarke** [comment]
Sorry that the problem is because I have two versions of netty in my project.

So I am closing this issue.
