### ISSUE TITLE
NullPointer exception while creating LocalNode

### ISSUE THREAD

**Issue by Lugghawk** [sksamuel/elastic4s#1290]
Hi, I'm using elastic4s `6.1.4` and have tried `6.1.3` also and creating LocalNodes seems to be failing for me.

Here's the code I'm using to create the node.

```scala
import better.files.File

def client(): HttpClient = {
    val tmpdir = File.newTemporaryDirectory()
    val node = LocalNode("cluster", tmpdir.pathAsString)
    node.http(true)
}
```

The line that is failing is the `LocalNode("cluster", tmpdir.pathAsString)`, and I've tried putting other paths there also ("/tmp/elastic") and no such luck. Here's the stacktrace I'm getting from the failure.

```
java.lang.NullPointerException
	at org.elasticsearch.cluster.node.DiscoveryNodes.isAllNodes(DiscoveryNodes.java:233)
	at org.elasticsearch.cluster.node.DiscoveryNodes.resolveNodes(DiscoveryNodes.java:304)
	at org.elasticsearch.action.support.nodes.TransportNodesAction.resolveRequest(TransportNodesAction.java:148)
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.<init>(TransportNodesAction.java:166)
	at org.elasticsearch.action.support.nodes.TransportNodesAction.doExecute(TransportNodesAction.java:89)
	at org.elasticsearch.action.support.nodes.TransportNodesAction.doExecute(TransportNodesAction.java:52)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:167)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:139)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:81)
	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83)
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:405)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:394)
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:706)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:46)
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:53)
	at com.sksamuel.elastic4s.embedded.InternalLocalNode.<init>(LocalNode.scala:76)
	at com.sksamuel.elastic4s.embedded.LocalNode$.apply(LocalNode.scala:175)
	at com.sksamuel.elastic4s.embedded.LocalNode$.apply(LocalNode.scala:181)
	at com.sksamuel.elastic4s.embedded.LocalNode$.apply(LocalNode.scala:199)
	at com.hoggit.missionhub.http.MissionLocalStorage.$init$(MissionRegistryActorSpec.scala:28)
```

**Comment by Lugghawk** [comment]
To add to this, I debugged a little into the elastic4s code to see what might be NullPointering. The line in DiscoveryNodes(~233) is `return nodesIds == null || nodesIds.length == 0 || (nodesIds.length == 1 && nodesIds[0].equals("_all"));` and in my case, `nodesIds[0]` is `null`. I don't know what's setting those or anything, but that call checking `.equals` on null is what's throwing the exception.

**Comment by Lugghawk** [comment]
An update: I found that this appears to happen when calling `LocalNode` subsequent times with the same cluster name argument. Here's reproducing it in `sbt console`:

`scala> import com.sksamuel.elastic4s.embedded.LocalNode
import com.sksamuel.elastic4s.embedded.LocalNode

scala> var node = LocalNode("mycluster", "/tmp/foo/bar1")
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
node: com.sksamuel.elastic4s.embedded.InternalLocalNode = com.sksamuel.elastic4s.embedded.InternalLocalNode@7aad5734

scala> var node = LocalNode("mycluster", "/tmp/foo/bar2")
java.lang.NullPointerException
  at org.elasticsearch.cluster.node.DiscoveryNodes.isAllNodes(DiscoveryNodes.java:233)
  at org.elasticsearch.cluster.node.DiscoveryNodes.resolveNodes(DiscoveryNodes.java:304)
  at org.elasticsearch.action.support.nodes.TransportNodesAction.resolveRequest(TransportNodesAction.java:148)
  at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.<init>(TransportNodesAction.java:166)
  at org.elasticsearch.action.support.nodes.TransportNodesAction.doExecute(TransportNodesAction.java:89)
  at org.elasticsearch.action.support.nodes.TransportNodesAction.doExecute(TransportNodesAction.java:52)
  at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:167)
  at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:139)
  at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:81)
  at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83)
  at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72)
  at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:405)
  at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:394)
  at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:706)
  at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:46)
  at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:53)
  at com.sksamuel.elastic4s.embedded.InternalLocalNode.<init>(LocalNode.scala:76)
  at com.sksamuel.elastic4s.embedded.LocalNode$.apply(LocalNode.scala:175)
  at com.sksamuel.elastic4s.embedded.LocalNode$.apply(LocalNode.scala:181)
  at com.sksamuel.elastic4s.embedded.LocalNode$.apply(LocalNode.scala:199)
  ... 38 elided`

**Comment by wrwills** [comment]
+1

**Comment by AlgerLin** [comment]
I got the same problem, when initiate LocalNode with Elastic4S 6.3.7, please let me know, if you have any solution.

**Comment by sksamuel** [comment]
Local Node has been removed from elastic4s now. Recommended you use docker for a proper local instance.
