### ISSUE TITLE
ScriptedMetricAggregationDefinition not supported

### ISSUE THREAD

**Issue by therealnb** [sksamuel/elastic4s#1314]
Hello;
I'm trying to use `ScriptedMetricAggregationDefinition` with elastic4s-http 5.4.15. I get the following exception
```
scala.MatchError: ScriptedMetricAggregationDefinition(ids,Some(ScriptDefinition(params._agg.ids = [],Some(painless),inline,Map(),Map())),Some(ScriptDefinition(params._agg.ids.add(doc._uid.value),Some(painless),inline,Map(),Map())),Some(ScriptDefinition(,Some(painless),inline,Map(),Map())),Some(ScriptDefinition(def tot = new HashSet(); for (a in params._aggs) { tot.addAll(a.ids) } return tot,Some(painless),inline,Map(),Map())),Map(),List(),Map()) (of class com.sksamuel.elastic4s.searches.aggs.ScriptedMetricAggregationDefinition)
	at com.sksamuel.elastic4s.http.search.aggs.AggregationBuilderFn$.apply(AggregationBuilderFn.scala:30)
	at com.sksamuel.elastic4s.http.search.SearchBodyBuilderFn$.$anonfun$apply$63(SearchBodyBuilderFn.scala:204)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
```
which I think I understand as a missing case in `AggregationBuilderFn`.

I posted this question [https://stackoverflow.com/questions/49428759/tweaking-elastic4s-queries-before-they-are-sent](https://stackoverflow.com/questions/49428759/tweaking-elastic4s-queries-before-they-are-sent) to ask for a workaround.

The aim is to use this aggregation, which doesn't seem directly possible in this branch, but the question here is 'is there a way to add this manually' before query?

I have a bunch of other aggregations and parameters defined in the DSL, and it seems to me I have to throw all that out and do a raw query. I don't really want to do that. I would like to create the query using the DSL, then change a bit manually, then send.

**Comment by therealnb** [comment]
I got round this in my code by subclassing AggregationBuilderFn and providing ScriptedMetricAggregationBuilder. This is very hacky, so I am open to better suggestions.

For reference, if anyone else want to hack in the same way.

```
package com.sksamuel.elastic4s.http.search.aggs

import com.sksamuel.elastic4s.http.ScriptBuilderFn
import com.sksamuel.elastic4s.searches.aggs.ScriptedMetricAggregationDefinition
import org.elasticsearch.common.xcontent.{XContentBuilder, XContentFactory, XContentType}

/** This is a replacement of elastic4s to allow us to use ScriptedMetricAggregationDefinition.
  * It should probably be reviewed when we have a new version of elasticsearch. */
object ScriptedMetricAggregationBuilder {
  def apply(agg: ScriptedMetricAggregationDefinition): XContentBuilder = {
    val builder = XContentFactory.jsonBuilder()
    builder.startObject()
    builder.startObject("scripted_metric")
    if(agg.initScript.nonEmpty)
      builder.rawField("init_script", ScriptBuilderFn(agg.initScript.get).bytes(), XContentType.JSON)
    if(agg.mapScript.nonEmpty)
      builder.rawField("map_script", ScriptBuilderFn(agg.mapScript.get).bytes(), XContentType.JSON)
    if(agg.combineScript.nonEmpty)
      builder.rawField("combine_script", ScriptBuilderFn(agg.combineScript.get).bytes(), XContentType.JSON)
    if(agg.reduceScript.nonEmpty)
      builder.rawField("reduce_script", ScriptBuilderFn(agg.reduceScript.get).bytes, XContentType.JSON)
    if(agg.params.nonEmpty) {
      builder.startObject("params")
      agg.params.toSeq.foreach(p => builder.field(p._1, p._2))
      builder.field("_agg", Map.empty)
      builder.endObject()
    }
    builder.endObject()
    builder.endObject()
  }
}
```
and

```
package com.sksamuel.elastic4s.http.search.aggs

import com.sksamuel.elastic4s.searches.aggs._
import com.sksamuel.elastic4s.searches.aggs.pipeline.{CumulativeSumDefinition, MaxBucketDefinition}
import org.elasticsearch.common.xcontent.XContentBuilder

/** This is a replacement of elastic4s to allow us to use ScriptedMetricAggregationDefinition.
  * It should probably be reviewed when we have a new version of elasticsearch. */
object AggregationBuilderFn {
  def apply(agg: AbstractAggregation): XContentBuilder = {
    val builder = agg match {
      case agg: AvgAggregationDefinition => AvgAggregationBuilder(agg)
      case agg: CardinalityAggregationDefinition => CardinalityAggregationBuilder(agg)
      case agg: CumulativeSumDefinition => CumulativeSumAggregationBuilder(agg)
      case agg: DateHistogramAggregation => DateHistogramAggregationBuilder(agg)
      case agg: DateRangeAggregation => DateRangeAggregationBuilder(agg)
      case agg: FilterAggregationDefinition => FilterAggregationBuilder(agg)
      case agg: MaxAggregationDefinition => MaxAggregationBuilder(agg)
      case agg: MinAggregationDefinition => MinAggregationBuilder(agg)
      case agg: MissingAggregationDefinition => MissingAggregationBuilder(agg)
      case agg: NestedAggregationDefinition => NestedAggregationBuilder(agg)
      case agg: StatsAggregationDefinition => StatsAggregationBuilder(agg)
      case agg: SumAggregationDefinition => SumAggregationBuilder(agg)
      case agg: TopHitsAggregationDefinition => TopHitsAggregationBuilder(agg)
      case agg: TermsAggregationDefinition => TermsAggregationBuilder(agg)
      case agg: ValueCountAggregationDefinition => ValueCountAggregationBuilder(agg)
      case agg: SigTermsAggregationDefinition => SigTermsAggregationBuilder(agg)
      case agg: ScriptedMetricAggregationDefinition => ScriptedMetricAggregationBuilder(agg)

      case agg: RangeAggregationDefinition => RangeAggregationBuilder(agg)

      // pipeline aggs
      case agg: MaxBucketDefinition => MaxBucketPipelineAggBuilder(agg)
    }
    builder
  }
}
```
Now I can do something like this

```
val i = ScriptDefinition("params._agg.ids = []")
val ms = ScriptDefinition("if(doc._type.value == 'generic') params._agg.ids.add(doc._uid.value)")
val rs = ScriptDefinition("def tot = new HashSet(); for (a in params._aggs) { tot.addAll(a.ids) } return tot.hashCode()")
val hash = ScriptedMetricAggregationDefinition("alert_group").initScript(i).mapScript(ms).reduceScript(rs)

val res = Es.client.execute {
  search(Es.indices()).aggs(hash).size(0) query QueryStringQueryDefinition("somequery")
}.await(Config.timeout)
```

**Comment by therealnb** [comment]
I think the best approach for the library would be something like
      `case agg: RawAggregationDefinition => RawAggregationBuilder(agg)`
So it is possible to pass some ad hoc json in.

**Comment by sksamuel** [comment]
PR welcome.

**Comment by paulporu** [comment]
Hi,

In case you're still interested a pull request has been opened to add the feature to version 5.4.x: https://github.com/sksamuel/elastic4s/pull/1507.
