### ISSUE TITLE
NullPointerException sometimes during indexing of collection with null

### ISSUE THREAD

**Issue by provegard** [sksamuel/elastic4s#1374]
I'm trying to index an instance with a collection of nested instances. I'm seeing inconsistent behavior with respect to `null` values in the collection.

For example, indexing the following field map, where head is a Map is problematic:

    Map("Things" -> Seq(Map("Color" -> "red"), null)

It results in:

```
java.lang.NullPointerException: null
	at com.sksamuel.elastic4s.FieldsMapper$.mapFields(FieldsMapper.scala:31)
	at com.sksamuel.elastic4s.FieldsMapper$$anonfun$mapFields$1$$anonfun$3.apply(FieldsMapper.scala:50)
	at com.sksamuel.elastic4s.FieldsMapper$$anonfun$mapFields$1$$anonfun$3.apply(FieldsMapper.scala:50)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at com.sksamuel.elastic4s.FieldsMapper$$anonfun$mapFields$1.apply(FieldsMapper.scala:50)
	at com.sksamuel.elastic4s.FieldsMapper$$anonfun$mapFields$1.apply(FieldsMapper.scala:31)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Map$Map4.foreach(Map.scala:188)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.sksamuel.elastic4s.FieldsMapper$.mapFields(FieldsMapper.scala:31)
	at com.sksamuel.elastic4s.indexes.IndexDefinition.fields(IndexDefinition.scala:54)
```

Whereas indexing the following, where head is `null` works, sort of:

    Map("Things" -> Seq(null, Map("Color" -> "red")))

However, when I later search for Things.Color with value "red", I get no results.

If I leave out `null` entirely, indexing and searching works fine.

I'm well aware that using `null` is bad and I can work around it, but I thought that you perhaps may want to look into the inconsistent behavior.

**Comment by sksamuel** [comment]
Fixed in 6.3.0
