### ISSUE TITLE
Slice and scroll publisher generate an ElasticSearch parsin Exception

### ISSUE THREAD

**Issue by fooblahblah** [sksamuel/elastic4s#1400]
I'm using ElasticSearch `6.2` and elastic4s `6.2.9`. When issuing a query with the scroll publisher and slice I get an error:

```
    httpClient.publisher {
      search(MyIndex) query {
        termQuery(Fields.StateFacet, state)
      } sourceInclude(Fields.DetailsUrl) slice(sliceId, maxSlices) size(1000) scroll ("5m")
    }
```
results in
```
java.lang.RuntimeException: ElasticError(parsing_exception,[slice] failed to parse field [max],None,None,None,List(ElasticError(parsing_exception,[slice] failed to parse field [max],None,None,None,null)))
	at com.sksamuel.elastic4s.streams.PublishActor$$anonfun$com$sksamuel$elastic4s$streams$PublishActor$$fetching$1.applyOrElse(ScrollPublisher.scala:152)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at com.sksamuel.elastic4s.streams.PublishActor.aroundReceive(ScrollPublisher.scala:70)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
	at akka.actor.ActorCell.invoke(ActorCell.scala:559)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Any ideas?

**Comment by fooblahblah** [comment]
I updated from elastic4s `6.2.3` to `6.2.9` and got a new error which may be my issue:
```
java.lang.RuntimeException: ElasticError(parsing_exception,[slice] failed to parse field [max],None,None,None,List(ElasticError(parsing_exception,[slice] failed to parse field [max],None,None,None,null,None)),Some(CausedBy(illegal_argument_exception,max must be greater than 1,Map())))
	at com.sksamuel.elastic4s.streams.PublishActor$$anonfun$com$sksamuel$elastic4s$streams$PublishActor$$fetching$1.applyOrElse(ScrollPublisher.scala:152)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at com.sksamuel.elastic4s.streams.PublishActor.aroundReceive(ScrollPublisher.scala:70)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
	at akka.actor.ActorCell.invoke(ActorCell.scala:559)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
So it seems I should only use slices when I'm actually slicing. I'll close this issue since it seems to be my stupidity!
