### ISSUE TITLE
NullPointerException in GetImplicits$GetHttpExecutable

### ISSUE THREAD

**Issue by francisdb** [sksamuel/elastic4s#1423]
Not sure how we ended up there but wrapping the `node.get("error")` in an optional and folding might be a good idea

Elastic4s `6.2.2`

```
java.lang.NullPointerException: null
    at com.sksamuel.elastic4s.http.get.GetImplicits$GetHttpExecutable$$anon$2.bad$1(GetImplicits.scala:67)
    at com.sksamuel.elastic4s.http.get.GetImplicits$GetHttpExecutable$$anon$2.handle(GetImplicits.scala:81)
    at com.sksamuel.elastic4s.http.HttpClient.$anonfun$execute$1(HttpClient.scala:69)
    at scala.util.Success.$anonfun$map$1(Try.scala:251)
    at scala.util.Success.map(Try.scala:209)
    at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
    at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
    at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


```

**Comment by francisdb** [comment]
Hmm, looks like this code was already refactored, will upgrade and see if we still see this one

**Comment by brunoballekens** [comment]
Still have it during upgrade on elastic managed cloud using elastic4s 6.7.1
Will make a PR to fix this shortly

**Comment by brunoballekens** [comment]
Response body (status code 503) from elastic cloud was probably something like:
```
{"ok":false,"message":"Deployment is under maintenance / recovery."}
```

**Comment by francisdb** [comment]
Same NullPointerException at different location

```
java.lang.NullPointerException: null
    at com.sksamuel.elastic4s.http.get.GetHandlers$GetHandler$$anon$2.bad$1(GetHandlers.scala:48)
    at com.sksamuel.elastic4s.http.get.GetHandlers$GetHandler$$anon$2.handle(GetHandlers.scala:62)
    at com.sksamuel.elastic4s.http.ElasticClient.$anonfun$execute$1(ElasticClient.scala:33)
    at scala.util.Success.$anonfun$map$1(Try.scala:255)
    at scala.util.Success.map(Try.scala:213)
    at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
    at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
    at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
