### ISSUE TITLE
IndicesOptionsRequest in SearchRequest seems ignored

### ISSUE THREAD

**Issue by ali-h** [sksamuel/elastic4s#1469]
I'm trying to search a few indices without having an error returned in case one of the indices doesn't exist. I'm doing the following:
```scala
val mySearch = search(indices) indicesOptions IndicesOptionsRequest(ignoreUnavailable = true)
```
However, I'm still having errors for non-existent indices. Looking at [SearchBodyBuilderFn](https://github.com/sksamuel/elastic4s/blob/ac137de93cf301f517c39f913afcd28338ed5d5b/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/SearchBodyBuilderFn.scala) I don't see the field ```indicesOptions``` of the request being used anywhere. Is it not being taken into account for now ?

**Comment by ali-h** [comment]
For reference, here's the error I get:
```
java.util.NoSuchElementException: Request Failure ElasticError(index_not_found_exception,no such index,Some(_na_),Some(my-index),None,List(ElasticError(index_not_found_exception,no such index,Some(_na_),Some(my-index),None,null,None)),None)
  at com.sksamuel.elastic4s.http.RequestFailure.result(responses.scala:38) ~[elastic4s-http_2.12-6.3.3.jar:6.3.3]
  at com.sksamuel.elastic4s.http.RequestFailure.result(responses.scala:33) ~[elastic4s-http_2.12-6.3.3.jar:6.3.3]
  at world.jawair.server.topic.impl.TopicServiceImpl.$anonfun$getTopics$10(TopicServiceImpl.scala:294) ~[classes/:?]
  at scala.util.Success.$anonfun$map$1(Try.scala:251) ~[scala-library-2.12.6.jar:1.0.3]
at scala.util.Success.map(Try.scala:209) ~[scala-library-2.12.6.jar:1.0.3]
  at scala.concurrent.Future.$anonfun$map$1(Future.scala:288) ~[scala-library-2.12.6.jar:?]
  at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29) ~[scala-library-2.12.6.jar:?]
  at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29) ~[scala-library-2.12.6.jar:?]
  at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60) ~[scala-library-2.12.6.jar:?]
```

**Comment by sksamuel** [comment]
The ignore unavailable is set as a http parameter, so is part of the SearchHandler not the SearchBodyBuilderFn. I've added a test to confirm it's working and it is.
See https://github.com/sksamuel/elastic4s/blob/b12c9e4db695bd29cb21b9d6e48b7e628ce13941/elastic4s-tests/src/test/scala/com/sksamuel/elastic4s/search/SearchTest.scala#L206-L216
