### ISSUE TITLE
Illegal character error while using 'near' operator in search query (5.5.11)

### ISSUE THREAD

**Issue by SovietSir** [sksamuel/elastic4s#1535]
Hello,

Recently I have faced with such issue - when I try to perform simple search request with 'near' operator, I get following error:

> Exception in thread "main" org.elasticsearch.client.ResponseException: POST http://localhost:9200/index/type/_search: HTTP/1.1 500 Internal Server Error
{"error":{"root_cause":[{"type":"json_parse_exception","reason":"Illegal character ((CTRL-CHAR, code 0)): only regular white space (\\r, \\n, \\t) is allowed between tokens\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@1cc2525e; line: 1, column: 90]"}],"type":"json_parse_exception","reason":"Illegal character ((CTRL-CHAR, code 0)): only regular white space (\\r, \\n, \\t) is allowed between tokens\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@1cc2525e; line: 1, column: 90]"},"status":500}
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:354)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:343)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:748)

To reproduce this error in isolated workaround, I use such code snippet:

> 
    
    val http: HttpClient = HttpClient(ElasticsearchClientUri("localhost", 9200))
    
    val break: SpanTermQueryDefinition = SpanTermQueryDefinition("_all_custom", "break")
    val broke: SpanTermQueryDefinition = SpanTermQueryDefinition("_all_custom", "broke")
    val must: SpanNearQueryDefinition = SpanNearQueryDefinition(Seq(), 20).clauses(Seq(break, broke))
    val query: BoolQueryDefinition = BoolQueryDefinition().must(must) // query 'break NEAR broke'
    
    val request = ElasticDsl.search(IndexesAndTypes(Seq("index"), Seq("type"))).query(query)
    
    val response = http.execute(request).await

So far so good. Then I look in debugger and found, that request body looks like:

![screenshot_20181004_181606](https://user-images.githubusercontent.com/25549770/46484063-ac894580-c801-11e8-833a-08a8372cb911.png)

My suggestion is that builder of body insert redundant whitespaces, which are forbidden in ES requests.

Versions:
ES docker image: 5.5.3
Elastic4s: 5.5.11

I will be glad for any help from you!

Regards, 
Leonid

**Comment by unkarjedy** [comment]
Added PR: https://github.com/sksamuel/elastic4s/pull/1537

**Comment by unkarjedy** [comment]
@sksamuel Closing the bug due to my PR?
