### ISSUE TITLE
JsonMapperException when parsing incomplete error response 

### ISSUE THREAD

**Issue by butleradamj-deere** [sksamuel/elastic4s#1582]
We are occasionally seeing errors like these in our logs:  

```
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
at [Source: ; line: 1, column: 1]
at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3781)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3721)
at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2271)
at com.sksamuel.elastic4s.http.ElasticError$.parse(ElasticError.scala:34)
at com.sksamuel.elastic4s.http.DefaultResponseHandler.handle(ResponseHandler.scala:49)
at com.sksamuel.elastic4s.http.HttpClient$$anonfun$execute$1.apply(HttpClient.scala:69)
at com.sksamuel.elastic4s.http.HttpClient$$anonfun$execute$1.apply(HttpClient.scala:68)
at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
at scala.util.Try$.apply(Try.scala:192)
at scala.util.Success.map(Try.scala:237)
at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

This is being thrown here:  https://github.com/sksamuel/elastic4s/blob/master/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/ElasticError.scala#L37

The response body from ElasticSearch is either incomplete or misformed.  Logic should be added to handle this and still return a valid response to elastic4s clients.

**Comment by francisdb** [comment]
We are having the same issue. Some other calls return `ElasticError(504,504,None,None,None,List(),None)`, my guess is that this is the proxy at elastic.co just cuts the connection returning 504 without response body.

Can #1583 be updated/merged please?

old stack trace from 6.2.9
```
om.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
    at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
    at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4133)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3988)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3030)
    at com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper.readValue(ScalaObjectMapper.scala:190)
    at com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper.readValue$(ScalaObjectMapper.scala:189)
    at com.sksamuel.elastic4s.json.JacksonSupport$$anon$1.readValue(JacksonSupport.scala:11)
    at com.sksamuel.elastic4s.http.ResponseHandler$.fromEntity(ResponseHandler.scala:35)
    at com.sksamuel.elastic4s.http.ResponseHandler$.fromResponse(ResponseHandler.scala:30)
    at com.sksamuel.elastic4s.http.get.GetImplicits$GetHttpExecutable$$anon$2.bad$1(GetImplicits.scala:66)
    at com.sksamuel.elastic4s.http.get.GetImplicits$GetHttpExecutable$$anon$2.handle(GetImplicits.scala:81)
    at com.sksamuel.elastic4s.http.HttpClient.$anonfun$execute$1(HttpClient.scala:69)
```

**Comment by francisdb** [comment]
By the way, we have 27.000+ of these errors in our error tracker, if only we knew the status codes for all of these

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/161305/57128057-8aa17280-6d92-11e9-9590-ec77d4be763b.png">

**Comment by sksamuel** [comment]
Closing as this is part of the recent releases.

**Comment by brunoballekens** [comment]
Hmm, this only seems to be available on the 7.0 and 7.1 branches/releases.
Can this be backported to the 6.7 branch ?
Or can we use a 7.x elastic4s release with an Elasticsearch 6.7 ?

**Comment by sksamuel** [comment]
7.0 should work fine on 6.x

**Comment by brunoballekens** [comment]
Hmm, unfortunately we still need to support a customer with ES 5.6.
I guess I can use elastic4s 6.7.x for that ? 
If yes, would it be possible to merge this fix also to the 6.7 branch ?
Many thx!

**Comment by sksamuel** [comment]
There's so many versions to maintain that I let users make the PRs they
want from master back to a version they need, and then I release it for
them.

**Comment by brunoballekens** [comment]
I already wondered how you cope with all the maintenance :-)
I've created pull request https://github.com/sksamuel/elastic4s/pull/1784
