### ISSUE TITLE
NPE when reading stats aggregation result

### ISSUE THREAD

**Issue by maxcom** [sksamuel/elastic4s#1614]
Stats aggregation for empty selection fails with NullPointerException:

```
java.lang.NullPointerException: null
	at com.sksamuel.elastic4s.http.search.HasAggregations.statsBucket(aggresponses.scala:529) ~[elastic4s-http_2.12-6.5.0.jar:6.5.0]
	at com.sksamuel.elastic4s.http.search.HasAggregations.statsBucket$(aggresponses.scala:525) ~[elastic4s-http_2.12-6.5.0.jar:6.5.0]
	at com.sksamuel.elastic4s.http.search.Aggregations.statsBucket(aggresponses.scala:397) ~[elastic4s-http_2.12-6.5.0.jar:6.5.0]
	at ru.org.linux.user.UserStatisticsService.$anonfun$topicStats$3(UserStatisticsService.scala:119) ~[UserStatisticsService.class:?]
```

This happens because count is 0 and other fields is missing in result.

**Comment by sksamuel** [comment]
If you would care to raise a PR that would be great.
