### ISSUE TITLE
org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot determine write shards for [asc_local_2019-01-12_sat/searches]; likely its format is incorrect (maybe it contains illegal characters? or all shards failed?)

### ISSUE THREAD

**Issue by richa2810** [sksamuel/elastic4s#1669]
I face the below issue while trying to store the data into elastic search with spark.

org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot determine write shards for [asc_local_2019-01-12_sat/searches]; likely its format is incorrect (maybe it contains illegal characters? or all shards failed?)
        at org.elasticsearch.hadoop.util.Assert.isTrue(Assert.java:60)
        at org.elasticsearch.hadoop.rest.RestService.initSingleIndex(RestService.java:687)
        at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:632)
        at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:58)
        at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:107)
        at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:107)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:109)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

The issue is very random. It does not occur everytime and I also do not face it on my local machine.

**Comment by sksamuel** [comment]
Elastic4s is not involved here.
