### ISSUE TITLE
Setting searchType to DFS_QUERY_THEN_FETCH  for multisearch throws NPE

### ISSUE THREAD

**Issue by markovujo** [sksamuel/elastic4s#1691]
Version: 
```
<groupId>com.sksamuel.elastic4s</groupId>
<artifactId>elastic4s-http_2.11</artifactId>
<version>6.2.9</version>
```

Code (note the .searchType(SearchType.DFS_QUERY_THEN_FETCH)):
```
    val search1 = search(index)
      .query(query)
      .searchType(SearchType.DFS_QUERY_THEN_FETCH)
      .size(limit)
      .minScore(.99)
      .sortBy(ScoreSortDefinition(SortOrder.DESC), FieldSortDefinition("id"))
      .sourceInclude("ds","id")
```

Debugging show query:
`client.show(multi(Seq(search1))):`

Output:
```
client.show: {"index":"index1,index2","search_type":"DfsQueryThenFetch"}
{"version":true,"query":{"bool":{"must":[{"nested":{"path":"businessNames","query":{"multi_match":{"query":"Somename","fields":["name.name^1.0","name.name.ngram^1.0"],"slop":1}}}}],"size":100,"min_score":0.99,"sort":[{"_score":{"order":"desc"}},{"dataSourceId":{"order":"asc"}}],"_source":{"includes":["ds","id"]}}
```

The following NPE is thrown:

```
client.execute(multi(Seq(search1)))
java.lang.NullPointerException
	at com.sksamuel.elastic4s.http.search.SearchImplicits$MultiSearchHttpExecutable$$anon$2.handle(SearchImplicits.scala:44)
	at com.sksamuel.elastic4s.http.search.SearchImplicits$MultiSearchHttpExecutable$$anon$2.handle(SearchImplicits.scala:39)
	at com.sksamuel.elastic4s.http.HttpClient$$anonfun$execute$1.apply(HttpClient.scala:69)
	at com.sksamuel.elastic4s.http.HttpClient$$anonfun$execute$1.apply(HttpClient.scala:68)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by sksamuel** [comment]
The NPE is throw because there are no responses in the response. So I guess it's a more generic issue, and I've fixed it in master.
