### ISSUE TITLE
java.lang.NullPointerException from ElasticsearchJavaRestClient

### ISSUE THREAD

**Issue by KirilYurovnikRiski** [sksamuel/elastic4s#1900]
This could actually be an issue in `org.elasticsearch`, but I'm having a hard time understanding what causes this exactly.
I'm using `elastic4s` version `6.5.2`.

The application is a pretty simple data pipeline executing plain index/update queries, nothing too fancy. I'm sending several dozens of queries per second, in average.
The error occurs every once in a while and lasts for several minutes to hours, during which part of the queries fail with this exception.

The full stack trace:
```
java.lang.NullPointerException: null
Wrapped by: com.sksamuel.elastic4s.http.JavaClientExceptionWrapper: java.lang.NullPointerException
	at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient$$anon$1.onFailure(ElasticsearchJavaRestClient.scala:63)
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:850)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:558)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:531)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:834)
```

**Comment by KirilYurovnikRiski** [comment]
For some reason, it turns out that a small portion of the exceptions actually contain a more complete stack trace:
```
java.lang.NullPointerException: null
    at scala.io.Codec.decoder(Codec.scala:65)
    at scala.io.BufferedSource.reader(BufferedSource.scala:26)
    at scala.io.BufferedSource.bufferedReader(BufferedSource.scala:27)
    at scala.io.BufferedSource.charReader$lzycompute(BufferedSource.scala:37)
    at scala.io.BufferedSource.charReader(BufferedSource.scala:35)
    at scala.io.BufferedSource.scala$io$BufferedSource$$decachedReader(BufferedSource.scala:64)
    at scala.io.BufferedSource.mkString(BufferedSource.scala:93)
    at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient.$anonfun$fromResponse$1(ElasticsearchJavaRestClient.scala:44)
    at scala.Option.map(Option.scala:230)
    at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient.fromResponse(ElasticsearchJavaRestClient.scala:35)
    at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient$$anon$1.onFailure(ElasticsearchJavaRestClient.scala:62)
    at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:850)
    at org.elasticsearch.client.RestClient$1.retryIfPossible(RestClient.java:588)
    at org.elasticsearch.client.RestClient$1.completed(RestClient.java:550)
    ... 16 common frames omitted
    Suppressed: org.elasticsearch.client.ResponseException: method [PUT], host [http://es-host-url:9200], URI [/index_name/type_name/123], status line [HTTP/1.1 503 Service Unavailable]
no healthy upstream
        at org.elasticsearch.client.RestClient$1.completed(RestClient.java:546)
        ... 16 common frames omitted
Wrapped by: com.sksamuel.elastic4s.http.JavaClientExceptionWrapper: java.lang.NullPointerException
    at com.sksamuel.elastic4s.http.ElasticsearchJavaRestClient$$anon$1.onFailure(ElasticsearchJavaRestClient.scala:63)
    at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:850)
    ...
```

**Comment by therockstorm** [comment]
@KirilYurovnikRiski, did you find a solution to this? I'm seeing the same exception.

**Comment by KirilYurovnikRiski** [comment]
> @KirilYurovnikRiski, did you find a solution to this? I'm seeing the same exception.

In my case it was due to sporadic network issues, manifesting as `no healthy upstream` (503 Service Unavailable) responses from istio.
Didn't look into it much, but it would seem that something about those responses causes the Java REST client (`org.elasticsearch.client.RestClient`) to fail while decoding it.
Try to look for issues in your network infra.
