### ISSUE TITLE
Attempting to use elastic4s 7.3.5 with Elasticsearch client 7.6.1 throws method not found exception

### ISSUE THREAD

**Issue by philvarner** [sksamuel/elastic4s#2020]
using these versions together:

```
lazy val elastic4sVersion = "7.3.5"
lazy val elasticsearchRestClientVersion = "7.6.1"

lazy val elasticLibs = Seq(
  "com.sksamuel.elastic4s" %% "elastic4s-core" % elastic4sVersion,
  "com.sksamuel.elastic4s" %% "elastic4s-client-esjava" % elastic4sVersion,
  "org.elasticsearch.client" % "elasticsearch-rest-client" % elasticsearchRestClientVersion
)
```

results in:

```
java.lang.NoSuchMethodError: org.elasticsearch.client.RestClient.performRequestAsync(Lorg/elasticsearch/client/Request;Lorg/elasticsearch/client/ResponseListener;)V
	at com.sksamuel.elastic4s.http.JavaClient.send(JavaClient.scala:76)
	at com.sksamuel.elastic4s.Executor$$anon$1.exec(Executor.scala:22)
	at com.sksamuel.elastic4s.Executor$$anon$1.exec(Executor.scala:15)
	at com.sksamuel.elastic4s.ElasticClient.execute(ElasticClient.scala:34)
```

I _think_ this is due to the method now returning a value rather than void. Recompiling elastic4s with the newer client completes without any errors.

**Comment by sksamuel** [comment]
7.6.0 is now released.
