### ISSUE TITLE
GeoBoundingBoxQuery with geohash doesn't work

### ISSUE THREAD

**Issue by illfaku** [sksamuel/elastic4s#2044]
If you try to use GeoBoundingBoxQuery with geohash you'd get the following exception:
```
java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:327)
	at com.sksamuel.elastic4s.XContentBuilder.endObject(XContentBuilder.scala:336)
	at com.sksamuel.elastic4s.requests.searches.queries.geo.GeoBoundingBoxQueryBodyFn$.apply(GeoBoundingBoxQueryBodyFn.scala:35)
	at com.sksamuel.elastic4s.requests.searches.queries.QueryBuilderFn$.apply(QueryBuilderFn.scala:24)
	at com.sksamuel.elastic4s.requests.searches.queries.compound.BoolQueryBuilderFn$.$anonfun$apply$1(BoolQueryBuilderFn.scala:13)
	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:100)
	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:87)
	at scala.collection.immutable.Vector.map(Vector.scala:119)
	at com.sksamuel.elastic4s.requests.searches.queries.compound.BoolQueryBuilderFn$.apply(BoolQueryBuilderFn.scala:13)
	at com.sksamuel.elastic4s.requests.searches.queries.QueryBuilderFn$.apply(QueryBuilderFn.scala:16)
	at com.sksamuel.elastic4s.requests.searches.SearchBodyBuilderFn$.$anonfun$apply$7(SearchBodyBuilderFn.scala:21)
	at scala.Option.map(Option.scala:242)
	at com.sksamuel.elastic4s.requests.searches.SearchBodyBuilderFn$.apply(SearchBodyBuilderFn.scala:21)
	at com.sksamuel.elastic4s.requests.searches.SearchHandlers$SearchHandler$.$anonfun$build$23(SearchHandlers.scala:81)
	at scala.Option.getOrElse(Option.scala:201)
	at com.sksamuel.elastic4s.requests.searches.SearchHandlers$SearchHandler$.build(SearchHandlers.scala:81)
	at com.sksamuel.elastic4s.requests.searches.SearchHandlers$SearchHandler$.build(SearchHandlers.scala:51)
	at com.sksamuel.elastic4s.ElasticClient.execute(ElasticClient.scala:33)
```
Fix is simple. You just need to remove `builder.endObject()` line from code related to geohash in GeoBoundingBoxQueryBodyFn object.

**Comment by sksamuel** [comment]
PR welcome.

**Comment by illfaku** [comment]
> PR welcome.
Done: https://github.com/sksamuel/elastic4s/pull/2045

**Comment by sksamuel** [comment]
Released.
