### ISSUE TITLE
Could not initialize class org.elasticsearch.analysis.common.CommonAnalysisPlugin

### ISSUE THREAD

**Issue by gkurzawski** [sksamuel/elastic4s#2130]
I tried to update elastic4s to version 6.7.6, but I'm getting the following errors in the tests:
```
io.relayr.devicesearch.es.DevicesContextPaginationTest *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.analysis.common.CommonAnalysisPlugin
[info]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[info]   at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[info]   at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:609)
[info]   at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:119)
[info]   at org.elasticsearch.node.Node.<init>(Node.java:339)
[info]   at com.sksamuel.elastic4s.embedded.InternalLocalNode.<init>(LocalNode.scala:59)
[info]   at com.sksamuel.elastic4s.embedded.LocalNode$.apply(LocalNode.scala:163)
```

Part of my `build.sbt` file
```
val elastic4sVersion = "6.7.6"

// Elasticsearch
libraryDependencies ++= Seq(
  "com.sksamuel.elastic4s" %% "elastic4s-core" % elastic4sVersion,
  "com.sksamuel.elastic4s" %% "elastic4s-http" % elastic4sVersion,
  "com.sksamuel.elastic4s" %% "elastic4s-spray-json" % elastic4sVersion
)

// Testing
libraryDependencies ++= Seq(
  "com.sksamuel.elastic4s" %% "elastic4s-testkit" % elastic4sVersion % "test",
  "com.sksamuel.elastic4s" %% "elastic4s-embedded" % elastic4sVersion % "test",
  "org.apache.logging.log4j" % "log4j-core" % "2.9.1" % "test"
)
```

Did I miss anything? It works well with version 6.5.4 (the version I used before)

**Comment by sksamuel** [comment]
I would ditch the local node in tests and move to docker. ES dropped support for the local node and it was always a bit hacky to begin with.
