### ISSUE TITLE
IngestHandler has inconsistent version support for Pipeline API

### ISSUE THREAD

**Issue by roy-tc** [sksamuel/elastic4s#2275]
Hi,

For our project we'd like to configure our index with a `default_pipeline` that contains a [Date Processor](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/date-processor.html). We are using `elastic4s` for all our communication with Elasticsearch, so we wanted to use the `IngestApi` to do the following:

1. `getPipeline` to check if a pipeline already exists with the same id.
2. If it exists, verify that the definition matches with what we configured in our application
3. If it does not exist or if the definition did not match:
  1. `putPipeline` to upsert the pipeline definition
  2. Create a new index instance with this pipeline configured as `default_pipeline` and start reindexing data from the old index into the new index (so they will have an `@timestamp` field as expected).

The problem is the following:
- `GetPipelineResponse.version` is not optional. In other words, `IngestHandlers.responseHandler` [requires a version](https://github.com/sksamuel/elastic4s/blob/master/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/requests/ingest/IngestHandlers.scala#L22), while the parameter is optional according to the ES docs. 
- Moreover, `IngestApi.putPipeline` or `PutPipelineRequest` does not provide support for defining the pipeline `version` ([ES Docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/put-pipeline-api.html#versioning-pipelines)). So `PipelineApi.putPipeline` in fact not compatible with `PipelineApi.getPipeline`.

This results in the following exception:

```
java.util.NoSuchElementException: key not found: version
	at scala.collection.immutable.Map$Map2.apply(Map.scala:184)
	at com.sksamuel.elastic4s.requests.ingest.IngestHandlers$GetPipelineRequestHandler$$anon$1.$anonfun$handle$1(IngestHandlers.scala:22)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:154)
	at scala.collection.TraversableLike.map(TraversableLike.scala:273)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at com.sksamuel.elastic4s.requests.ingest.IngestHandlers$GetPipelineRequestHandler$$anon$1.handle(IngestHandlers.scala:18)
	at com.sksamuel.elastic4s.ElasticClient.$anonfun$execute$1(ElasticClient.scala:36)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	... 4 common frames omitted
```

I think the solution would simply be to make `version` optional. Thoughts?

I can create a PR for this, although I'd like this to be available for `7.6.x`, as any version above this involves breaking changes for our code base. Where should I branch off, and where should it be merged into?

On a side note; it would be very appreciated if breaking changes would be avoided in between minor versions. This would make it a lot easier to keep up to date on the latest ES releases.

Cheers!

**Comment by sksamuel** [comment]
If you make the pr against master and release/7.6.x that will work.

Thanks.

**Comment by roy-tc** [comment]
Thanks @sksamuel 
I created https://github.com/sksamuel/elastic4s/pull/2276, but couldn't find the `release7.6.x` branch.
Did I miss anything, or does it still need to be created? Please let me know, so we can apply this fix in our implementation.

Thanks again!

**Comment by roy-tc** [comment]
Hi @sksamuel 
Any input on this?
Releasing this fix would greatly help our product.

Thanks!

**Comment by sksamuel** [comment]
@roy-tc I have released 7.10.0 which contains your fix.
I also created the branch `release/7.6.x` and applied your patch there and released 7.6.2 as well.

**Comment by roy-tc** [comment]
@sksamuel awesome! Thanks for this.

We're upgrading our system right now.

**Comment by sksamuel** [comment]
You're welcome.
