### ISSUE TITLE
Index template creates MapperParsingException

### ISSUE THREAD

**Issue by MLnick** [sksamuel/elastic4s#249]
Creating an index template and then trying to index into a new index results in the following error:

```
Exception in thread "main" org.elasticsearch.transport.RemoteTransportException: [Vermin][inet[/127.0.0.1:9300]][indices:data/write/index]
Caused by: org.elasticsearch.index.mapper.MapperParsingException: mapping []
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:405)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:329)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:153)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Root type mapping not empty after parsing! Remaining fields:   [city : {dynamic=dynamic, _source={enabled=true}, numeric_detection=true, _ttl={enabled=false}, properties={location={type=geo_point}, year_founded={type=integer}}, _all={enabled=true}}]
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:276)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:190)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:444)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:317)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:402)
	... 5 more
```

Can re-create like:

```scala
object ESTest extends App {
  import com.sksamuel.elastic4s.ElasticDsl._
  import scala.concurrent.duration._
  val client = ElasticClient.remote("127.0.0.1", 9300)


  val f = client.execute {
      create template "some_template" pattern "*" mappings (
      "city" as (
        "year_founded" typed IntegerType,
        "location" typed GeoPointType
        )
      )
  }
  f.await(1 second)
  val r = client.execute {
    index into "test" -> "city" fields (
      "year_founded" -> 1829,
      "location" -> "33.9253, 18.4239"
      )
  }

  r.await(1 second)

}
```

The problem is that the template created looks like this:

```json
{
  "some_template" : {
    "order" : 0,
    "template" : "*",
    "settings" : { },
    "mappings" : {
      "" : {
        "city" : {
          "dynamic" : "dynamic",
          "_source" : {
            "enabled" : true
          },
          "numeric_detection" : true,
          "_ttl" : {
            "enabled" : false
          },
          "properties" : {
            "location" : {
              "type" : "geo_point"
            },
            "year_founded" : {
              "type" : "integer"
            }
          },
          "_all" : {
            "enabled" : true
          }
        }
      }
    },
    "aliases" : { }
  }
}
```

Under mappings the first element is a blank `""`. This derives from the following line: https://github.com/sksamuel/elastic4s/blob/b96f3aee5f91baecd745bc993a59f090a26895ce/src/main/scala/com/sksamuel/elastic4s/admin/IndexTemplateDsl.scala#L25

It seems like the call should be ``` _builder.addMapping(TYPE, mapping.build.SUB_MAPPING)```. I played around with it a bit but couldn't figure out how to achieve this (I'm not familiar with the XContent builder etc).

**Comment by sksamuel** [comment]
Seems that having ttl and numeric_detection in the templates breaks it, so I updated it to not include those (as well as the fix you suggested) and the test I wrote now passes.
https://github.com/sksamuel/elastic4s/blob/10ca56752ac17ccdf17b328384cc6c9e4418e1f7/src/test/scala/com/sksamuel/elastic4s/IndexTemplateTest.scala#L11

**Comment by sksamuel** [comment]
Actually still fails on travis but passes locally?! Can you checkout source and try sbt test for me?

**Comment by MLnick** [comment]
Thanks - I'm on vacation at the moment but will test in the next few days.

**Comment by MLnick** [comment]
seems consistent I've had no test passes yet after quite a few runs

**Comment by sksamuel** [comment]
windows or osx or linux

**Comment by sksamuel** [comment]
also what jdk version / vendor and what version of sbt. thanks.

**Comment by MLnick** [comment]
OSX

Java
```
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)
```

SBT 
```
> sbtVersion
[info] 0.13.5
```

**Comment by sksamuel** [comment]
Do Mac's use Oracle's JDK or some kind of open jdk?

**Comment by MLnick** [comment]
I'm using oracle jdk

—

**Comment by sksamuel** [comment]
So I've updated the test so that it now checks the template is applied
properly (before I was just checking that creating a template, then
creating an index didn't throw an exception). And while the template is
there, it doesn't seem to be getting applied.

**Comment by sksamuel** [comment]
Ok so now there's two tests. One that creates the template, and one that applies the template. Do you want to test this latest code locally?

**Comment by sksamuel** [comment]
Ok travis is happy now.

**Comment by MLnick** [comment]
`sbt test` passes for me now too. I will test it out on my local ES setup also.
Thanks!

**Comment by l15k4** [comment]
I have a similar issue, basically the template is created with some arbitrary mappings : 
```scala
    schema.resourceDocType as (
      "name"      typed StringType index NotAnalyzed,
      "host"      typed StringType index NotAnalyzed,
      "campaign"  typed StringType index NotAnalyzed,
      "created"   typed LongType
      ) numericDetection false // but I tried remove the numericDetection
```

on 2 identically set up machines that are not in cluster. The only difference is basically Oracle JDK vs OpenJDK ... And on that machine with OpenJDK if I just `index` into an index triggering that template like this : 
```scala
        index into(indexName / resourceDocType) fieldValues (
          SimpleFieldValue("name", fileName),
          SimpleFieldValue("host", host),
          SimpleFieldValue("campaign", campaign),
          SimpleFieldValue("created", date.getTime)
        )
```
or 
```scala
        index into(indexName / resourceDocType) fields Map[String, Any](
          "name" -> fileName,
          "host" -> host,
          "campaign" -> campaign,
          "created", date.getTime
        )
```

Than I get this [exception] (http://pastebin.com/raw.php?i=KCUxqz5C) ... Weird thing is that the template looks OK : 
```json
         "resource": {
            "_source": {
               "enabled": true
            },
            "dynamic": "dynamic",
            "_all": {
               "enabled": true
            },
            "properties": {
               "created": {
                  "type": "long"
               },
               "name": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "host": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "campaign": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "recIds": {
                  "type": "integer"
               }
            }
         }
```

Any idea if it is related to this issue? I spent 10 hours trying to figure out this problem.
