### ISSUE TITLE
Class com.sksamuel.elastic4s.http.JavaClient does not implement the requested interface com.sksamuel.exts.Logging

### ISSUE THREAD

**Issue by sentenza** [sksamuel/elastic4s#2598]
Trying to upgrade elastic4s to v7.16.1 in a Scala Play project I get the following error while testing.

The exception thrown at compile time during tests is an `IncompatibleClassChangeError`

```
java.lang.IncompatibleClassChangeError: Class com.sksamuel.elastic4s.http.JavaClient does not implement the requested interface com.sksamuel.exts.Logging
```

I'm testing using:

* Library v7.16.2
* JDK 11.0.13
* Scala 2.13.8
* sbt 1.6.1
* Scala Play v2.8.12

The `IncompatibleClassChangeError` exception  is thrown when an incompatible class change has occurred to some class definition. The definition of some class, on which the currently executing method depends, has since changed. It is normally thrown when a non-final field of a base class becomes static, or when the base class turns into an interface (and vice versa), etc.

```
[info]   at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:568)
[info]   at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:190)
[info]   at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
[info]   at com.google.inject.Guice.createInjector(Guice.java:87)
[info]   at com.google.inject.Guice.createInjector(Guice.java:78)
[info]   at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:200)
[info]   at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:155)
[info]   at helper.IntegrationHelperBase.app(IntegrationHelper.scala:1196)
[info]   at helper.IntegrationHelperBase.app$(IntegrationHelper.scala:1190)
[info]   at io.kode.controllers.api.GetContractTariffControllerSpec.app$lzycompute(GetContractTariffControllerSpec.scala:17)
[info]   ...
[info]   Cause: java.lang.IncompatibleClassChangeError: Class com.sksamuel.elastic4s.http.JavaClient does not implement the requested interface com.sksamuel.exts.Logging
[info]   at com.sksamuel.exts.Logging.$init$(Logging.scala:6)
[info]   at com.sksamuel.elastic4s.http.JavaClient.<init>(JavaClient.scala:24)
[info]   at com.sksamuel.elastic4s.http.JavaClient$.fromRestClient(JavaClient.scala:94)
[info]   at com.sksamuel.elastic4s.http.JavaClient$.apply(JavaClient.scala:135)
[info]   at com.sksamuel.elastic4s.http.JavaClient$.apply(JavaClient.scala:101)
[info]   at io.kode.daos.elasticsearch.ElasticUtil$.localElasticClient(ElasticUtil.scala:34)
[info]   at io.kode.daos.elasticsearch.TripEsDao.$anonfun$client$5(TripEsDao.scala:43)
[info]   at scala.Option.getOrElse(Option.scala:201)
[info]   at io.kode.daos.elasticsearch.TripEsDao.<init>(TripEsDao.scala:43)
[info]   at io.kode.daos.elasticsearch.TripEsDao$$FastClassByGuice$$12828785.GUICE$TRAMPOLINE(<generated>)
```

**Comment by sksamuel** [comment]
Can you try 7.16.2 once it pops into maven ?

**Comment by sentenza** [comment]
> Can you try 7.16.2 once it pops into maven ?

@sksamuel Same error 😢

**Comment by sentenza** [comment]
@sksamuel No error with v7.15.5. Do you have any idea why that happens?

**Comment by sentenza** [comment]
I found the root cause. It was given by a cross-dependency with a custom library that we need for AWS. I managed to fork it, upgrade it to v7.16.3 and now the error is gone!

It was still using v7.14.

**Comment by sksamuel** [comment]
Great catch, thanks.
