### ISSUE TITLE
Numeric lowFreqMinimumShouldMatch in commonQuery causes QueryPhaseExecutionException

### ISSUE THREAD

**Issue by maxcom** [sksamuel/elastic4s#277]
```scala
commonQuery("_all") query "some long query text" lowFreqMinimumShouldMatch 2
```

causes 

```
Caused by: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "2.0"
	at org.elasticsearch.search.internal.ContextIndexSearcher.createNormalizedWeight(ContextIndexSearcher.java:136)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:281)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:269)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:157)
	... 8 more
Caused by: java.lang.NumberFormatException: For input string: "2.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.elasticsearch.common.lucene.search.Queries.calculateMinShouldMatch(Queries.java:136)
	at org.apache.lucene.queries.ExtendedCommonTermsQuery.calcMinimumNumberShouldMatch(ExtendedCommonTermsQuery.java:58)
	at org.apache.lucene.queries.ExtendedCommonTermsQuery.calcLowFreqMinimumNumberShouldMatch(ExtendedCommonTermsQuery.java:51)
	at org.apache.lucene.queries.CommonTermsQuery.buildQuery(CommonTermsQuery.java:205)
	at org.apache.lucene.queries.CommonTermsQuery.rewrite(CommonTermsQuery.java:161)
	at org.apache.lucene.search.BooleanQuery.rewrite(BooleanQuery.java:554)
```

It seems that this parameter can only be whole number

**Comment by sksamuel** [comment]
Latest commits have a test that works for this

**Comment by sksamuel** [comment]
Try release 1.4.13

**Comment by maxcom** [comment]
It works fine, thanx!
