### ISSUE TITLE
Invalid create template request

### ISSUE THREAD

**Issue by l15k4** [sksamuel/elastic4s#294]
Hey,

I've been fighting a really ugly [issue](https://github.com/elastic/elasticsearch/issues/10299) for past days and it turns out that even though elastic4s create template request yields exactly the same `GET _template/name` output as java client template request, it is somehow corrupted leading to incorrect mapping during `Index creation` / `index request` time.

**Comment by l15k4** [comment]
I tried to disable `_dynamic` and `_source` but it didn't help

```scala  
def recordSchema =
    schema.recDocType as( // Note other fields are Strings, even 'mid' and 'max' have string values
      "gwid"      typed StringType index NotAnalyzed,
      "mid"       typed StringType index NotAnalyzed,
      "memberid"  typed StringType index NotAnalyzed,
      "respid"    typed StringType index NotAnalyzed,
      "token"     typed StringType index NotAnalyzed,
      "weighting" typed DoubleType,
      "timestamp" typed LongType
    ) numericDetection false

  def resourceSchema =
    schema.resourceDocType as (
      "name"      typed StringType index NotAnalyzed,
      "host"      typed StringType index NotAnalyzed,
      "campaign"  typed StringType index NotAnalyzed,
      "created"   typed LongType,
      "recIds"    typed IntegerType
    ) numericDetection false dynamic false source false

  def errorSchema =
    schema.errorDocType as (
      "fileName" typed StringType index NotAnalyzed,
      "headerRow" typed StringType index NotAnalyzed,
      "dataRow" typed StringType index NotAnalyzed,
      "headerFields" typed StringType index NotAnalyzed,
      "dataFields" typed StringType index NotAnalyzed
    )

create template template.templateName pattern template.templatePattern mappings (errorSchema, resourceSchema, recordSchema)
```

```json
   "template_mi": {
      "order": 0,
      "template": "mi_*",
      "settings": {},
      "mappings": {
         "error": {
            "dynamic": "dynamic",
            "_source": {
               "enabled": true
            },
            "properties": {
               "dataFields": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "dataRow": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "headerRow": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "fileName": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "headerFields": {
                  "index": "not_analyzed",
                  "type": "string"
               }
            },
            "_all": {
               "enabled": true
            }
         },
         "resource": {
            "dynamic": "false",
            "_source": {
               "enabled": false
            },
            "properties": {
               "host": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "recIds": {
                  "type": "integer"
               },
               "created": {
                  "type": "long"
               },
               "name": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "campaign": {
                  "index": "not_analyzed",
                  "type": "string"
               }
            },
            "_all": {
               "enabled": true
            }
         },
         "record": {
            "dynamic": "dynamic",
            "_source": {
               "enabled": true
            },
            "properties": {
               "timestamp": {
                  "type": "long"
               },
               "memberid": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "token": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "respid": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "weighting": {
                  "type": "double"
               },
               "mid": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "gwid": {
                  "index": "not_analyzed",
                  "type": "string"
               }
            },
            "_all": {
               "enabled": true
            }
         }
      }
```

The java version https://github.com/elastic/elasticsearch/issues/10299#issuecomment-88003956

works, it results to :
```json
"template_mi": {
      "order": 0,
      "template": "mi_*",
      "settings": {},
      "mappings": {
         "error": {
            "properties": {
               "dataFields": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "dataRow": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "headerRow": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "fileName": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "headerFields": {
                  "index": "not_analyzed",
                  "type": "string"
               }
            }
         },
         "resource": {
            "numeric_detection": false,
            "properties": {
               "host": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "recIds": {
                  "type": "integer"
               },
               "created": {
                  "type": "long"
               },
               "name": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "campaign": {
                  "index": "not_analyzed",
                  "type": "string"
               }
            }
         },
         "record": {
            "numeric_detection": false,
            "properties": {
               "timestamp": {
                  "type": "long"
               },
               "memberid": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "token": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "respid": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "weighting": {
                  "type": "double"
               },
               "mid": {
                  "index": "not_analyzed",
                  "type": "string"
               },
               "gwid": {
                  "index": "not_analyzed",
                  "type": "string"
               }
            }
         }
      }
```

**Comment by l15k4** [comment]
Hi, is this issue legitimate or am I doing something wrong? I'm new to ES, so I don't see in the internals much, anyway it is kinda hard to resolve it so if anybody else hit it he'll probably spent huge amount of time with it... Would you please take a look?

**Comment by l15k4** [comment]
One obvious problem might be that following piece of dsl : 
```scala
    schema.recDocType as(have string values
      "gwid"      typed StringType index NotAnalyzed,
      "mid"       typed StringType index NotAnalyzed,
      "memberid"  typed StringType index NotAnalyzed,
      "respid"    typed StringType index NotAnalyzed,
      "token"     typed StringType index NotAnalyzed,
      "weighting" typed DoubleType,
      "timestamp" typed LongType
    ) numericDetection false
```

doesn't generate `numericDetection` and it generates `dynamic` value as `String` instead of `Boolean` : 

```json
      "mappings": {
         "record": {
            "dynamic": "true",
            "_all": {
               "enabled": true
            },
            "_ttl": {
               "enabled": false
            },
            "properties": {
               "gwid": {
                  "type": "string",
                  "index": "not_analyzed"
               },
               "memberid": {
                  "type": "string",
                  "index": "not_analyzed"
               },
               "mid": {
                  "type": "string",
                  "index": "not_analyzed"
               },
               "respid": {
                  "type": "string",
                  "index": "not_analyzed"
               },
               "timestamp": {
                  "type": "long"
               },
               "token": {
                  "type": "string",
                  "index": "not_analyzed"
               },
               "weighting": {
                  "type": "double"
               }
            }
         }
      }
   }
```

**Comment by sksamuel** [comment]
I don't really follow your example, it is quite big. Do you have a simple one I can use as a unit test?

**Comment by MLnick** [comment]
@sksamuel actually I have been bitten by something that might be similar. The current test that you have first creates the template, then creates the index, then indexes. That should work fine and it does for me.

However if you create the template, then index data (i.e. auto-create the index) it fails with a root mapping empty exception.

If you put the template via elastic4s, get it via curl and put it again via curl, then dynamic indexing works!

**Comment by sksamuel** [comment]
Oh I see. That's interesting. I'll add a test for that (might even be a bug
in ES?)

**Comment by l15k4** [comment]
Hi, indeed it is quite strange issue, as you can see from the original [issue](https://github.com/elastic/elasticsearch/issues/10299) i'm kind of sure that it only occurs if the template is created by elastic4s, no matter how the following indexing requests (matching that template) are made (json, java-client, elastic4s)... I didn't manage to compose elastic4s `create template` request that would correspond to the java-client one, but I believe that if I could it would work... I still have a code base full of Java-client code because of this issue .... I'm gravely busy these 2 weeks so I can't dig deeper in this any more, sorry

**Comment by sksamuel** [comment]
Interesting issue. I'll take a look but I'm away in America for week for a
week so I can't look until late April, but I'm sure I can get to the bottom
of it.

**Comment by sksamuel** [comment]
@l15k4 do you have more details on your actual error. You just say that its
corrupted but no more details than that.

**Comment by l15k4** [comment]
Hi, sorry github stopped notifying me. This is the [server error](http://pastebin.com/raw.php?i=KCUxqz5C) in time of dynamic indexing using the template created by elastic4s.... If I create it using java-client [like this](https://github.com/elastic/elasticsearch/issues/10299#issuecomment-88003956), the indexing requests work fine...Although there are slight differences in the template as I mentioned above : 

https://github.com/sksamuel/elastic4s/issues/294#issuecomment-88017338

**Comment by MLnick** [comment]
@l15k4 @sksamuel I can confirm I see the same error `Root type mapping not empty after parsing!` with dynamic index creation, which is not the case with submitting a create index request followed by indexing into that index.

**Comment by sksamuel** [comment]
You guys on 1.5.4 as I fixed a relevant bug recently

**Comment by MLnick** [comment]
On 1.5.4, the following:

```
object ESTest extends App {
  val client = ElasticClient.remote("127.0.0.1", 9300)

  client.execute {
    create template "test" pattern "test*" mappings (
      "user" as (
        "name" withType StringType
        )
      )
  }.await

  //client.execute { create index "test" }

  client.execute {
    index into "test" / "user" fields (
      "name" -> 1829
      )
  }.await

}
```

Gives:
```
Exception in thread "main" org.elasticsearch.transport.RemoteTransportException: [Cannonball][inet[/127.0.0.1:9300]][indices:data/write/index]
Caused by: org.elasticsearch.index.mapper.MapperParsingException: mapping [user]
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:401)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:365)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Root type mapping not empty after parsing! Remaining fields:   [user : {properties={}}]
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:278)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:192)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:434)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:307)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:398)
	... 6 more
```

While removing the comment and creating the index first works.

```
curl 'localhost:9200/test/user/_mapping?pretty'
{
  "test" : {
    "mappings" : {
      "user" : {
        "dynamic" : "true",
        "properties" : {
          "name" : {
            "type" : "string"
          }
        }
      }
    }
  }
}

curl 'localhost:9200/test/user/_search?q=*&pretty'
{
  "took" : 62,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test",
      "_type" : "user",
      "_id" : "AUy9Z-agv0qG-A9ldkYb",
      "_score" : 1.0,
      "_source":{"name":1829}
    } ]
  }
}
```

**Comment by l15k4** [comment]
I'm on 1.5.1 and I am creating template `test*`, then creating index `test`, await and then I send index request to both, so according to what you say it shouldn't occur. I'll try it out with 1.5.4

**Comment by l15k4** [comment]
@MLnick @sksamuel  I just found out that it happens only in this case : 

1) create template `test_*` and index `test`  + await
2) `index into(test_foo / "resource")` and concurrently `index into(test_foo / "record")

Neither of those request succeed (nothing is indexed) and the error occurs. But if I do this : 

1) create template `test_*` and index `test`  + await
2) `index into(test / "resource")` and concurrently `index into(test_foo / "record")

It works ...

**Comment by sksamuel** [comment]
What's the error output in the error case ?

**Comment by l15k4** [comment]
```org.elasticsearch.transport.RemoteTransportException: [Starlight][inet[/127.0.0.1:9300]][indices:data/write/index]
Caused by: org.elasticsearch.index.mapper.MapperParsingException: mapping [resource]
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:401) ~[gwiq.jar:0.1-SNAPSHOT]
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:365) ~[gwiq.jar:0.1-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188) ~[gwiq.jar:0.1-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158) ~[gwiq.jar:0.1-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.8.0_31]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.8.0_31]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_31]
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Root type mapping not empty after parsing! Remaining fields:   [resource : {properties={}}]
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:278) ~[gwiq.jar:0.1-SNAPSHOT]
        at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:192) ~[gwiq.jar:0.1-SNAPSHOT]
        at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:434) ~[gwiq.jar:0.1-SNAPSHOT]
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:307) ~[gwiq.jar:0.1-SNAPSHOT]
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:398) ~[gwiq.jar:0.1-SNAPSHOT]
        ... 6 common frames omitted
```

**Comment by sksamuel** [comment]
Deffo 1.5.4?

**Comment by l15k4** [comment]
Yes, 1.5.4 deffo

**Comment by sksamuel** [comment]
Ok cos i fixed an error when creating indexes with no properties set.
Thought it might be that. Maybe I didn't release that yet actually.

**Comment by l15k4** [comment]
You know what is strange? That if you create mapping exactly the same for index and template, then it yields to 2 different results: 
```scala
"resource" as (
      "name"      typed StringType index NotAnalyzed
    ) numericDetection false source true
```

template: 
```json
         "resource": {
            "dynamic": "dynamic",
            "_source": {
               "enabled": true
            },
            "numeric_detection": false,
            "properties": {
               "name": {
                  "index": "not_analyzed",
                  "type": "string"
               }
            }
         }
```

index: 
```json
         "resource": {
            "dynamic": "true",
            "properties": {
               "name": {
                  "type": "string",
                  "index": "not_analyzed"
               }
            }
         }
```

**Comment by sksamuel** [comment]
@MLnick so I added that test you pasted and it worked fine for me, and also on Travis. I've got back about 50 commits and it still works so wasn't fixed recently. (This is testing on an embedded client though, I'll try a remote client next).

**Comment by sksamuel** [comment]
Works against a remote server too. Running latest ES version.

**Comment by sksamuel** [comment]
Ok I can recreate error now.

**Comment by sksamuel** [comment]
Maybe I closed this too soon. Passes locally for me (on windows) but fails on travis. Anyone else want to try master?

**Comment by fehmicansaglam** [comment]
It also passes for me on OS X.

**Comment by l15k4** [comment]
This nondeterministic behavior might suggest that it concerns the concurrency issues I wrote about, which would mean it is an ES bug. Because when I first hit this issue it was happening only on ec2 instances in docker container but I couldn't reproduce it locally on my linux machine... This is why I couldn't make a test case and I spent like 2 days of chasing this weirdest issue I've ever seen.

I'll test if it works next week

**Comment by sksamuel** [comment]
I don't think its non-deterministic in that it works sometimes and not
others on the same machine, but it might be something environmental based.
It passes for me every single time on windows (tried it 20 times), and
never passes on travis.

**Comment by l15k4** [comment]
I checked both oracleJDK and openJDK and it seemed to be unrelated to it... And I had identical docker setup for my laptop and the ec2 instance ... 

I traced the problem from the start to the end here : 
https://cloud.githubusercontent.com/assets/518855/6908594/722d48a8-d73e-11e4-9780-0e3ec19509b9.png
https://cloud.githubusercontent.com/assets/518855/6914545/084fd876-d78c-11e4-8acc-127d867e516b.png

There is index creation and consequent indexing request with empty resource properties, but I didn't find the exact origin of it...

**Comment by sksamuel** [comment]
Have you tried latest master Jakub?

**Comment by sksamuel** [comment]
Travis is reporting this fixed now as well. I'm closing this. Will be released as part of 1.5.5

Thanks to @l15k4  and @MLnick for your hard work tracking this down.

**Comment by MLnick** [comment]
I can confirm 1.5.5 fixes this for me. thanks!

**Comment by sksamuel** [comment]
Great!
