### ISSUE TITLE
None of the configured nodes are available: [] when shutting down client

### ISSUE THREAD

**Issue by apanimesh061** [sksamuel/elastic4s#314]
I know this issue has come up a lot many times but I still am not able to solve this.
I want to connect with ES server that already running on my localhost.
```
[2015-06-02 09:16:19,552][INFO ][node                     ] [Heinrich Zemo] version[1.4.2], pid[25625], build[927caff/2014-12-16T14:11:12Z]
[2015-06-02 09:16:19,553][INFO ][node                     ] [Heinrich Zemo] initializing ...
[2015-06-02 09:16:19,563][INFO ][plugins                  ] [Heinrich Zemo] loaded [marvel], sites [marvel]
[2015-06-02 09:16:22,686][INFO ][node                     ] [Heinrich Zemo] initialized
[2015-06-02 09:16:22,686][INFO ][node                     ] [Heinrich Zemo] starting ...
[2015-06-02 09:16:22,807][INFO ][transport                ] [Heinrich Zemo] bound_address {inet[/0.0.0.0:9300]}, publish_address {inet[/10.0.2.15:9300]}
[2015-06-02 09:16:22,828][INFO ][discovery                ] [Heinrich Zemo] elasticsearch/V7utDLHRS0i02opM2Ks3Ng
[2015-06-02 09:16:26,604][INFO ][cluster.service          ] [Heinrich Zemo] new_master [Heinrich Zemo][V7utDLHRS0i02opM2Ks3Ng][quickstart.cloudera][inet[/10.0.2.15:9300]], reason: zen-disco-join (elected_as_master)
[2015-06-02 09:16:26,685][INFO ][http                     ] [Heinrich Zemo] bound_address {inet[/0.0.0.0:9200]}, publish_address {inet[/10.0.2.15:9200]}
[2015-06-02 09:16:26,685][INFO ][node                     ] [Heinrich Zemo] started
[2015-06-02 09:16:27,642][INFO ][gateway                  ] [Heinrich Zemo] recovered [10] indices into cluster_state
```
where `10.0.2.15:9200` gives me :
```json
{
  "status" : 200,
  "name" : "Heinrich Zemo",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.4.2",
    "build_hash" : "927caff6f05403e936c20bf4529f144f0c89fd8c",
    "build_timestamp" : "2014-12-16T14:11:12Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.2"
  },
  "tagline" : "You Know, for Search"
}

```
and I used this code to interact with it:
```scala
object Main extends App {
  val uri = ElasticsearchClientUri("elasticsearch://10.0.2.15:9300")
  val settings = ImmutableSettings.settingsBuilder().put("cluster.name", "elasticsearch").build()
  val client = ElasticClient.remote(settings, uri)
  client.execute(create index "bands").await
  println(client.exists("bands").await.isExists())
  client.close()
  client.shutdown
}
```
ES version: 1.4.2
elastic4s version: 1.4.13
That JARs that I included in my scala project are the ones that are in the `lib` folder of elasticsearch.

When I run the code I get this error:
```
true
Exception in thread "main" org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:278)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:197)
	at org.elasticsearch.client.transport.support.InternalTransportClusterAdminClient.execute(InternalTransportClusterAdminClient.java:86)
	at org.elasticsearch.client.support.AbstractClusterAdminClient.nodesShutdown(AbstractClusterAdminClient.java:262)
	at org.elasticsearch.action.admin.cluster.node.shutdown.NodesShutdownRequestBuilder.doExecute(NodesShutdownRequestBuilder.java:70)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
	at com.sksamuel.elastic4s.ElasticClient$$anonfun$shutdown$1.apply(ElasticClient.scala:32)
	at com.sksamuel.elastic4s.ElasticClient$$anonfun$shutdown$1.apply(ElasticClient.scala:32)
	at com.sksamuel.elastic4s.ElasticClient.injectFuture(ElasticClient.scala:103)
	at com.sksamuel.elastic4s.ElasticClient.shutdown(ElasticClient.scala:32)
	at com.sksamuel.elastic4s.ElasticClient.shutdown(ElasticClient.scala:29)
	at helpers.Main4$delayedInit$body.apply(testAkka.scala:37)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at helpers.Main4$.main(testAkka.scala:25)
	at helpers.Main4.main(testAkka.scala)
```
I see that the index is created and I can also view it in `Sense` but why then during the shutdown it throws that error?

**Comment by sksamuel** [comment]
You can try connecting on localhost:9300 if you're running it locally?

**Comment by apanimesh061** [comment]
I changed the IP to `localhost` and again ran it. It still gave the same error when it was shutting down.

**Comment by sksamuel** [comment]
@apanimesh061 did you sort this ?

**Comment by apanimesh061** [comment]
Oh sorry. Forgot to update on this. 

The thing was that if I run a server externally and try to shut it down from my program it causes error which seems right cause I don't want external program to actually shutdown the server. The right thing was to only close the connection. If I use `local` connection without starting ES externally then `close` and `shutdown` work as intended.

**Comment by hhimanshu** [comment]
I see this even with connecting https://github.com/sksamuel/elastic4s/issues/416

**Comment by sksamuel** [comment]
See reply to 416 :)

**Comment by tanmoy-tech** [comment]
Hi,

Using TCPClinet for connection in elastic search like below

val settings = Settings.builder().put("cluster.name", "elasticsearch").build()
  implicit val client = TcpClient.transport(settings, ElasticsearchClientUri("elasticsearch://127.0.0.1:9200"))

But getting below exception while run my program:

Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{sslzRanpR8inOkA3qe-Ryw}{127.0.0.1}{127.0.0.1:9200}]]

Any help would be appriciated
