### ISSUE TITLE
Scripted update wont work if a scala.collection.immutable.list is passed as param

### ISSUE THREAD

**Issue by andrestc** [sksamuel/elastic4s#378]
For example, the following code:

```scala
client.execute {
      update id document.id in indexName -> documentType script {
        "ctx._source.synonyms += synonyms"
      } params Map("synonyms" -> document.synonyms) upsert {
        Map("word" -> document.word, "synonyms" -> document.synonyms)
      }
}
```

Where "synonyms" is a List[String],  is generating the following exception:

```
[info] org.elasticsearch.transport.SendRequestTransportException: [Protector][inet[/192.168.0.9:9300]][indices:data/write/update]
[info] 	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:286)
[info] 	at org.elasticsearch.action.TransportActionNodeProxy.execute(TransportActionNodeProxy.java:57)
[info] 	at org.elasticsearch.client.transport.support.InternalTransportClient$1.doWithNode(InternalTransportClient.java:109)
[info] 	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:205)
[info] 	at org.elasticsearch.client.transport.support.InternalTransportClient.execute(InternalTransportClient.java:106)
[info] 	at org.elasticsearch.client.support.AbstractClient.update(AbstractClient.java:127)
[info] 	at org.elasticsearch.client.transport.TransportClient.update(TransportClient.java:350)
[info] 	at com.sksamuel.elastic4s.UpdateDsl$UpdateDefinitionExecutable$$anonfun$apply$1.apply(UpdateDsl.scala:21)
[info] 	at com.sksamuel.elastic4s.UpdateDsl$UpdateDefinitionExecutable$$anonfun$apply$1.apply(UpdateDsl.scala:21)
[info] 	at com.sksamuel.elastic4s.Executable$class.injectFuture(Executable.scala:21)
[info] 	at com.sksamuel.elastic4s.UpdateDsl$UpdateDefinitionExecutable$.injectFuture(UpdateDsl.scala:19)
[info] 	at com.sksamuel.elastic4s.UpdateDsl$UpdateDefinitionExecutable$.apply(UpdateDsl.scala:21)
[info] 	at com.sksamuel.elastic4s.UpdateDsl$UpdateDefinitionExecutable$.apply(UpdateDsl.scala:19)
[info] 	at com.sksamuel.elastic4s.ElasticClient.execute(ElasticClient.scala:28)
[info] 	at com.hu.server.config.DatabaseConfig$$anon$1.com$hu$core$elasticsearch$ElasticSearchQueryLogger$$super$execute(DatabaseConfig.scala:39)
[info] 	at com.hu.core.elasticsearch.ElasticSearchQueryLogger$class.execute(ElasticSearchQueryLogger.scala:22)
[info] 	at com.hu.server.config.DatabaseConfig$$anon$1.execute(DatabaseConfig.scala:39)
[info] 	at com.hu.core.synonyms.SynonymsIndexer.updateIndexFromRequest(SynonymsIndexer.scala:39)
[info] 	at com.hu.core.index.RequestIndexerHandler$$anonfun$apply$1.apply(RequestIndexerHandler.scala:37)
[info] 	at com.hu.core.index.RequestIndexerHandler$$anonfun$apply$1.apply(RequestIndexerHandler.scala:37)
[info] 	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
[info] 	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
[info] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
[info] 	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
[info] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] Caused by: java.io.IOException: Can't write type [class scala.collection.immutable.$colon$colon]
[info] 	at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:415)
[info] 	at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:382)
[info] 	at org.elasticsearch.common.io.stream.StreamOutput.writeMap(StreamOutput.java:327)
[info] 	at org.elasticsearch.action.update.UpdateRequest.writeTo(UpdateRequest.java:715)
[info] 	at org.elasticsearch.transport.netty.NettyTransport.sendRequest(NettyTransport.java:701)
[info] 	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:276)
[info] 	... 27 more
```

I fixed it by using the JavaCoverters, sending the list with "asJava", like this:

```scala
client.execute {
      update id document.id in indexName -> documentType script {
        "ctx._source.synonyms += synonyms"
      } params Map("synonyms" -> document.synonyms.asJava) upsert {
        Map("word" -> document.word, "synonyms" -> document.synonyms)
      }
    }
```

Are we interested in doing such conversions inside elastic4s? Any tips on how to tackle this problem so i can submit a PR?

Thanks.

**Comment by sksamuel** [comment]
We would have to recurse the map, looking for scala collections (instance of seq / set) and converting them to Arrays. I think that would be enough?

**Comment by andrestc** [comment]
Yea, I think so. Was wondering if there was other edge cases to handle. I'll try submiting a PR tomorrow.
