### ISSUE TITLE
Can't insert document NoNodeAvailableException: None of the configured nodes are available: []

### ISSUE THREAD

**Issue by hhimanshu** [sksamuel/elastic4s#416]
@sksamuel 
I am using latest `Elastic4S` and this is what my code looks like  

```
object Elastic {
  println("Creating Elastic Connection")
  val client = ElasticClient.remote(host = "192.168.99.100", port = 9200)

  def insert(monitorJson: String) = {
    client execute {
      index into "test" -> "elastic4s" doc StringDocumentSource(monitorJson)
    }
  }
}
```
When I run my code I see,

```
inserting {time: Fri Aug 28 10:27:27 PDT 2015}
Creating Elastic Connection
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:305)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:200)
	at org.elasticsearch.client.transport.support.InternalTransportClient.execute(InternalTransportClient.java:106)
	at org.elasticsearch.client.support.AbstractClient.index(AbstractClient.java:102)
	at org.elasticsearch.client.transport.TransportClient.index(TransportClient.java:340)
	at com.sksamuel.elastic4s.IndexDsl$IndexDefinitionExecutable$$anonfun$apply$1.apply(IndexDsl.scala:23)
	at com.sksamuel.elastic4s.IndexDsl$IndexDefinitionExecutable$$anonfun$apply$1.apply(IndexDsl.scala:23)
	at com.sksamuel.elastic4s.Executable$class.injectFuture(Executable.scala:21)
	at com.sksamuel.elastic4s.IndexDsl$IndexDefinitionExecutable$.injectFuture(IndexDsl.scala:20)
	at com.sksamuel.elastic4s.IndexDsl$IndexDefinitionExecutable$.apply(IndexDsl.scala:23)
	at com.sksamuel.elastic4s.IndexDsl$IndexDefinitionExecutable$.apply(IndexDsl.scala:20)
	at com.sksamuel.elastic4s.ElasticClient.execute(ElasticClient.scala:28)
	at com.enterpriseconnector.persistence.Elastic$.insert(Elastic.scala:14)
	at com.enterpriseconnector.persistence.Test$$anonfun$1.apply(Elastic.scala:24)
	at com.enterpriseconnector.persistence.Test$$anonfun$1.apply(Elastic.scala:21)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Range.foreach(Range.scala:166)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.enterpriseconnector.persistence.Test$.delayedEndpoint$com$enterpriseconnector$persistence$Test$1(Elastic.scala:21)
	at com.enterpriseconnector.persistence.Test$delayedInit$body.apply(Elastic.scala:20)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.enterpriseconnector.persistence.Test$.main(Elastic.scala:20)
	at com.enterpriseconnector.persistence.Test.main(Elastic.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

and I see that my `ElasticSearch` is up and running

```
$ curl http://192.168.99.100:9200/?pretty
{
  "status" : 200,
  "name" : "Collector",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.4.4",
    "build_hash" : "c88f77ffc81301dfa9dfd81ca2232f09588bd512",
    "build_timestamp" : "2015-02-19T13:05:36Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.3"
  },
  "tagline" : "You Know, for Search"
}
```

What am I missing?

**Comment by sksamuel** [comment]
You want 9300 for TCP. 9200 is for rest.

**Comment by hhimanshu** [comment]
Yes, that fixed it. Thank you @sksamuel

**Comment by tanmoy-tech** [comment]
Using TCPClinet for connection in elastic search like below

val settings = Settings.builder().put("cluster.name", "elasticsearch").build()
implicit val client = TcpClient.transport(settings, ElasticsearchClientUri("elasticsearch://127.0.0.1:9200"))

implicit val ec = ExecutionContext.global

val futureArtist = for {
_ <- createElasticIndex
_ <- insertDocument
resp <- queryDocument
} yield resp.to[Artist]
val artistList = Await.result(futureArtist, Duration.Inf)
artistList.foreach(println)
client.close()

But getting below exception while run my program:

Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{sslzRanpR8inOkA3qe-Ryw}{127.0.0.1}{127.0.0.1:9200}]]

Any help would be appriciated

**Comment by sksamuel** [comment]
The TCP client is no longer supported. I'd recommend you move to the http
client.

**Comment by tanmoy-tech** [comment]
@sksamuel :Thanks for quick response
