### ISSUE TITLE
Suggestion for `delete mapping` DSL

### ISSUE THREAD

**Issue by sdiwu** [sksamuel/elastic4s#417]
I'm trying to delete the ES type (index/type) with elastic4s. I found there is `delete mapping <index/type>` DSL to do this but no documentation or example at all on elastic4s page. So at first, I tried this way and expect it would work:

    client.execute( delete mapping "bands/artists" )

But it didn't work and I got runtime error:

	org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: mapping type is missing;
			at org.elasticsearch.action.ValidateActions.addValidationError(ValidateActions.java:29)
			at org.elasticsearch.action.admin.indices.mapping.delete.DeleteMappingRequest.validate(DeleteMappingRequest.java:59)
			at org.elasticsearch.action.TransportActionNodeProxy.execute(TransportActionNodeProxy.java:52)
			
Since there are no documentation, I have to check out the ElasticDsl code to find out I have to do it this way:

    client.execute( delete mapping IndexType("bands", "artists") )

I think it's better if it can also be done with `delete mapping "bands/artists"`. It looks more natural.

**Comment by MLnick** [comment]
You can also use `client.execute { delete mapping "index" / "type "}`

**Comment by sdiwu** [comment]
Ah thank you for that. Glad there is shorter syntax, but I still suggest to add `"index/type"` way so it's consistent with the other DSL that is able to process that way too.

**Comment by MLnick** [comment]
Fair enough (I am not the author but @sksamuel might have a view).

I personally prefer and use the `/` syntax because I find it clearer than string interpolation when passing in variable into queries (e.g `index into indexName / docType` rather than `index into s"$indexName/$docType"`)

**Comment by sdiwu** [comment]
I usually make a constant for the "index/type", e.g.:

    val bandsArtists = "bands/artists"

thus:

    index into ESConstant.bandsArtists

**Comment by sksamuel** [comment]
For 2.0 I'll make it accept both formats.
