### ISSUE TITLE
Dynamic templates don't support mapping without field name

### ISSUE THREAD

**Issue by MLnick** [sksamuel/elastic4s#451]
Dynamic templates allow matching against a field name and specifying the type for that matching field (see https://www.elastic.co/guide/en/elasticsearch/guide/current/custom-dynamic-mapping.html)

However, the DSL requires the mapping to be specified using a `TypedFieldDefinition` (as per https://github.com/sksamuel/elastic4s/blob/master/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/mappings/DynamicTemplateDefinition.scala#L64), which defeats the purpose.

e.g.
```scala
val priceTemplate = new DynamicTemplateDefinition("price")
  .matching("*_price")
  .mapping("price" typed DoubleType)
```

should instead be something like:
```scala
val priceTemplate = new DynamicTemplateDefinition("price")
  .matching("*_price")
  .mapping(DoubleType)
```

**Comment by MLnick** [comment]
More info - this example

```scala
  val esClient = ElasticClient.local

  val priceTemplate = new DynamicTemplateDefinition("price")
    .matching("*_price")
    .mapping("price" typed DoubleType)

  esClient.execute {
    create index "test" mappings { "test" as () dynamicTemplates priceTemplate }
  }.await
```

creates
```
Exception in thread "main" java.lang.StackOverflowError
	at com.sksamuel.elastic4s.mappings.MappingDefinition.templates(MappingDefinition.scala:141)
	at com.sksamuel.elastic4s.mappings.MappingDefinition.templates(MappingDefinition.scala:141)
	at com.sksamuel.elastic4s.mappings.MappingDefinition.templates(MappingDefinition.scala:141)
	at com.sksamuel.elastic4s.mappings.MappingDefinition.templates(MappingDefinition.scala:141)
	at com.sksamuel.elastic4s.mappings.MappingDefinition.templates(MappingDefinition.scala:141)
	at com.sksamuel.elastic4s.mappings.MappingDefinition.templates(MappingDefinition.scala:141)
	at com.sksamuel.elastic4s.mappings.MappingDefinition.templates(MappingDefinition.scala:141)
...
```

**Comment by TrustNoOne** [comment]
you have to use template(Seq(...): _*). it's the only one that works.

https://github.com/sksamuel/elastic4s/issues/466
