### ISSUE TITLE
Getting NoNodeAvailableException while trying to connect using transport client

### ISSUE THREAD

**Issue by tprizler** [sksamuel/elastic4s#476]
Hey! 

I am trying to connect to my cluster using transport client. (using version 2.0.0)
I tried it in 2 ways, both gave me the same exception when trying to index a document into my index.

Option 1:

     val settings = Settings.settingsBuilder()
      .put("transport.ping_schedule", "5s")
      .put("cluster.name", clusterId)
      .put("shield.transport.ssl", true)
      .put("request.headers.X-Found-Cluster", clusterId)
      .put("shield.user", "user:pass)
      .build();

    // Instantiate a TransportClient and add the cluster to the list of addresses to connect to.
    // Only port 9343 (SSL-encrypted) is currently supported.
    val hostname = clusterId + "." + region + ".aws.found.io";
    val client: Client = TransportClient.builder().settings(settings).build().
      addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName(hostname), my_port));
    ElasticClient.fromClient(client)

Option 2:

    ElasticClient.transport(settings, ElasticsearchClientUri("elasticsearch://" + hostname + ":" + my_port))

Finally I ran:

    client.execute {
        index into "my_index" / "artists" fields "name" -> "coldplay"
    }.await

Which gave me this exception:

     None of the configured nodes are available: []
     NoNodeAvailableException[None of the configured nodes are available: []]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:280)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:197)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:272)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:347)
	at org.elasticsearch.client.support.AbstractClient.index(AbstractClient.java:359)
	at com.sksamuel.elastic4s.IndexDsl$IndexDefinitionExecutable$$anonfun$apply$1.apply(IndexDsl.scala:23)
	at com.sksamuel.elastic4s.IndexDsl$IndexDefinitionExecutable$$anonfun$apply$1.apply(IndexDsl.scala:23)
	at com.sksamuel.elastic4s.Executable$class.injectFutureAndMap(Executable.scala:21)
	at com.sksamuel.elastic4s.IndexDsl$IndexDefinitionExecutable$.injectFutureAndMap(IndexDsl.scala:20)
	at com.sksamuel.elastic4s.IndexDsl$IndexDefinitionExecutable$.apply(IndexDsl.scala:23)
	at com.sksamuel.elastic4s.IndexDsl$IndexDefinitionExecutable$.apply(IndexDsl.scala:20)
	at com.sksamuel.elastic4s.ElasticClient.execute(ElasticClient.scala:20)

When debugging this, I saw that the Elasticsearch client in the first option, managed to connect to the server, while invoking client.asInstanceOf[TransportClient].listedNodes() I got the correct node.
Am I missing here something?

Thank you!

**Comment by sksamuel** [comment]
Can you paste the output of host:9200 ?

**Comment by tprizler** [comment]
Sure! Removed the actual cluster id:

    {
       name: "instance-0000000000",
       cluster_name: "my_cluster_id",
       version: {
            number: "2.0.1",
            build_hash: "build_hash",
            build_timestamp: "2015-11-18T17:42:23Z",
            build_snapshot: false,
            lucene_version: "5.2.1"
        },
        tagline: "You Know, for Search"
     }

**Comment by sksamuel** [comment]
Cluster id is what I was looking for :) But all I wanted to see was are you setting it correctly? Usually when I see  None of the configured nodes are available: [] it means you're connecting to the correct host/port but not specifying the right cluster name.

**Comment by tprizler** [comment]
I see:) Well I can assure you that the cluster_name value is the value I use in my example as clusterId.
The thing is the Elasticsearch Transport client manage to connect! 
But when the elastic4s client try to execute it fails with this exception.

What else can I do? need more information? And thank you!

**Comment by tprizler** [comment]
When looking at it again I see that the listed nodes include the node I am trying to connect to but the connected nodes is an empty list..:-|

**Comment by sksamuel** [comment]
I've never used shield, so you could try that.

**Comment by tprizler** [comment]
Yep.. this was indeed shield configuration problem.. thanks:)

**Comment by nrstott** [comment]
I'm encountering this exact error. My cluster names match. I can connect just fine from a standalone scala program but from Spark it is not working.

What were your shield configuration problems, @tpraizler
