### ISSUE TITLE
NoNodeAvailableException when trying to connect to ElasticSearch 2.2.0 with Shield on localhost

### ISSUE THREAD

**Issue by rahulsinghai** [sksamuel/elastic4s#520]
Hi, I am getting following exception, when I am trying to connect to ElasticSearch 2.2.0 with Shield 2.2.0 on localhost (127.0.0.1):

    2016-02-08 16:48:13,303 INFO  [com.xxx.clients.ThreatClient  ] - Loading threats from ElasticSearch based on rawQuery: { "match_all": {} }
    2016-02-08 16:48:13,955 ERROR [akka.actor.OneForOneStrategy                      ] - None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{127.0.0.1:9300}]
    org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{127.0.0.1:9300}]
    	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290) ~[elasticsearch-2.2.0.jar:2.2.0]
    	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:286) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:351) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:574) ~[elasticsearch-2.2.0.jar:2.2.0]
	at com.sksamuel.elastic4s.SearchDsl$SearchDefinitionExecutable$$anonfun$apply$1.apply(SearchDsl.scala:38) ~[elastic4s-core_2.11-2.2.0.jar:2.2.0]
	at com.sksamuel.elastic4s.SearchDsl$SearchDefinitionExecutable$$anonfun$apply$1.apply(SearchDsl.scala:38) ~[elastic4s-core_2.11-2.2.0.jar:2.2.0]
	at com.sksamuel.elastic4s.Executable$class.injectFutureAndMap(Executable.scala:21) ~[elastic4s-core_2.11-2.2.0.jar:2.2.0]
	at com.sksamuel.elastic4s.SearchDsl$SearchDefinitionExecutable$.injectFutureAndMap(SearchDsl.scala:35) ~[elastic4s-core_2.11-2.2.0.jar:2.2.0]
	at com.sksamuel.elastic4s.SearchDsl$SearchDefinitionExecutable$.apply(SearchDsl.scala:38) ~[elastic4s-core_2.11-2.2.0.jar:2.2.0]
	at com.sksamuel.elastic4s.SearchDsl$SearchDefinitionExecutable$.apply(SearchDsl.scala:35) ~[elastic4s-core_2.11-2.2.0.jar:2.2.0]
	at com.sksamuel.elastic4s.ElasticClient.execute(ElasticClient.scala:20) ~[elastic4s-core_2.11-2.2.0.jar:2.2.0]
	at com.barclays.dsi.fusioncell.clients.ThreatClient.searchIndicators(Clients.scala:147) ~[classes/:na]
	at com.barclays.dsi.fusioncell.clients.ThreatClient$$anonfun$receive$4.applyOrElse(Clients.scala:140) ~[classes/:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[akka-actor_2.11-2.4.1.jar:na]
	at com.barclays.dsi.fusioncell.clients.ThreatClient.aroundReceive(Clients.scala:36) ~[classes/:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.1.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.1.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.1.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.1.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]

I managed to fix the exception by overriding transport method of com.sksamuel.elastic4s.ElasticClient class and adding "addPlugin()" call as follows:

    def transport(settings: Settings, uri: ElasticsearchClientUri): ElasticClient = {
      val client = TransportClient.builder.addPlugin(classOf[org.elasticsearch.shield.ShieldPlugin]).settings(settings).build()

      for ( (host, port) <- uri.hosts ) {
        client.addTransportAddress(new InetSocketTransportAddress(new InetSocketAddress(host, port)))
      }
      ElasticClient.fromClient(client)
    }

**Comment by alexshadow007** [comment]
@rahulsinghai https://github.com/sksamuel/elastic4s/pull/514

**Comment by rahulsinghai** [comment]
@alexshadow007 Thanks for the solution :)
