### ISSUE TITLE
filtered query with elastic4s

### ISSUE THREAD

**Issue by balajraj** [sksamuel/elastic4s#522]
I was reading your documentation and really interested in using elastic4s as a scala client for my project, could not find information on how to use the following below query with elastic4s. One of the field that I have has a data type of geo_point, so interested to search on geo_distance. 

the json query that works for me with curl. 
{
  "query": {

    "filtered": {
      "query" : {
              "match" : { "user_id" :  "1000000"}
        },
      "filter": {
            "geo_distance": {
               "location": {
                 "lat":  12.946475,
                 "lon": 77.613284
               },
               "distance": "3km"
            }
       }
    }
  }

}

I thought I could execute raw json query but I am getting exception on that. 

val res:Future[SearchResponse]  = client.execute { search in  "*" types("trips") rawQuery {
      """{"query": {"match" : { "user_id" :  "1000000"}}}"""
      } searchType SearchType.Scan
    }

[2016-02-09 13:56:30,592][DEBUG][action.search.type       ] [Helleyes] All shards failed for phase: [init_scan]
org.elasticsearch.search.SearchParseException: [userhistory][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query_binary":"eyJxdWVyeSI6IHsibWF0Y2giIDogeyAidXNlcl9pZCIgOiAgIjEwMDAwMDAifX19"}]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:747)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:572)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:544)
	at org.elasticsearch.search.SearchService.executeScan(SearchService.java:239)
	at org.elasticsearch.search.action.SearchServiceTransportAction$19.call(SearchServiceTransportAction.java:486)
	at org.elasticsearch.search.action.SearchServiceTransportAction$19.call(SearchServiceTransportAction.java:483)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.query.QueryParsingException: [userhistory] No query registered for [query]
	at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:305)
	at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:382)
	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:281)
	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:276)
	at org.elasticsearch.search.query.QueryBinaryParseElement.parse(QueryBinaryParseElement.java:36)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:731)
	... 9 more

One other suggestion when I was trying to use a 1.7.2 version of elastic search with latest version of elastic4s the I was repeatedly getting connection failure exceptions, later I figured out version mismatch was the root cause, it would be helpful if elastic4s can give more meaningful error messages.

**Comment by alexshadow007** [comment]
@balajraj 
For Elasticsearch 1.7.x you must use elastic4s 1.7.5

You can run your query like this:
```
client.execute {
        search in "*" / "trips" query filteredQuery
          .query(matchQuery("user_id", 1000000))
          .filter(geoDistance("location").lat(12.946475).lon(77.613284).distance("3km"))
}
```

**Comment by balajraj** [comment]
That worked thank you so much.

**Comment by troypayne** [comment]
This is now deprecated, what's the equivalent using boolQuery (including its necessary import)

**Comment by nighatusman03** [comment]
Sir i am trying to run the below query in Intellij IDEA Community Edition:
val res:Future[SearchResponse] = client execute { search in "cuckoo-2016-12" query
    "_source": ["virustotal.md5","virustotal.total","virustotal.positives","malfamily","malscore"], 
    "size": 5   
    }
But i am getting an error which is shown below:
[error] /home/Desktop/todaynb/example.scala:17: identifier expected but '[' found.
[error]     "_source": ["virustotal.md5","virustotal.total","virustotal.positives","malfamily","malscore"], 
[error]                      ^
[error] one error found

Kindly assist me in it. Thanks in advance for your valuable comments.
