### ISSUE TITLE
ElasticClient.local path.home not configured

### ISSUE THREAD

**Issue by arnarthor** [sksamuel/elastic4s#549]
I'm trying to set up ElasticClient.local to talk to when running a service locally during development. After upgrading to version 2.3 it doesn't work any more without setting `path.home`. 

What should the value of this be? I've tried multiple ways to do this and can't get it to work.

Example code that doesn't work 
```
    val settings = Settings.settingsBuilder().put("cluster.name", clusterName)
    tier match {
      case "production" => ElasticClient.transport(settings.build, ElasticsearchClientUri(esHosts))
      case "staging" => ElasticClient.transport(settings.build, ElasticsearchClientUri(esHosts))
      case "development" => ElasticClient.local
    }
```
This throws this error 

```
                     java.lang.IllegalStateException: path.home is not configured
                        at org.elasticsearch.env.Environment.<init>(Environment.java:101)
                        at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:81)
                        at org.elasticsearch.node.Node.<init>(Node.java:140)
                        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
                        at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:150)
                        at com.sksamuel.elastic4s.ElasticClient$.local(ElasticClient.scala:124)
                        at com.sksamuel.elastic4s.ElasticClient$.local(ElasticClient.scala:117)
                        at com.quizup.tvadmin.services.ElasticSearchClientWrapper$.apply(ESCastingService.scala:28)
                        at com.quizup.tvadmin.services.ESCastingService.<init>(ESCastingService.scala:41)
                        at com.quizup.tvadmin.test.ESSuite$class.$init$(ESSuite.scala:21)
                        at com.quizup.tvadmin.TvServiceSpec.<init>(TvServiceSpec.scala:27)
                        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
                        at java.lang.Class.newInstance(Class.java:442)
                        at org.scalatest.junit.JUnitRunner.<init>(JUnitRunner.scala:64)
                        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
                        at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
                        at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
                        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
                        at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
                        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
                        at __shaded_by_pants__.org.pantsbuild.tools.junit.impl.AnnotatedClassRequest.getRunner(AnnotatedClassRequest.java:43)
                        at __shaded_by_pants__.org.pantsbuild.tools.junit.impl.CompositeRequest.runChild(CompositeRequest.java:53)
                        at __shaded_by_pants__.org.pantsbuild.tools.junit.impl.ConcurrentCompositeRequest$1$1.run(ConcurrentCompositeRequest.java:36)
                        at __shaded_by_pants__.org.pantsbuild.tools.junit.impl.ConcurrentRunnerScheduler.finished(ConcurrentRunnerScheduler.java:85)
                        at __shaded_by_pants__.org.pantsbuild.tools.junit.impl.ConcurrentCompositeRequest$1.evaluate(ConcurrentCompositeRequest.java:45)
                        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                        at __shaded_by_pants__.org.pantsbuild.tools.junit.impl.ConsoleRunnerImpl.run(ConsoleRunnerImpl.java:426)
                        at __shaded_by_pants__.org.pantsbuild.tools.junit.impl.ConsoleRunnerImpl.main(ConsoleRunnerImpl.java:753)
                        at org.pantsbuild.tools.junit.ConsoleRunner.main(ConsoleRunner.java:12)
```

I tried this as well, which didn't throw an exception, but when running this the node doesn't find the data folder which results in timeouts on all tests because it hangs while waiting for cluster to be created.
```
    val settings = Settings.settingsBuilder().put("cluster.name", clusterName)
    tier match {
      case "production" => ElasticClient.transport(settings.build, ElasticsearchClientUri(esHosts))
      case "staging" => ElasticClient.transport(settings.build, ElasticsearchClientUri(esHosts))
      case "development" => ElasticClient.local(
        settings
          .put("path.home", System.getProperty("user.dir"))
          .build
      )
    }
```

**Comment by sksamuel** [comment]
Since I think 2.0 or 2.1 you have to supply path.home as it will no longer default.

**Comment by arnarthor** [comment]
Ok, I actually think I solved this with some dirty hack by including the testkit NodeBuilder in my app when running locally and using that.

If someone runs into this, this is what I did

```
object App with NodeBuilder {
 def main(): Unit = {
   ....
    val esHosts = s"elasticsearch://${config.elasticSearchUrls.map(url => url.dropRight(4) + "9300").mkString(",")}"
    val esClient =
      if (tier != "development") ElasticSearchClientWrapper(esHosts, config.elasticSearchClusterName, tier)
      else createLocalClient

    val esService = new ESService(
      // URL conversion is to remove the 9200 port and add 9300 instead
      config.elasticSearchIndexName,
      config.elasticSearchDocumentName,
      esClient,
      FuturePool.unboundedPool
    )

    if (tier == "development") {
      val source = "Mapping.json"
      esService.createIndex(config.elasticSearchIndexName, source)
    }
   ....
  }
}
```
