### ISSUE TITLE
[elastic4s-jackson_2.11] Updating jackson dependency to 2.7.2

### ISSUE THREAD

**Issue by prasanthkrishnan** [sksamuel/elastic4s#564]
I ran into the following issue when using `"com.sksamuel.elastic4s" % "elastic4s-jackson_2.11" % "2.3.0",` to do the following

```
def test = Action.async {
    val s = sample("test",12,123.4,Set("tag1","tag2"))
    val q = index into "sample"/"a" source  s id "2"
    println(q.show)
    client.execute {
      q
    }.map { resp =>
      Ok(resp.toString)
    }
  }
```

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Incompatible Jackson version: 2.7.1
    at com.fasterxml.jackson.module.scala.JacksonModule$class.setupModule(JacksonModule.scala:64)
    at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:19)
    at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:722)
    at com.sksamuel.elastic4s.jackson.JacksonJson$.<init>(JacksonJson.scala:11)
    at com.sksamuel.elastic4s.jackson.JacksonJson$.<clinit>(JacksonJson.scala)
    at com.sksamuel.elastic4s.jackson.ElasticJackson$Implicits$$anon$1.json(ElasticJackson.scala:13)
    at com.sksamuel.elastic4s.IndexDefinition.source(IndexDsl.scala:85)
    at controllers.testController$$anonfun$test$1.apply(testController.scala:22)
    at controllers.testController$$anonfun$test$1.apply(testController.scala:20)
    at play.api.mvc.ActionBuilder$$anonfun$async$1.apply(Action.scala:421)
```

With reference to the issue [jackson-module-scala](https://github.com/FasterXML/jackson-module-scala/issues/233), upgrading the jackson version should solve the issue.

**Comment by iamszabo** [comment]
Hi, is there any follow up on this issue?

**Comment by nandanrao** [comment]
@prasanthkrishnan how did you work around this issue??
