### ISSUE TITLE
Error NoNodeAvailableException[None of the configured nodes are available: 

### ISSUE THREAD

**Issue by nsphung** [sksamuel/elastic4s#576]
Hello,

I'm using Elastisearch 2.3.3 with elastic4s 2.3.0. I'm instantiating the client like this 

``` scala
  val settings = Settings.settingsBuilder().put("cluster.name", "clustername").build()
  val uri = ElasticsearchClientUri("elasticsearch://ies03.int.adencf.local:9307,ies04.int.adencf.local:9307,pfcaes01.int.adencf.local:9307,pfcaes02.int.adencf.local:9307")
  val clientOfferEs = ElasticClient.transport(settings, uri)
```

When I'm running integration tests, everything is working as expected

```
2016-05-31 15:14:21 DEBUG network:107 - configuration:

lo
        inet 127.0.0.1 netmask:255.0.0.0 scope:host
        inet6 ::1 prefixlen:128 scope:host
        UP LOOPBACK mtu:65536 index:1

eth0
        inet 10.53.42.116 netmask:255.255.252.0 broadcast:10.53.43.255 scope:site
        inet6 fe80::c634:6bff:fe5e:2814 prefixlen:64 scope:link
        hardware C4:34:6B:5E:28:14
        UP MULTICAST mtu:1500 index:2

docker0
        inet 172.17.0.1 netmask:255.255.0.0 broadcast:0.0.0.0 scope:site
        inet6 fe80::42:e1ff:fe30:2d9c prefixlen:64 scope:link
        hardware 02:42:E1:30:2D:9C
        UP MULTICAST mtu:1500 index:3

vetha4f3f91
        inet6 fe80::b841:e9ff:fe7d:35b0 prefixlen:64 scope:link
        hardware BA:41:E9:7D:35:B0
        UP MULTICAST mtu:1500 index:39

2016-05-31 15:14:21 DEBUG netty:104 - using gathering [true]
2016-05-31 15:14:21 DEBUG transport:120 - [Professor X] node_sampler_interval[5s]
2016-05-31 15:14:21 DEBUG SelectorUtil:58 - Using select timeout of 500
2016-05-31 15:14:21 DEBUG SelectorUtil:58 - Epoll-bug workaround enabled = false
2016-05-31 15:14:21 DEBUG transport:177 - [Professor X] adding address [{#transport#-1}{10.154.165.156}{ies03.int.adencf.local/10.154.165.156:9307}]
2016-05-31 15:14:21 DEBUG netty:931 - [Professor X] connected to node [{#transport#-1}{10.154.165.156}{ies03.int.adencf.local/10.154.165.156:9307}]
2016-05-31 15:14:21 DEBUG netty:931 - [Professor X] connected to node [{ies03}{sguN-3ikSUaQ57Lvpi0H5A}{10.154.165.156}{ies03.int.adencf.local/10.154.165.156:9307}{dc=AUB}]
2016-05-31 15:14:21 DEBUG transport:177 - [Professor X] adding address [{#transport#-2}{10.153.165.116}{ies04.int.adencf.local/10.153.165.116:9307}]
2016-05-31 15:14:21 DEBUG netty:931 - [Professor X] connected to node [{#transport#-2}{10.153.165.116}{ies04.int.adencf.local/10.153.165.116:9307}]
2016-05-31 15:14:21 DEBUG netty:931 - [Professor X] connected to node [{ies04}{Mkuh1ALtR_WTTT7MORy2kA}{10.153.165.116}{ies04.int.adencf.local/10.153.165.116:9307}{dc=CBV}]
2016-05-31 15:14:21 DEBUG transport:177 - [Professor X] adding address [{#transport#-3}{10.154.165.93}{pfcaes01.int.adencf.local/10.154.165.93:9307}]
2016-05-31 15:14:21 DEBUG netty:931 - [Professor X] connected to node [{#transport#-3}{10.154.165.93}{pfcaes01.int.adencf.local/10.154.165.93:9307}]
2016-05-31 15:14:21 DEBUG netty:931 - [Professor X] connected to node [{pfcaes01}{a1m6sjuxRz-atMg8e81b1A}{10.154.165.93}{pfcaes01.int.adencf.local/10.154.165.93:9307}{dc=AUB}]
2016-05-31 15:14:21 DEBUG transport:177 - [Professor X] adding address [{#transport#-4}{10.153.165.93}{pfcaes02.int.adencf.local/10.153.165.93:9307}]
2016-05-31 15:14:21 DEBUG netty:931 - [Professor X] connected to node [{#transport#-4}{10.153.165.93}{pfcaes02.int.adencf.local/10.153.165.93:9307}]
2016-05-31 15:14:21 DEBUG netty:931 - [Professor X] connected to node [{pfcaes02}{qhpjoHmOS0if9iNnPOSlIA}{10.153.165.93}{pfcaes02.int.adencf.local/10.153.165.93:9307}{dc=CBV}]
```

But when I'm running my application, an error occurred 

```
16/05/31 14:51:35 ERROR Executor: Exception in task 9.0 in stage 0.0 (TID 9)
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{10.154.165.156}{ies03.int.adencf.local/10.154.165.156:9307}, {#transport#-2}{10.153.165.116}{ies04.int.adencf.local/10.153.165.116:9307}, {#transport#-3}{10.154.165.93}{pfcaes01.int.adencf.local/10.154.165.93:9307}, {#transport#-4}{10.153.165.93}{pfcaes02.int.adencf.local/10.153.165.93:9307}]]
    at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
    at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
    at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
    at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:286)
    at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java351)
    at org.elasticsearch.client.support.AbstractClient.get(AbstractClient.java:443)
    at com.sksamuel.elastic4s.GetDsl$GetDefinitionExecutable$$anonfun$apply$1.apply(GetDsl.scala:21)
    at com.sksamuel.elastic4s.GetDsl$GetDefinitionExecutable$$anonfun$apply$1.apply(GetDsl.scala:21)
    at com.sksamuel.elastic4s.Executable$class.injectFutureAndMap(Executable.scala:21)
    at com.sksamuel.elastic4s.GetDsl$GetDefinitionExecutable$.injectFutureAndMap(GetDsl.scala:19)
    at com.sksamuel.elastic4s.GetDsl$GetDefinitionExecutable$.apply(GetDsl.scala:21)
    at com.sksamuel.elastic4s.GetDsl$GetDefinitionExecutable$.apply(GetDsl.scala:19)
    at com.sksamuel.elastic4s.ElasticClient.execute(ElasticClient.scala:21)
```

Does anyone has the same issue ? I'm using the TCP port for my elasticsearch instances as expected but it doesn't seem to work.

Regards,

**Comment by BranislavLazic** [comment]
Yep. Same issue.

**Comment by mariussoutier** [comment]
I have the same issue, even with the correct port. The elastic search logs show "Incompatible message frame format".

**Comment by sksamuel** [comment]
Sounds like a version mismatch between the version in e4s and the version on the server.

**Comment by mariussoutier** [comment]
#589 fixed it for me.
