### ISSUE TITLE
Spray + Akka + Elastic4s

### ISSUE THREAD

**Issue by ibaisi** [sksamuel/elastic4s#588]
I have a project running with Spray 1.3.3 and Akka 2.4.4 and only by adding elastic4s 2.3.0 as dependency, I get an error that shuts down my JVM:

`Uncaught error from thread [Sys-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[Sys]
java.lang.NoSuchMethodError: org.jboss.netty.handler.codec.http.HttpRequest.setHeader(Ljava/lang/String;Ljava/lang/Object;)V
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.construct(NettyAsyncHttpProvider.java:693)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.buildRequest(NettyAsyncHttpProvider.java:650)
	at com.ning.http.client.providers.netty.NettyConnectListener$Builder.build(NettyConnectListener.java:144)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.doConnect(NettyAsyncHttpProvider.java:1070)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:935)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:499)
	at dispatch.HttpExecutor$class.apply(execution.scala:47)
	at dispatch.Http.apply(execution.scala:12)
	at dispatch.HttpExecutor$class.apply(execution.scala:42)
	at dispatch.Http.apply(execution.scala:12)
	at com.bbtv.vtitle2.service.KeywordsService$.makeDbPediaCall(KeywordsService.scala:41)
	at com.bbtv.vtitle2.service.KeywordsService$$anonfun$getKeywords$2.apply(KeywordsService.scala:26)
	at com.bbtv.vtitle2.service.KeywordsService$$anonfun$getKeywords$2.apply(KeywordsService.scala:25)
	at akka.stream.impl.fusing.MapAsync$$anon$9$$anon$10.onPush(Ops.scala:590)
	at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:575)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:586)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:533)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:445)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:366)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:504)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:539)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:489)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:495)
	at akka.actor.ActorCell.create(ActorCell.scala:590)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

This is my build.sbt:

`organization  := "com.example"

version       := "0.1"

scalaVersion  := "2.11.8"

scalacOptions := Seq("-unchecked", "-deprecation", "-encoding", "utf8")

libraryDependencies ++= {
  val akkaV = "2.4.4"
  val sprayV = "1.3.3"
  Seq(
    "io.spray"            %%  "spray-can"     % sprayV,
    "io.spray"            %%  "spray-routing" % sprayV,
    "io.spray"            %%  "spray-testkit" % sprayV  % "test",
    "com.typesafe.akka"   %%  "akka-actor"    % akkaV,
    "com.typesafe.akka"   %%  "akka-testkit"  % akkaV   % "test",
    "org.specs2"          %%  "specs2-core"   % "2.3.11" % "test",
    "com.typesafe.akka" %% "akka-stream-experimental" % "2.0.1",
    "com.typesafe.akka" %% "akka-http-experimental" % "2.4.7",
    "net.databinder.dispatch" %% "dispatch-core" % "0.11.2",
    "ch.qos.logback" % "logback-classic" % "1.1.2",
    "com.timgroup" % "java-statsd-client" % "3.1.0",
    "joda-time" % "joda-time" % "2.1",
    "org.joda" % "joda-convert" % "1.2",
    "com.sksamuel.elastic4s" %% "elastic4s-core" % "2.3.0"
  )
}

Revolver.settings`

Are there any incompatibility issues with the Spray or Akka libraries?

**Comment by sksamuel** [comment]
Elastic4s-core really only has scalactic and elasticsearch. I think the problem might be between the version of netty akka is using and the version of netty es is using.

**Comment by victorfranz** [comment]
I have an older app running successfully with versions akkaV = "2.3.6" and sprayV = "1.3.2".

**Comment by ibaisi** [comment]
I'll try that out, thanks!

**Comment by ibaisi** [comment]
Thanks for the tip guys. Actually, the issue is with the version of netty Dispatch is using.

Cheers!
