### ISSUE TITLE
QueryStringQueryDefinition value boosting should be Long

### ISSUE THREAD

**Issue by MasseGuillaume** [sksamuel/elastic4s#594]
```
server Caused by: java.lang.NumberFormatException: For input string: "shapeless"
server  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
server  at java.lang.Long.parseLong(Long.java:589)
server  at java.lang.Long.parseLong(Long.java:631)
server  at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseLongValue(NumberFieldMapper.java:296)
server  at org.elasticsearch.index.mapper.core.LongFieldMapper$LongFieldType.indexedValueForSearch(LongFieldMapper.java:164)
```

**Comment by MasseGuillaume** [comment]
related to https://github.com/elastic/elasticsearch/issues/2438#issuecomment-232155961

**Comment by sksamuel** [comment]
You've set the field to long and then trying to pass in a value of "shapeless".
