### ISSUE TITLE
Gauva version conflict when using with Apache Spark

### ISSUE THREAD

**Issue by arturekbb** [sksamuel/elastic4s#595]
elastic4s 2.3.0 uses guava 18, apache spark uses guava 14, what causes error

```
16/07/15 08:58:41 WARN scheduler.TaskSetManager: Lost task 1.0 in stage 1.0 (TID 17, hdp115-yarn.prod.ne.lan): java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.threadpool.ThreadPool
	at org.elasticsearch.client.transport.TransportClient$Builder.build(TransportClient.java:131)
	at com.sksamuel.elastic4s.ElasticClient$.transport(ElasticClient.scala:103)
	at com.sksamuel.elastic4s.ElasticClient$.remote(ElasticClient.scala:111)
	at com.hgintelligence.EsFetcher.<init>(EsFetcher.scala:18)
	at com.hgintelligence.MyJob$$anonfun$doMyJobOnRDD$3.apply(MyJob.scala:47)
	at com.hgintelligence.MyJob$$anonfun$doMyJobOnRDD$3.apply(MyJob.scala:46)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:878)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:878)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1767)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1767)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
	at org.apache.spark.scheduler.Task.run(Task.scala:70)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

16/07/15 08:58:41 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 1.0 (TID 16, hdp115-yarn.prod.ne.lan): java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
	at org.elasticsearch.threadpool.ThreadPool.<clinit>(ThreadPool.java:190)
	at org.elasticsearch.client.transport.TransportClient$Builder.build(TransportClient.java:131)
	at com.sksamuel.elastic4s.ElasticClient$.transport(ElasticClient.scala:103)
	at com.sksamuel.elastic4s.ElasticClient$.remote(ElasticClient.scala:111)
	at com.hgintelligence.EsFetcher.<init>(EsFetcher.scala:18)
	at com.hgintelligence.MyJob$$anonfun$doMyJobOnRDD$3.apply(MyJob.scala:47)
	at com.hgintelligence.MyJob$$anonfun$doMyJobOnRDD$3.apply(MyJob.scala:46)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:878)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:878)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1767)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1767)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
	at org.apache.spark.scheduler.Task.run(Task.scala:70)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sksamuel** [comment]
The use of Guava comes from the Elasticsearch dependency itself, so there's nothing I can do to change it.
