### ISSUE TITLE
Elastic4s streams : Subscriber completionFn is also called when errorFn is called

### ISSUE THREAD

**Issue by fchaillou** [sksamuel/elastic4s#615]
Hello,
I'm using the reactive streams subscriber to push logs to an index.
Actually, i'm using akka streams so i had to convert the Subscriber to a Sink.

In my use-case, i wanted to know when the subscriber has completed so i did the following :

``` scala
private[this] def indexLogs[T : RequestBuilder](source : Source[T, NotUsed]): Future[Unit] = {
    val promise = Promise[Unit]
    val elasticSubscriber = esClient.subscriber[T](
      completionFn = () => {promise.success(()); ()},
      errorFn = (error: Throwable) => {promise.failure(error); ()}
    )

    source
      .to(Sink.fromSubscriber(elasticSubscriber))
      .run()

    promise.future
  }
```

So basically, i'm completing my promise when  the subscriber calls my completionFn.

It works nicely however, i found the following logs in my production environment.

```
2016-08-04 00:01:13,109 ERROR c.s.elastic4s.streams.BulkActor sync-open-akka.actor.default-dispatcher-4 akka://sync-open/user/$Oh - Promise already completed.
java.lang.IllegalStateException: Promise already completed.
        at scala.concurrent.Promise$class.complete(Promise.scala:55) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.concurrent.Promise$class.success(Promise.scala:86) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:153) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at com.omsignal.sync.open.rest.omplus.E4sOmplusElasticSearchIndexClient$$anonfun$1.apply$mcV$sp(OmplusElasticSearchIndexClient.scala:93) ~[com.omsignal.sync-open-rest-1.25
.6.jar:1.25.6]
        at com.sksamuel.elastic4s.streams.BulkActor.postStop(BulkIndexingSubscriber.scala:176) ~[com.sksamuel.elastic4s.elastic4s-streams_2.11-2.3.0.omsignal.jar:2.3.0.omsignal]
        at akka.actor.Actor$class.aroundPostStop(Actor.scala:492) ~[com.typesafe.akka.akka-actor_2.11-2.4.6.jar:na]
        at com.sksamuel.elastic4s.streams.BulkActor.aroundPostStop(BulkIndexingSubscriber.scala:86) ~[com.sksamuel.elastic4s.elastic4s-streams_2.11-2.3.0.omsignal.jar:2.3.0.omsign
al]
        at akka.actor.dungeon.FaultHandling$class.akka$actor$dungeon$FaultHandling$$finishTerminate(FaultHandling.scala:210) ~[com.typesafe.akka.akka-actor_2.11-2.4.6.jar:na]
        at akka.actor.dungeon.FaultHandling$class.terminate(FaultHandling.scala:172) ~[com.typesafe.akka.akka-actor_2.11-2.4.6.jar:na]
        at akka.actor.ActorCell.terminate(ActorCell.scala:374) ~[com.typesafe.akka.akka-actor_2.11-2.4.6.jar:na]
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:467) ~[com.typesafe.akka.akka-actor_2.11-2.4.6.jar:na]
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483) ~[com.typesafe.akka.akka-actor_2.11-2.4.6.jar:na]
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282) [com.typesafe.akka.akka-actor_2.11-2.4.6.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:260) [com.typesafe.akka.akka-actor_2.11-2.4.6.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:224) [com.typesafe.akka.akka-actor_2.11-2.4.6.jar:na]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [com.typesafe.akka.akka-actor_2.11-2.4.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.7.jar:na]
```

Is this expected ?

Do you have a better way to do what i want by the way ?

Thanks for your great library !
Fabien

**Comment by sksamuel** [comment]
Can you change your errorFn to output something as well, and then re-run it.

**Comment by fchaillou** [comment]
Hi, sorry for my late reply.
The fail error would log something right now in our log since the failed future is returned to our spray handler. 
I never saw any log related to that so it doesnt seem the error function is called at all.
Since i updated my completion function to do ```promise.trySuccess()``` i dont see the issue anymore (obviously i'm just hiding it)

I could add a logging in the error but not right now since this is in production. 
Do you have any other idea ? Thanks

**Comment by sksamuel** [comment]
I was thinking that there's an error in the completion function itself throwing an exception and causing it, but I don't know. What be good to see what the underlying error is.

**Comment by JD557** [comment]
I also had this problem.

The thing is (IIRC), if your stream has an error, both the `completionFn and `errorFn` are called (`errorFn` is called first).

Here's how I'm handling it:

```
    val promise = Promise[Unit]

    val subscriber = esClient.subscriber[T](
      completionFn = { () =>
      if (!promise.isCompleted) promise.complete(Success(()))
      ()
    },
      errorFn = { t: Throwable => promise.complete(Failure(t)); () }
    )
```

**Comment by fchaillou** [comment]
Oh ok, that explains it :)
I'm doing exactly the same as you using trySuccess and tryFailure and i didn't had any issue since  :
```
val elasticSubscriber = esClient.subscriber[T](
      completionFn = () => {promise.trySuccess(()); ()},
      errorFn = (error: Throwable) => {promise.tryFailure(error); ()}
    )
```

**Comment by fchaillou** [comment]
Now i see the issue :
BulkActor handleError does 
```
config.errorFn(t)
...
context.stop(self)
```

and postStop does 
```
config.completionFn()
```

So i guess you should keep a flag to know if you had an error to decide whether to call completeFn in postStop or not.

Thanks !

**Comment by sksamuel** [comment]
I guess my thinking was that completionFn was like a finally block, in that it should always be called. I think in hindsight that was a bad idea.

Maybe for the upcoming 5.0.0 release I will change it. There's breaking changing due to changes in elasticsearch itself, so I guess anything is open.

**Comment by fchaillou** [comment]
Thanks for the clarification.
The way i interpret it is more like the semantic of Reactive Streams where you receive either a Complete or an Error.
Anyway this is not a big deal.
I will rename the issue though.

**Comment by sksamuel** [comment]
I have added a successFn which is only invoked when everything has completed without errors.
