### ISSUE TITLE
richSearchResponse.hits(0).sourceAsMap("field") yields error if field does not exist

### ISSUE THREAD

**Issue by jhendric98** [sksamuel/elastic4s#620]
Guide shows an example where you marshal the fields into an Implicit object of HitAs using a case class to define structure. 

I'm running into an issue when a document does not contain the field referenced in the implicit object. For instance in the example name and location is marshalled from the richsearchresponse. If 4 of 5 documents in a query response have both fields but the 5th only contains name, the sourceAsMap returns a java error: 

```
java.util.NoSuchElementException: key not found: location
	at scala.collection.MapLike$class.default(scratch_8.scala:224)
	at scala.collection.AbstractMap.default(scratch_8.scala:54)
	at scala.collection.MapLike$class.apply(scratch_8.scala:137)
	at scala.collection.AbstractMap.apply(scratch_8.scala:54)
	at #worksheet#.get$$instance$$res9(scratch_8.scala:80)
	at #worksheet#.#worksheet#(scratch_8.scala:227)
```

So, I've tried using fieldOpt to test for the presence of the field but I seem to get "none" as a result in every case. Since I get 5 results to my query, the test for totalHits passes. 

Thanks for any help.

**Comment by jhendric98** [comment]
Nevermind guys, I was able to find the solution.
