### ISSUE TITLE
MapperParsingException with CustomAnalyzerDefinition

### ISSUE THREAD

**Issue by rdgreen** [sksamuel/elastic4s#662]
When I use `CustomAnalyzerDefinition`, this exception occurs:

```
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [foo]: analyzer [lowercase_keyword] not found for field [raw]
```

Using jdb, I notice that the settings constructed by elastic4s are like this:

```
t.build().settings.settings = "{analysis.analyzer.lowercase_keyword.filter.0=lowercase, analysis.analyzer.lowercase_keyword.tokenizer=keyword, analysis.analyzer.lowercase_keyword.type=custom}"
```

In my working version, the settings are created like this:

```
.put("analysis.analyzer.lowercase_keyword.filter", "[lowercase]")
```

Maybe that difference is why it doesn't work?

**Comment by sksamuel** [comment]
Which version?

**Comment by rdgreen** [comment]
Ah, actually we are using elastic4s 2.3.0, but with Elasticsearch 2.4.1. We should probably use matching versions!

**Comment by rdgreen** [comment]
It still happens with elastic4s 2.4.0.

**Comment by sksamuel** [comment]
I added a test and it looks ok. Can you show me the code you are running to get this error.

**Comment by SemanticBeeng** [comment]
Maybe my error (somewhat different) may help 

Happens as soon as I add a synonym token filter to the list of filters
Generates 

```
Temp 

{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "number_of_replicas": 0,
      "refresh_interval": "2000ms"
    },
    "analysis": {
      "analyzer": {
        "customanalyzer_index": {
          "type": "custom",
          "tokenizer": "lowercase",
          "filter": [
            "stop",
            "asciifolding",
            "synonym",
            "stemmeroverride",
            "stemmer_possessive",
            "stemmer",
            "word_delimiter"
          ]
        },
        "customanalyzer_search": {
          "type": "custom",
          "tokenizer": "lowercase",
          "filter": [
            "stop",
            "asciifolding",
            "stemmeroverride",
            "stemmer_possessive",
            "stemmer",
            "word_delimiter"
          ]
        }
      },
      "filter": {
        "stop": {
          "type": "stop",
          "stopwords_path": "analysis/en_US/stopwords.txt"
        },
        "synonym": {
          "type": "synonym",
          "format": "wordnet",
          "expand": true,
          "synonyms_path": "analysis/en_US/wn_s.pl",
          "tokenizer": "keyword"
        }
      }
    }
  }
}
```

stacktrace
```
[ERROR][03:00:55.818][c.n.c.c.i.p.c.ElasticController][C:] - Error creating ElasticSearch index
com.fasterxml.jackson.core.JsonGenerationException: Current context not Object but root
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1897)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeEndObject(UTF8JsonGenerator.java:348)
	at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.writeEndObject(JsonXContentGenerator.java:142)
	at org.elasticsearch.common.xcontent.XContentBuilder.endObject(XContentBuilder.java:186)
	at com.sksamuel.elastic4s.AnalysisDefinition$$anonfun$build$4.apply(CreateIndexDsl.scala:212)
	at com.sksamuel.elastic4s.AnalysisDefinition$$anonfun$build$4.apply(CreateIndexDsl.scala:208)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.sksamuel.elastic4s.AnalysisDefinition.build(CreateIndexDsl.scala:208)
	at com.sksamuel.elastic4s.CreateIndexDefinition$$anonfun$_source$2.apply(CreateIndexDsl.scala:131)
	at com.sksamuel.elastic4s.CreateIndexDefinition$$anonfun$_source$2.apply(CreateIndexDsl.scala:131)
	at scala.Option.foreach(Option.scala:257)
	at com.sksamuel.elastic4s.CreateIndexDefinition._source(CreateIndexDsl.scala:131)
	at com.sksamuel.elastic4s.CreateIndexDsl$CreateIndexShow$.show(CreateIndexDsl.scala:32)
	at com.sksamuel.elastic4s.CreateIndexDsl$CreateIndexShowOps.show(CreateIndexDsl.scala:36)
```
code for overriden filter

```
case class KeywordSynonymTokenFilter(
  name: String,
  format: Option[String] = Some("wordnet"),
  ignoreCase: Option[Boolean] = Some(false),
  expand: Option[Boolean] = Some(true),
  path: Option[String]
) extends TokenFilter
    with TokenFilterDefinition
    with Product
    with Serializable {

  val filterType = "synonym"

  override def build(source: XContentBuilder): Unit = {
    source.field("format", "wordnet")
    expand.foreach(source.field("expand", _))
    path.foreach(source.field("synonyms_path", _))
    source.field("tokenizer", "keyword")

  }
}
```

had to override because this is a defect

```
    require(
      path.isDefined || synonyms.nonEmpty,
      "synonym requires either `synonyms` or `synonyms_path` to be configured"
    )
```

**Comment by sksamuel** [comment]
This is working in 5.0.0 onwards, I have just neglected to close the ticket.
