### ISSUE TITLE
Dependency Issues

### ISSUE THREAD

**Issue by michaelqiu94** [sksamuel/elastic4s#675]
I'm running a JAR application using 5.0.1 and am getting the following:

Exception in thread "main" java.lang.NoSuchMethodError: io.netty.buffer.CompositeByteBuf.addComponents(ZLjava/lang/Iterable;)Lio/netty/buffer/CompositeByteBuf;
at org.elasticsearch.transport.netty4.Netty4Utils.toByteBuf(Netty4Utils.java:75)
at org.elasticsearch.transport.netty4.Netty4Transport.sendMessage(Netty4Transport.java:449)
at org.elasticsearch.transport.netty4.Netty4Transport.sendMessage(Netty4Transport.java:91)
at org.elasticsearch.transport.TcpTransport.internalSendMessage(TcpTransport.java:947)
at org.elasticsearch.transport.TcpTransport.sendRequest(TcpTransport.java:929)
at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:493)
at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:459)
at org.elasticsearch.transport.TransportService.submitRequest(TransportService.java:445)
at org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler.doSample(TransportClientNodesService.java:388)
at org.elasticsearch.client.transport.TransportClientNodesService$NodeSampler.sample(TransportClientNodesService.java:324)
at org.elasticsearch.client.transport.TransportClientNodesService.addTransportAddresses(TransportClientNodesService.java:191)
at org.elasticsearch.client.transport.TransportClient.addTransportAddress(TransportClient.java:282)
at com.sksamuel.elastic4s.ElasticClient$$anonfun$transport$2.apply(ElasticClient.scala:103)
at com.sksamuel.elastic4s.ElasticClient$$anonfun$transport$2.apply(ElasticClient.scala:102)
at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
at scala.collection.immutable.List.foreach(List.scala:381)
at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
at com.sksamuel.elastic4s.ElasticClient$.transport(ElasticClient.scala:102)
at com.sksamuel.elastic4s.ElasticClient$.transport(ElasticClient.scala:67)

**Comment by sksamuel** [comment]
You need Netty 4.1 on your classpath. I'll fix this for 5.0.2

**Comment by captify-aakmatov** [comment]
I have the same problem, having Netty 4.1.7.Final in the classpath does not help. I am using elastic4s-tcp version 5.2.11. Adding org.elasticsearch.plugin/transport-netty3-client/jars/transport-netty3-client-5.2.0.jar to the classpath breaks it, but without it - it does not start also.

**Comment by subhasish23sahu** [comment]
im still getting the below error :
Exception in thread "main" java.lang.NoSuchMethodError: io.netty.buffer.CompositeByteBuf.addComponents(ZLjava/lang/Iterable;)Lio/netty/buffer/CompositeByteBuf;


I am using ES: 5.4.2 and Lucene: 6.5.1 and netty-all 4.0.9, netty buffer 4.1.11 and netty-common 4.1.11 jars

and my java code is as below :
Settings settings =Settings.builder().put("cluster.name", "my-application").build();
		TransportClient client = new PreBuiltTransportClient(settings);
        TransportAddress address = new InetSocketTransportAddress(InetAddress.getByName("localhost"), 9300);
        client.addTransportAddress(address);
