### ISSUE TITLE
Completion suggestion example needed

### ISSUE THREAD

**Issue by zy4** [sksamuel/elastic4s#680]
Is this suggestion method fully supported? I have difficulties to make this work in contrast to the term suggestion method which works very well. 

I am getting only a SearchParseException:

[2016-11-16 10:02:42,831][DEBUG][action.search            ] [Virako] [tkplay_dev][4], node[ib3x_5CgQjusuNDfM5bZ4w], [P], v[6], s[STARTED], a[id=K5Ne3_BVQdO8nbw4KA2--w]: Failed to
execute [org.elasticsearch.action.search.SearchRequest@7b5f9a3e]
RemoteTransportException[[Virako][10.39.6.106:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"suggest":{"jobs":{"text":"712110","completion":{"field":"jobID","size":10,"context":{"jobs":[]}}}}}]]; nested: ClassCastException[org.elasticsearch.index.mapper.core.StringFieldMapper$StringFieldType cannot be cast to org.elasticsearch.index.mapper.core.CompletionFieldMapper$CompletionFieldType];
Caused by: SearchParseException[failed to parse search source [{"suggest":{"jobs":{"text":"712110","completion":{"field":"jobID","size":10,"context":{"jobs":[]}}}}}]]; nested: ClassCastException[org.elasticsearch.index.mapper.core.StringFieldMapper$StringFieldType cannot be cast to org.elasticsearch.index.mapper.core.CompletionFieldMapper$CompletionFieldType];
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:873)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:667)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:633)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:377)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)

Tested with almost every version of the 2.x branch with corresponding elastic4s releases.

**Comment by sksamuel** [comment]
Do you have some sample code ?

**Comment by zy4** [comment]
def jobIDcompletionSuggester(queryString : String) = { 
    client.execute {
      search in "tkplay_dev"->"jobs" suggestions (
        //completionSuggestion("jobs-completer") field "jobID" text queryString size 10 <-- tried both
        completionSuggestion field "jobID" text queryString size 10
      )
    }
  }

**Comment by sksamuel** [comment]
I think you just need to set the field to completion type. I've added some examples as tests in 2cbecac.
