### ISSUE TITLE
Disturbing log message - disconnecting from...due to explicit disconnect call

### ISSUE THREAD

**Issue by 123avi** [sksamuel/elastic4s#702]
Not sure that this is directly elastic4s issue. but I am getting the following message in my log:
```
[elasticsearch[Nobilus][generic][T#1]] DEBUG org.elasticsearch.transport.netty - [Nobilus] disconnecting from [{#transport#-2}{127.0.0.1}{127.0.0.1:9200}] due to explicit disconnect call
[elasticsearch[Nobilus][generic][T#1]] DEBUG org.elasticsearch.transport.netty - [Nobilus] connected to node [{#transport#-2}{127.0.0.1}{127.0.0.1:9200}]
[elasticsearch[Nobilus][generic][T#1]] INFO org.elasticsearch.client.transport - [Nobilus] failed to get node info for {#transport#-2}{127.0.0.1}{127.0.0.1:9200}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][127.0.0.1:9200][cluster:monitor/nodes/liveness] request_id [72] timed out after [5005ms]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:696)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
although index works and I can query the elasticsearch 
this is how I build my client :
```
val hosts = "127.0.0.1:9200,127.0.0.1:9300"
val settings = Settings
      .settingsBuilder()
      .put("cluster.name", "myindex")
      .put("client.transport.sniff", false) 
      .build

    ElasticClient.transport(settings, ElasticsearchClientUri(hosts))
```
localhost:9200 yields:
```
{
  "name" : "Ravage 2099",
  "cluster_name" : "myindex",
  "cluster_uuid" : "VTTdWUq_QoeBzNJjRvNFZA",
  "version" : {
    "number" : "2.4.3",
    "build_hash" : "d38a34e7b75af4e17ead16f156feffa432b22be3",
    "build_timestamp" : "2016-12-07T16:28:56Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.2"
  },
  "tagline" : "You Know, for Search"
}
```
Please advise

**Comment by sksamuel** [comment]
9200 is http so don't include that in your hosts. Not sure if that's the cause of the exception.

**Comment by 123avi** [comment]
yeap, that helps ... ;)
