### ISSUE TITLE
constantScoreQuery throws MatchError from HttpClient

### ISSUE THREAD

**Issue by hekaldama** [sksamuel/elastic4s#738]
I currently have the code:
```scala
val client = HttpClient(ElasticsearchClientUri(baseUrl))

client.execute {
  search(index) query {
    constantScoreQuery {
      termsQuery(field, values)
    }
  }
}
```
and it is throwing a `MatchError` with stacktrace:
```scala
ConstantScoreDefinition(TermsQueryDefinition(field,List(value),None,None,None,None,None),None,None) (of class com.sksamuel.elastic4s.searches.queries.ConstantScoreDefinition)
scala.MatchError: ConstantScoreDefinition(TermsQueryDefinition(field,List(value),None,None,None,None,None),None,None) (of class com.sksamuel.elastic4s.searches.queries.ConstantScoreDefinition)
	at com.sksamuel.elastic4s.http.search.queries.QueryBuilderFn$.apply(QueryBuilderFn.scala:9)
	at com.sksamuel.elastic4s.http.search.SearchBodyBuilderFn$$anonfun$apply$1.apply(SearchBodyBuilderFn.scala:18)
	at com.sksamuel.elastic4s.http.search.SearchBodyBuilderFn$$anonfun$apply$1.apply(SearchBodyBuilderFn.scala:18)
	at scala.Option.map(Option.scala:146)
	at com.sksamuel.elastic4s.http.search.SearchBodyBuilderFn$.apply(SearchBodyBuilderFn.scala:18)
	at com.sksamuel.elastic4s.http.search.SearchImplicits$SearchHttpExecutable$.execute(SearchImplicits.scala:71)
	at com.sksamuel.elastic4s.http.search.SearchImplicits$SearchHttpExecutable$.execute(SearchImplicits.scala:45)
	at com.sksamuel.elastic4s.http.HttpClient$class.execute(HttpClient.scala:32)
	at com.sksamuel.elastic4s.http.HttpClient$$anon$1.execute(HttpClient.scala:46)
...
```

It seems like `QueryBuilderFn` needs a handler for `ConstantScoreDefinition`. Seems like `ConstantScoreBuilder` would work but that is in tcp package.

Can `HttpClient` have this same functionality? If so, is it as easy as copying over `ConstantScoreDefinition` into the http package?

Thanks in advance

**Comment by sksamuel** [comment]
`ConstantScoreDefinition` is in core, so common to both clients. You need to add a `ConstantScoreBodyFn` which terms it into the JSON.

**Comment by hekaldama** [comment]
Should it be `ConstantScoreBodyFn` or `ConstantScoreQueryBodyFn`?

**Comment by sksamuel** [comment]
Don't mind.

**Comment by hekaldama** [comment]
Here is what I have so far:
```diff
diff --git a/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/queries/ConstantScoreBodyFn.scala b/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/queries/ConstantScoreBodyFn.scala
new file mode 100644
index 0000000..fffedc7
--- /dev/null
+++ b/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/queries/ConstantScoreBodyFn.scala
@@ -0,0 +1,19 @@
+package com.sksamuel.elastic4s.http.search.queries
+
+import com.sksamuel.elastic4s.searches.queries.ConstantScoreDefinition
+import org.elasticsearch.common.xcontent.{XContentBuilder, XContentFactory}
+
+object ConstantScoreBodyFn{
+  def apply(q: ConstantScoreDefinition): XContentBuilder = {
+    val builder = XContentFactory.jsonBuilder()
+    builder.startObject()
+    builder.startObject("constant_score")
+    builder.startObject("filter")
+    // TODO need to somehow allow QueryDefinitions in here
+    builder.endObject()
+    q.boost.map(_.toString).foreach(builder.field("boost", _))
+    q.queryName.foreach(builder.field("_name", _))
+    builder.endObject()
+    builder.endObject()
+  }
+}
diff --git a/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/queries/QueryBuilderFn.scala b/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/queries/QueryBuilderFn.scala
index be2a3fb..276fbfe 100644
--- a/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/queries/QueryBuilderFn.scala
+++ b/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/queries/QueryBuilderFn.scala
@@ -9,6 +9,7 @@ object QueryBuilderFn {
   def apply(q: QueryDefinition): XContentBuilder = q match {
     case b: BoolQueryDefinition => BoolQueryBuilderFn(b)
     case q: CommonTermsQueryDefinition => CommonTermsQueryBodyFn(q)
+    case q: ConstantScoreDefinition => ConstantScoreBodyFn(q)
     case q: ExistsQueryDefinition => ExistsQueryBodyFn(q)
     case q: IdQueryDefinition => IdQueryBodyFn(q)
     case q: MatchQueryDefinition => MatchBodyFn(q)
diff --git a/elastic4s-tests/src/test/scala/com/sksamuel/elastic4s/search/SearchHttpTest.scala b/elastic4s-tests/src/test/scala/com/sksamuel/elastic4s/search/SearchHttpTest.scala
index d8ceafd..43a82a8 100644
--- a/elastic4s-tests/src/test/scala/com/sksamuel/elastic4s/search/SearchHttpTest.scala
+++ b/elastic4s-tests/src/test/scala/com/sksamuel/elastic4s/search/SearchHttpTest.scala
@@ -122,6 +122,17 @@ class SearchHttpTest
         search("chess" / "pieces") query matchAllQuery() sourceExclude "count"
       }.await.hits.hits.map(_.sourceAsString).toSet shouldBe Set("{\"name\":\"pawn\",\"value\":1}", "{\"name\":\"knight\",\"value\":3}", "{\"name\":\"king\",\"value\":0}", "{\"name\":\"rook\",\"value\":5}", "{\"name\":\"queen\",\"value\":10}", "{\"name\":\"bishop\",\"value\":3}")
     }
+    "support constantScoreQuery" in {
+      val resp = http.execute {
+        search("chess" / "pieces") query {
+          constantScoreQuery {
+            termQuery("name", "pawn")
+          } boost 14.5 queryName "namey"
+        }
+      }.await
+      // TODO remove
+      println(resp)
+    }
   }
 }
```

Any direction on the first `TODO` of allowing `QueryDefinition` in there? I see tcp tests doing a query like:

SearchDslTest.scala
```scala
search("music") types "bands" query {
  constantScoreQuery {
    termQuery("name", "sammy")
  } boost 14.5
}
```

My test is attempting that and is not failing, but the debug output shows that nothing is being populated for the `terms` object in the JSON.

Thanks.

**Comment by sksamuel** [comment]
You can just recursively call the QueryBuilderFn - see how the Bool Builder does it for elastic-http.

**Comment by hekaldama** [comment]
k, I was looking at that, will keep looking. ty

**Comment by sksamuel** [comment]
Like (just off top of my head)

```scala
 val builder = XContentFactory.jsonBuilder()
    builder.startObject()
    builder.startObject("constant_score")
    builder.startObject("filter")
    builder.rawField("filter", QueryBuilderFn(req.filter))
    builder.endObject()
    q.boost.map(_.toString).foreach(builder.field("boost", _))
   q.queryName.foreach(builder.field("_name", _))
    builder.endObject()
    builder.endObject()
```

**Comment by hekaldama** [comment]
I am stuck on where `filter` comes from or even `req` in that example. I thought maybe `ConstantScoreDefinition` would need a `filter` param passed to the constructor, but somehow the tcp version is able to handle it so I didn't think that was the right way to go.

Thanks again.

**Comment by sksamuel** [comment]
```scala
object MatchAllBodyFn {
  def apply(q: ConstantScoreDefinition): XContentBuilder = {
    val builder = XContentFactory.jsonBuilder()
    builder.startObject()
    builder.startObject("constant_score")
    builder.rawField("filter", QueryBuilderFn(q.query))
    q.boost.foreach(builder.field("boost", _))
    q.queryName.foreach(builder.field("_name", _))
    builder.endObject()
    builder.endObject()
  }
}
```

Filter is the query that you embed. It's called filter in the json https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-constant-score-query.html

Then `QueryBuilderFn` can be updated in the match.
