### ISSUE TITLE
Process content-type and encoding headers in http-client

### ISSUE THREAD

**Issue by muuki88** [sksamuel/elastic4s#832]
The current `HttpExecutable#onSuccess` implementation is very basic

```scala
override def onSuccess(r: Response): Unit = {
   logger.debug(s"onSuccess $r")
   val result = Try {
     format.fromJson(Source.fromInputStream(r.getEntity.getContent).mkString)
   }
   p.tryComplete(result)
}
```

It would be helpful to use some of the response information for more sophisticated error messages

* `status` code -> 5xx lead to an `Failure`  with the necessary request information
* `getContentType` to check for a valid content-type (e.g. when firewalls block access and return html or text)
* `getContentEncoding` to determine the correct `scala.io.Codec` to decode the response

**Comment by pahomovda** [comment]
If want to confirm this issue.
When you try to recieve uft8 responce from Elasticsearch you can probably get an `MalformedInputException`
It is caused by `def fromInputStream(is: InputStream)(implicit codec: Codec): BufferedSource`. [Default implicit for Codec](https://github.com/scala/scala/blob/v2.12.1/src/library/scala/io/Codec.scala#L88) will call `Charset.defaultCharset`  which will use default charset of jvm.
We were able to work around this issue for now using `-Dfile.encoding=UTF-8`

**Comment by ddmng** [comment]
Hi.
@pahomovda the `-Dfile.encoding=UTF-8` parameter does not work for me. The issue for me is a large String field with some binary data. I tried to exclude it in the query but now I have the following error

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.elasticsearch.common.logging.DeprecationLogger.<clinit>(DeprecationLogger.java:138)
	at org.elasticsearch.search.fetch.subphase.FetchSourceContext.<clinit>(FetchSourceContext.java:48)
	at com.sksamuel.elastic4s.searches.SearchDefinition.sourceFiltering(SearchDefinition.scala:274)
	at com.sksamuel.elastic4s.searches.SearchDefinition.sourceExclude(SearchDefinition.scala:270)
...
Caused by: java.lang.IllegalStateException: Error finding the build shortHash. Stopping Elasticsearch now so it doesn't run in subtly broken ways. This is likely a build bug.
	at org.elasticsearch.Build.<clinit>(Build.java:62)
	... 32 more
```

I'm connecting with the 5.3.2 elastic4s client to a 2.3.2 elastic cluster.

Any idea on how can I workaround it?
thanks

**Comment by sksamuel** [comment]
Content encoding is handled properly in 5.4.
