### ISSUE TITLE
Regex issue with ElasticsearchClientUri

### ISSUE THREAD

**Issue by rulanitee** [sksamuel/elastic4s#855]
Hi, i am experiencing a regex error as shown below, together with the build sbt and code for declaring the client. Kindly asking for assistance regarding this issue. Need to know if i am doing something wrong.

The sbt:
scalaVersion := "2.12.1"
libraryDependencies += "com.sksamuel.elastic4s" % "elastic4s-tcp_2.12" % "5.2.11"
libraryDependencies += "com.sksamuel.elastic4s" % "elastic4s-core_2.12" % "5.2.11"

The code:
Client declaration is as follows:
 val client = TcpClient.transport(ElasticsearchClientUri("my host", 9300))

The Exception:
Exception in thread "main" java.lang.NoSuchMethodError: scala.util.matching.Regex.unapplySeq(Ljava/lang/CharSequence;)Lscala/Option;
	at com.sksamuel.elastic4s.ElasticsearchClientUri$.apply(ElasticsearchClientUri.scala:20)
	at com.sksamuel.elastic4s.ElasticsearchClientUri$.apply(ElasticsearchClientUri.scala:16)
	at EsMain$.main(EsMain.scala:18)
	at EsMain.main(EsMain.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by sksamuel** [comment]
Can you make a small example that re-creates this.

**Comment by rulanitee** [comment]
Hi Stephen, the problem is the spark version i am using -1.6.2- which is for scala version 2.10.x. Therefore, i am closing this issue. 

Thank you for the response and the great work you and the rest of the community is doing ...
