### ISSUE TITLE
XPack authentication throws NoNodeAvailableException instead of a authentication related exception

### ISSUE THREAD

**Issue by aifred** [sksamuel/elastic4s#870]
A NoNodeAvailableException is thrown when a incorrect credential is used to access elastic search via the TCP. It works perfectly if I use a valid credential (default xpack user: elastic, password: changeme). Attached a snippet of the stack trace for verification.

org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{XTdOuK_fR62aQVbI3MrpkQ}{localhost}{127.0.0.1:9300}]
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{XTdOuK_fR62aQVbI3MrpkQ}{localhost}{127.0.0.1:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:328)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:226)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:345)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:403)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1226)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.delete(AbstractClient.java:1367)
	at com.sksamuel.elastic4s.indexes.DeleteIndexDsl$DeleteIndexDefinitionExecutable$$anonfun$apply$1.apply(DeleteIndexDsl.scala:17)
	at com.sksamuel.elastic4s.indexes.DeleteIndexDsl$DeleteIndexDefinitionExecutable$$anonfun$apply$1.apply(DeleteIndexDsl.scala:17)
	at com.sksamuel.elastic4s.Executable$class.injectFuture(Executable.scala:30)
	at com.sksamuel.elastic4s.indexes.DeleteIndexDsl$DeleteIndexDefinitionExecutable$.injectFuture(DeleteIndexDsl.scala:14)
	at com.sksamuel.elastic4s.indexes.DeleteIndexDsl$DeleteIndexDefinitionExecutable$.apply(DeleteIndexDsl.scala:17)
	at com.sksamuel.elastic4s.indexes.DeleteIndexDsl$DeleteIndexDefinitionExecutable$.apply(DeleteIndexDsl.scala:14)
	at com.sksamuel.elastic4s.ElasticClient$class.execute(ElasticClient.scala:21)
	at com.sksamuel.elastic4s.ElasticClient$$anon$1.execute(ElasticClient.scala:41)

**Comment by sksamuel** [comment]
This is the exception thrown by elasticsearch itself, which this client just wraps. So I guess we should stick to what the java client does.
