### ISSUE TITLE
Lucene dependency needs to be 6.5.0

### ISSUE THREAD

**Issue by kyal** [sksamuel/elastic4s#903]
java.lang.NoSuchFieldError: LUCENE_5_5_4 at org.elasticsearch.Version.<clinit>(Version.java:85)

**Comment by sksamuel** [comment]
Thanks, fixed in 5.4.1.

**Comment by Yasaswani** [comment]
We are upgrading from elasticsearch 2.4 to 5.6.9. Getting an exception when trying to start the elasticsearch node in embedded mode.

We see that LUCENE_5_5_4 field is not present in org.apache.lucene.util.Version of lucene-core 5.5.2 jar 
where as the same is present in org.apache.lucene.util.Version of lucene-core 6.6.21 jar .
Any pointers on this issue?

Exception in thread "StartupTaskUtil INITIALIZE_SEARCH" java.lang.NoSuchFieldError: LUCENE_5_5_4
               at org.elasticsearch.Version.<clinit>(Version.java:85)
               at org.elasticsearch.common.io.stream.StreamOutput.<init>(StreamOutput.java:74)
               at org.elasticsearch.common.io.stream.BytesStream.<init>(BytesStream.java:24)
               at org.elasticsearch.common.io.stream.BytesStreamOutput.<init>(BytesStreamOutput.java:59)
               at org.elasticsearch.common.io.stream.BytesStreamOutput.<init>(BytesStreamOutput.java:56)
               at org.elasticsearch.common.io.stream.BytesStreamOutput.<init>(BytesStreamOutput.java:46)
               at org.elasticsearch.common.xcontent.XContentBuilder.builder(XContentBuilder.java:68)
               at org.elasticsearch.common.settings.Setting.arrayToParsableString(Setting.java:995)
               at org.elasticsearch.common.settings.Setting.access$600(Setting.java:80)
               at org.elasticsearch.common.settings.Setting$ListSetting.lambda$new$0(Setting.java:693)
               at org.elasticsearch.common.settings.Setting$ListSetting.getRaw(Setting.java:701)
               at org.elasticsearch.common.settings.Setting.lambda$listSetting$27(Setting.java:959)
               at org.elasticsearch.common.settings.Setting.listSetting(Setting.java:964)
               at org.elasticsearch.common.settings.Setting.listSetting(Setting.java:959)
               at org.elasticsearch.env.Environment.<clinit>(Environment.java:60)
