### ISSUE TITLE
java.util.NoSuchElementException for innerHits accessor function

### ISSUE THREAD

**Issue by oguzalbayrakDH** [sksamuel/elastic4s#908]
Hi, i was making a request as a nested query and i get a succesfull response
The response contains two results as i see from the debugger, and there is a inner_hits result inside them
But when i call innerHits function i get an exception (the stack trace is at the end of the issue)
```
resp.hits.hits.map(searchHit=> {
    searchHit.innerHits
})
```
As i have seen the code inside the library is as follows
```
  def innerHits: Map[String, InnerHits] = Option(inner_hits).getOrElse(Map.empty).mapValues {
    case hits =>
      val v = hits("hits").asInstanceOf[Map[String, AnyRef]]
      InnerHits(
        total = v("total").asInstanceOf[Int],
        max_score = v("max_score").asInstanceOf[Double],
        hits = v("hits").asInstanceOf[Seq[Map[String, AnyRef]]].map { hits =>
          InnerHit(
            _nested = hits("_nested").asInstanceOf[Map[String, AnyRef]],
            _score = hits("_score").asInstanceOf[Double],
            _source = hits("_source").asInstanceOf[Map[String, AnyRef]],
            highlight = hits("highlight").asInstanceOf[Map[String, Seq[String]]]
          )
        }
      )
  }
```
Which means in the case that there is no highlighting it will fail
And there is no way i can evade this with a workaround because i can not access the inner_hits (which i shouldn't already i guess)
```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NoSuchElementException: key not found: highlight]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
Caused by: java.util.NoSuchElementException: key not found: highlight
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at com.sksamuel.elastic4s.http.search.SearchHit$$anonfun$innerHits$2$$anonfun$apply$1.apply(responses.scala:54)
	at com.sksamuel.elastic4s.http.search.SearchHit$$anonfun$innerHits$2$$anonfun$apply$1.apply(responses.scala:49)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
```

**Comment by oguzalbayrakDH** [comment]
Hi,
I was running the tests inside the project, and have seen that the tests are using tcp client, and the tcp client implements this as
```
  def innerHits: Map[String, SearchHits] = Option(java.getInnerHits).map(_.asScala.toMap).getOrElse(Map.empty)
```
Which works as intended meanwhile the http client is suffering because of the code i posted before
I still haven't exactly understand how the tests works, but it looks like the code that tests the innerHits parsing part is not using the http client since the LocalNode.scala is using only the tcp client (i might be wrong)

**Comment by sksamuel** [comment]
Fixed in the next release (which will be 5.4.3).

**Comment by oguzalb** [comment]
Thanks!

**Comment by oguzalb** [comment]
Hi, sorry i forgot adding the version i m having the trouble with
it is 5.3.2
will the solution be included in that version also?
