### ISSUE TITLE
CompletionSuggestionDefinition is not matched inside http client while parsing the response

### ISSUE THREAD

**Issue by oguzalbayrakDH** [sksamuel/elastic4s#914]
Hello,
CompletionSuggestionDefinition is not matched inside http client while parsing the response, so when the user tries to parse a completionSuggestion response a MatchError is raised from the http client
This is the library code inside SearchBodyBuilderFn.scala that causes the problem
```
    if (request.suggs.nonEmpty) {
      builder.startObject("suggest")
      request.suggs.foreach {
        case term: TermSuggestionDefinition =>
          builder.startObject(term.name)
          term.text.foreach(builder.field("text", _))
          builder.startObject("term")
          builder.field("field", term.fieldname)
          term.analyzer.foreach(builder.field("analyzer", _))
          term.lowercaseTerms.foreach(builder.field("lowercase_terms", _))
          term.maxEdits.foreach(builder.field("max_edits", _))
          term.minWordLength.foreach(builder.field("min_word_length", _))
          term.maxInspections.foreach(builder.field("max_inspections", _))
          term.minDocFreq.foreach(builder.field("min_doc_freq", _))
          term.maxTermFreq.foreach(builder.field("max_term_freq", _))
          term.prefixLength.foreach(builder.field("prefix_length", _))
          term.size.foreach(builder.field("size", _))
          term.shardSize.foreach(builder.field("shard_size", _))
          term.sort.map(_.name().toLowerCase).foreach(builder.field("sort", _))
          term.stringDistance.map(_.name.toLowerCase).foreach(builder.field("string_distance", _))
          term.suggestMode.map(_.name().toLowerCase).foreach(builder.field("suggest_mode", _))
          builder.endObject()
          builder.endObject()
      }
      builder.endObject()
    }
```

this is what i got using completionSuggestion in a query

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[MatchError: CompletionSuggestionDefinition(mysugg,title,None,None,None,None,None,None,None,None,None,None,None,None,Some(/)) (of class com.sksamuel.elastic4s.searches.suggestion.CompletionSuggestionDefinition)]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
Caused by: scala.MatchError: CompletionSuggestionDefinition(mysugg,title,None,None,None,None,None,None,None,None,None,None,None,None,Some(/)) (of class com.sksamuel.elastic4s.searches.suggestion.CompletionSuggestionDefinition)
	at com.sksamuel.elastic4s.http.search.SearchBodyBuilderFn$$anonfun$apply$7.apply(SearchBodyBuilderFn.scala:45)
	at com.sksamuel.elastic4s.http.search.SearchBodyBuilderFn$$anonfun$apply$7.apply(SearchBodyBuilderFn.scala:45)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.sksamuel.elastic4s.http.search.SearchBodyBuilderFn$.apply(SearchBodyBuilderFn.scala:45)
	at com.sksamuel.elastic4s.http.search.SearchImplicits$SearchHttpExecutable$.execute(SearchImplicits.scala:72)
	at com.sksamuel.elastic4s.http.search.SearchImplicits$SearchHttpExecutable$.execute(SearchImplicits.scala:45)
	at com.sksamuel.elastic4s.http.HttpClient$class.execute(HttpClient.scala:36)
	at com.sksamuel.elastic4s.http.HttpClient$$anon$1.execute(HttpClient.scala:50)
	at controllers.HomeController$$anonfun$autocomplete$1.apply(HomeController.scala:313)
```

**Comment by sksamuel** [comment]
Do you want to add a PR?

**Comment by oguzalbayrakDH** [comment]
still haven't figured out things, i ll try to make a PR with the next bug i come with

**Comment by oguzalb** [comment]
still haven't figured out things, i ll try to make a PR with the next bug i come with

**Comment by oguzalbayrakDH** [comment]
Hi, sorry i forgot adding the version i m having the trouble with
it is 5.3.2

**Comment by oguzalb** [comment]
Hi, sorry i forgot adding the version i m having the trouble with
it is 5.3.2

**Comment by houranketabdarDH** [comment]
Hi, i have the same error. Is there any solution for that?

**Comment by sksamuel** [comment]
It'll be added to 6.0 unless someone does a PR first for 5.4.x
