### ISSUE TITLE
UnmappableCharacterException when operating non-ASCII characters

### ISSUE THREAD

**Issue by frozenspider** [sksamuel/elastic4s#928]
When using non-ASCII characters, elastic4s fails with exception upon inserting it.
```scala
object SSCCE extends App {
  import com.sksamuel.elastic4s.http.ElasticDsl._

  val esClient: HttpClient = HttpClient(ElasticsearchClientUri("localhost", 9200))
  val str = "☃"
  esClient.execute {
    indexInto("a" / "b").fields("oops" -> str)
  }.await
}
```
will lead to
```
java.nio.charset.UnmappableCharacterException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:282) ~[na:1.8.0_121]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339) ~[na:1.8.0_121]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[na:1.8.0_121]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[na:1.8.0_121]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[na:1.8.0_121]
	at java.io.BufferedReader.readLine(BufferedReader.java:324) ~[na:1.8.0_121]
	at java.io.BufferedReader.readLine(BufferedReader.java:389) ~[na:1.8.0_121]
	at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:72) ~[scala-library-2.11.8.jar:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:893) ~[scala-library-2.11.8.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336) ~[scala-library-2.11.8.jar:na]
	at scala.collection.TraversableOnce$class.addString(TraversableOnce.scala:357) ~[scala-library-2.11.8.jar:na]
	at scala.collection.AbstractIterator.addString(Iterator.scala:1336) ~[scala-library-2.11.8.jar:na]
	at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:323) ~[scala-library-2.11.8.jar:na]
	at scala.collection.AbstractIterator.mkString(Iterator.scala:1336) ~[scala-library-2.11.8.jar:na]
	at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:325) ~[scala-library-2.11.8.jar:na]
	at scala.collection.AbstractIterator.mkString(Iterator.scala:1336) ~[scala-library-2.11.8.jar:na]
	at com.sksamuel.elastic4s.http.HttpExecutable$RichRestClient.async(HttpExecutable.scala:48) ~[elastic4s-http_2.11-5.4.3.jar:5.4.3]
	at com.sksamuel.elastic4s.http.index.IndexImplicits$IndexHttpExecutable$.execute(IndexImplicits.scala:39) ~[elastic4s-http_2.11-5.4.3.jar:5.4.3]
	at com.sksamuel.elastic4s.http.index.IndexImplicits$IndexHttpExecutable$.execute(IndexImplicits.scala:12) ~[elastic4s-http_2.11-5.4.3.jar:5.4.3]
	at com.sksamuel.elastic4s.http.HttpClient$class.execute(HttpClient.scala:23) ~[elastic4s-http_2.11-5.4.3.jar:5.4.3]
	at com.sksamuel.elastic4s.http.HttpClient$$anon$1.execute(HttpClient.scala:37) ~[elastic4s-http_2.11-5.4.3.jar:5.4.3]
```
This is because in `HttpExecutable:L48`
```
logger.debug(Source.fromInputStream(entity.getContent).getLines().mkString("\n"))
```
`Source.fromInputStream` uses default codec instead of UTF-8, so logging statement breaks the client. In my case (play framework) it happens to be `windows-1251`.
This bug is pretty severe, and might be affecting other places as well.

**Comment by sksamuel** [comment]
Thanks, updated.
