### ISSUE TITLE
GeoShapeDefinition missing in http client?

### ISSUE THREAD

**Issue by runebarikmo** [sksamuel/elastic4s#931]
Hi. I just switched to the http client and it caused my geoShapeQuery to fail. 

Is there a reason GeoShapeDefinition case is missing while GeoBoundingBoxQueryDefinition,GeoDistanceQueryDefinition and GeoPolygonQueryDefinition is implemented? 

Thanks

```
query: 

geoShapeQuery(
  "location",
  new PointBuilder().coordinate(new Coordinate(point.easting,point.northing))
)

Error:

[info]   scala.MatchError: GeoShapeDefinition(location,{
[info]   "geo_shape" : {
[info]     "location" : {
[info]       "shape" : {
[info]         "type" : "point",
[info]         "coordinates" : [
[info]           11.084543,
[info]           59.962241
[info]         ]
[info]       },
[info]       "relation" : "intersects"
[info]     },
[info]     "ignore_unmapped" : false,
[info]     "boost" : 1.0
[info]   }
[info] },None,None,None,None,None,None,None) (of class com.sksamuel.elastic4s.searches.queries.geo.GeoShapeDefinition)
[info]   at com.sksamuel.elastic4s.http.search.queries.QueryBuilderFn$.apply(QueryBuilderFn.scala:19)
[info]   at com.sksamuel.elastic4s.http.search.queries.compound.BoolQueryBuilderFn$$anonfun$1.apply(BoolQueryBuilderFn.scala:17)
[info]   at com.sksamuel.elastic4s.http.search.queries.compound.BoolQueryBuilderFn$$anonfun$1.apply(BoolQueryBuilderFn.scala:17)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[info]   at scala.collection.Iterator$class.foreach(Iterator.scala:891)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
[info]   at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[info]   at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[info]   ...

```

**Comment by sksamuel** [comment]
This was taken out during the initial development of the http client. I've added it back in now, slightly tweaked. It'll be in 6.0.0-rc2.

**Comment by runebarikmo** [comment]
Awesome. Thanks. I will check out the new version
