### ISSUE TITLE
Sniff fails when using elastic4s 5.4.x

### ISSUE THREAD

**Issue by franbh** [sksamuel/elastic4s#939]
Using elastic4s (TCP) 5.4.3, ES 5.4.0 or 5.4.1, and sniff activated, we get the following exception:

> failed to get local cluster state for {#transport#-1}{Pwx0fHKZTymHvuGa_rDQwA} elasticsearch.service.os.des.wr}{10.130.2.2:9300}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][10.130.2.2:9300][cluster:monitor/state] request_id [214] timed out after [5000ms]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:925)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

This is a known bug fixed in ES 5.4.1. See https://www.elastic.co/guide/en/elasticsearch/reference/5.4/release-notes-5.4.1.html (SniffNodesSampler should close connection after handling responses #24632 (issues: #22828, #24557, #24575))

I've just tested our code by upgrading to ES client 5.4.1 (using dependency eviction) and everything works OK. Therefore, it would be great if a new release is done including the ES client 5.4.1 upgrade, so I'm going to provide you with a PR ASAP.

Thanks so much in advance.

**Comment by sksamuel** [comment]
PR merged, will release tonight.

**Comment by franbh** [comment]
Thanks again!
