### ISSUE TITLE
Flaky error with ElasticSugar

### ISSUE THREAD

**Issue by yannick-cw** [sksamuel/elastic4s#990]
After upgrading to `5.4.5` from `2.x.x` version we sometimes run into this error in our integration tests using `ElasticSugar`.

```
java.lang.IllegalStateException: availableProcessors is already set to [8], rejecting [8]
[info]   at io.netty.util.NettyRuntime$AvailableProcessorsHolder.setAvailableProcessors(NettyRuntime.java:51)
[info]   at io.netty.util.NettyRuntime.setAvailableProcessors(NettyRuntime.java:87)
[info]   at org.elasticsearch.transport.netty4.Netty4Utils.setAvailableProcessors(Netty4Utils.java:82)
[info]   at org.elasticsearch.http.netty4.Netty4HttpServerTransport.<init>(Netty4HttpServerTransport.java:219)
[info]   at org.elasticsearch.transport.Netty4Plugin.lambda$getHttpTransports$1(Netty4Plugin.java:105)
[info]   at org.elasticsearch.node.Node.<init>(Node.java:430)
[info]   at com.sksamuel.elastic4s.embedded.LocalNode.<init>(LocalNode.scala:21)
[info]   at com.sksamuel.elastic4s.embedded.LocalNode$.apply(LocalNode.scala:117)
[info]   at com.sksamuel.elastic4s.embedded.LocalNode$.apply(LocalNode.scala:121)
[info]   at com.sksamuel.elastic4s.embedded.LocalNode$.apply(LocalNode.scala:144)
```
 Do you have any idea what could cause that?

**Comment by sksamuel** [comment]
It's because it's trying to create a new node, it can't find the other one for some reason. I see it myself sometimes and I don't know the root cause.

**Comment by yannick-cw** [comment]
Okay damn, that really hurts our CI from time to time, I might try some digging if I can find anything.

**Comment by sksamuel** [comment]
My guess has always been classloader related - in that the other node is on a different classloader so it tries to make a new one. But I've tried a lot of things, including a new discovery based sugar which you can see in master.

**Comment by yannick-cw** [comment]
Ah nice I'll have a look at this one, then it does not look good :)

**Comment by WayneWang12** [comment]
I get across the same error. What I have done is to start the node again as below:
```
  lazy val localNode = {
    val clusterName = "tag-query"
    val dataTargetFile = "target/elastic"
    Try(LocalNode(clusterName, dataTargetFile)).recover {
      case e: IllegalStateException =>
        LocalNode(clusterName, dataTargetFile)
    }
  }.get
```
It seems working.

**Comment by sksamuel** [comment]
That is very odd that it works.

**Comment by yannick-cw** [comment]
Similar quick fix for me, the error seems to be pretty rare, I have never seen it appear more than two times in a row, so this should catch it anyway.
Some special condition at a certain time must lead to the exception..

```
trait RetryElasticSugar extends ElasticSugar {
  this: Suite =>

  private lazy val dir: Path  = Paths get System.getProperty("java.io.tmpdir")
  private lazy val home: Path = dir resolve UUID.randomUUID().toString

  override lazy val getNode: LocalNode = localNode(0)

  private def localNode(timesTried: Int): LocalNode =
    Try(LocalNode("node_" + ClassLocalNodeProvider.counter.getAndIncrement(), home.toAbsolutePath.toString)) match {
      case Failure(ex: IllegalStateException) if timesTried < 5 =>
        ex.printStackTrace()
        localNode(timesTried + 1)
      case Success(okNode) => okNode
      case Failure(other)  => throw other
    }
}
```

**Comment by sksamuel** [comment]
I'll update master with this. It certainly manifests itself a lot more on
6.0 than it did on 5.x.

**Comment by sksamuel** [comment]
I've added this to master. Fingers crossed.

**Comment by yannick-cw** [comment]
Cool I hope for the best :)
